:source-highlighter: coderay
:cf: http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/cf-conventions.html
[[threddsDocs]]


= *THREDDS Data Server* 5.0

== Overview

The THREDDS Data Server (TDS) is a web server that provides metadata and
data access for scientific datasets, using OPeNDAP, OGC WMS and WCS,
HTTP, and other remote data access protocols. The TDS is developed and
supported by Unidata, a division of the University Corporation for
Atmospheric Research (http://www.ucar.edu/[UCAR]), and is sponsored by
the National Science Foundation.

Some of the technology in the TDS:

1.  THREDDS <<catalog/index#,Dataset Inventory Catalogs>> are used
to provide virtual directories of available data and their associated
metadata. These catalogs can be generated dynamically or statically.
2.  The link:../netcdf-java/documentation.htm[Netcdf-Java/CDM library]
reads NetCDF, OpenDAP, and HDF5 datasets, as well as other binary
formats such as GRIB and NEXRAD into a Common Data Model (CDM),
essentially an (extended) netCDF view of the data. Datasets that can be
read through the Netcdf-Java library are called __CDM datasets__.
3.  TDS can use the link:../netcdf-java/ncml/index.htm[NetCDF Markup
Language] (NcML) to modify and create virtual aggregations of CDM
datasets.
4.  An integrated server provides http://www.opendap.org/[OPeNDAP]
access to any CDM dataset. OPeNDAP is a widely used, subsetting data
access method extending the HTTP protocol.
5.  An integrated server provides bulk file access through the HTTP
protocol.
6.  An integrated server provides data access through the
http://www.opengeospatial.org/standards/wcs[OpenGIS Consortium (OGC) Web
Coverage Service (WCS]) protocol, for any ``gridded'' dataset whose
coordinate system information is complete.
7.  An integrated server provides data access through the
http://www.opengeospatial.org/standards/wms[OpenGIS Consortium (OGC) Web
Map Service (WMS]) protocol, for any ``gridded'' dataset whose
coordinate system information is complete. This software was developed
by Jon Blower (University of Reading (UK) E-Science Center) as part of
the http://behemoth.nerc-essc.ac.uk/ncWMS/godiva2.html[ESSC Web Map
Service for environmental data] (aka Godiva2).
8.  The integrated <<reference/ncISO#,ncISO server>> provides
automated metadata analysis and ISO metadata generation.
9.  The integrated
<<reference/services/NetcdfSubsetServiceReference#,NetCDF Subset
Service>> allows subsetting certain CDM datasets in coordinate space,
using a REST API. Gridded data subsets can be returned in
http://cfconventions.org/[CF-compliant] netCDF-3 or netCDF-4. Point data
subsets can be returned in CSV, XML, or {cf}#discrete-sampling-geometries[CF-DSG] netCDF files.
10. The integrated
<<../netcdf-java/reference/stream/CdmRemote#,CDM Remote Service>>
provides index subsetting on remote CDM datasets, with the same
functionality that *NetcdfFile* provides for CDM local datasets and
*DODSNetcdfFile* provides for remote OPeNDAP datasets. _*CdmRemote*_
supports the full CDM data model.

The THREDDS Data Server is implemented in 100% Java*, and is contained
in a single war file, which allows very easy installation into a
http://en.wikipedia.org/wiki/Servlet_container[servlet container] such
as the open-source http://tomcat.apache.org/[Tomcat] web server.
Configuration is made as simple and as automatic as possible, and we
have made the server as secure as possible. The library is freely
available and the source code is released under the (MIT-style) netCDF
library
http://www.unidata.ucar.edu/software/netcdf/copyright.html[license].

*Writing to netCDF-4 files is supported through the netCDF C library
only.

Much of the realtime data available over the Unidata
http://www.unidata.ucar.edu/software/idd/index.html[Internet Data
Distribution] (IDD) is available through a THREDDS Data Server hosted at
Unidata on http://thredds.ucar.edu/thredds/[thredds.ucar.edu]. You are
welcome to browse and access these meteorological datasets. If you need
regular access to large amounts of data, please contact
support-idd@unidata.ucar.edu.

== System Requirements

Java 8 is strongly recommended for production use in all cases. Java 7
is no longer getting security updates.

* http://www.oracle.com/technetwork/java/javase/overview/index.html[Java]
version 8
* http://tomcat.apache.org/[Tomcat] version 8
* *Be sure to keep up with the latest versions of Java and Tomcat for
security fixes. This is required for publically accessible servers!*

== Downloads

*TDS 5.0 is the development release. It requires Tomcat 8 and Java 8.*

* Download the latest development release:
** link:ftp://ftp.unidata.ucar.edu/pub/thredds/5.0/current/thredds.war[thredds.war]
** link:ftp://ftp.unidata.ucar.edu/pub/thredds/5.0/current/thredds.war.md5[MD5]
** link:ftp://ftp.unidata.ucar.edu/pub/thredds/5.0/current/thredds.war.sha1[SHA1]
** link:https://github.com/Unidata/thredds[source on GitHub]
** link:https://artifacts.unidata.ucar.edu/#browse/search=repository_name%3Dunidata-releases%20AND%20name.raw%3Dtds[artifacts in Unitdata’s maven repository]
The THREDDS Data Manager (TDM)
** link:ftp://ftp.unidata.ucar.edu/pub/thredds/5.0/current/tdm-5.0.jar[tdm.jar]

== TDS Services

=== Standard TDS Services

* http://opendap.org/pdf/dap_2_data_model.pdf[OPeNDAP (DAP2) protocol]
* http://www.resc.rdg.ac.uk/trac/ncWMS/[ncWMS] implementing the
<<reference/WMS#,Web Map Service>>
* <<reference/WCS#,Web Coverage Service>>
* http://www.ngdc.noaa.gov/eds/tds/[ncISO]
* <<reference/services/NetcdfSubsetServiceReference#,Netcdf
Subset Services>>
* <<../netcdf-java/reference/stream/CdmRemote#,CdmRemote web
service>>

=== Experimental TDS Services

* <<../netcdf-java/reference/stream/CdmrFeature#,CdmrFeature web
service>>
* Radar Subset Service
** <<reference/radarServer/RadarLevel2SubsetService#,NEXRAD Level
2>>
** <<reference/radarServer/RadarLevel3SubsetService#,NEXRAD Level 3
>>

== Other ways to use TDS

* http://ferret.pmel.noaa.gov/LAS/documentation/the-ferret-thredds-data-server-f-tds/[The
Ferret-THREDDS Data Server (F-TDS)]
* http://www.resc.rdg.ac.uk/trac/ncWMS/[Godiva / ncWMS]

== Other Documentation

* <<catalog/index#,THREDDS Catalogs>>
* Fact Sheet
[http://www.unidata.ucar.edu/publications/factsheets/2007sheets/threddsFactSheet-1.doc[Word
Doc]]
[http://www.unidata.ucar.edu/publications/factsheets/2007sheets/threddsFactSheet-1.pdf[PDF]]
