:source-highlighter: coderay
[[threddsDocs]]


= TDS Installation Checklist for Production Security

== Initial Installation

=== Install Java

1.  link:images/fileIcon.jpg[Download and install] the latest version of
JDK 1.7

=== Tomcat Install

Create a <<Security#install,dedicated user and group for running
Tomcat>> who does not have root privileges.
<<Security#install,Modify the permissions>> in *$\{tomcat_home}*
to allow this user access to only the necessary parts of the Tomcat
installation.

link:images/fileIcon.jpg[Download and install] the latest version of
Tomcat 7.

In **$\{tomcat_home}/bin** <<GettingStarted#makeSetenv,create a
setenv.sh>> shell script, and set the values of *$JAVA_HOME, $JAVA_OPTS*
and **$CATALINA_BASE**:

-------------------------------------------------------------------------------------------------------------------------------------------------
      #!/bin/sh
      JAVA_HOME="/usr/local/tds/jdk1.7.0_60"
      export JAVA_HOME

      JAVA_OPTS="-Xmx4096m -Xms512m -server -Djava.awt.headless=true -Djava.util.prefs.systemRoot=$CATALINA_BASE/content/thredds/javaUtilPrefs"
      export JAVA_OPTS

      CATALINA_BASE="/usr/local/tds/apache-tomcat-7.0.42"
      export CATALINA_BASE
-------------------------------------------------------------------------------------------------------------------------------------------------

Purchase a real certificate from a
http://en.wikipedia.org/wiki/Certificate_authority[certificate
authority], so users are not confused and question the legitimacy of
your web site.

Make the following modifications to **$\{tomcat_home}/conf/server.xml**:

* <<Security#digested,Enable digest passwords>> by commenting out
the *UserDatabaseRealm* and enabling the **MemoryRealm**.
* <<Security#ssl,Enable SSL>> by uncommenting the SSL Connector
listening on port 8443, and add the required *keystoreFile* and
*keystorePass* attributes.
* link:../reference/Performance#enableCompression[Enable
compression] by adding *compression* and *compressableMimeType*
attributes to 8080 Connector.
* <<TDSMonitoringAndDebugging#access,Enable access logging>> by
uncommenting the *AccessLogValve* and change the *prefix* and *suffix*
and *pattern* attributes.

<<Security#digested,Create a password digest>> using the
*$\{tomcat_home}/bin/digest.sh* script.

Make the following modifications to
**$\{tomcat_home}/conf/tomcat-users.xml**:

* Define the roles <<GettingStarted#grantingAccess,manager-gui>>
and
<<examples/accessingTDSMonitoringAndDebuggingTools#,tdsConfig>>
and
<<examples/accessingTDSMonitoringAndDebuggingTools#,tdsMonitor>>.
* <<GettingStarted#grantingAccess,Add yourself as a user>> with
the roles manager-gui and tdsConfig using your digest password your
created in step #6 above.

Make the following modifications to
**$\{tomcat_home}/webapps/manager/WEB-INF/web.xml**:

1.  Make sure the manager is only
<<examples/tomcatManagerSSL#,available via SSL>> by adding a
user-data-constraint with a transport-guarantee of CONFIDENTIAL inside
the security-constraint element.

<<Security#unused,Remove any unused applications>> from
$\{tomcat_home}/webapps.

=== TDS Install

<<GettingStarted#deploying,Download>> the latest thredds.war
file, and put it into **$\{tomcat_home}/webapps**.

Start/restart Tomcat so that it has a chance to create initial files in
**$\{tomcat_home}/content/thredds**.

Modify *$\{tomcat_home}/content/thredds/catalog.xml* for your site, as
in this <<BasicConfigCatalogs#exampleCatalog,example>>.

Modify  **$\{tomcat_home}/content/thredds/threddsConfig.xml** for your
site in the following manner:

* Add the needed information to the
<<BasicThreddsConfig_xml#serverInfo,`serverInformation` element>>
* <<AddingServices#,Enable any other optional services>> like WMS
or WCS.

If needed, <<Security#access,limit access to the TDS>> and create
a robots.txt file in *$\{tomcat_home}/webapps/ROOT/* to restrict crawler
activity.

== Maintenance and Upgrades

=== Maintenance

*Be sure to periodically check to make sure you are running the
<<Security#versions,latest versions>> of Java, Tomcat and the
TDS.*

* If you have enabled <<TomcatAndTDSLogs#access,access logging>>
(and you should), zip up the unused access logs in
*$\{tomcat_home}/logs/* and archive them off to another directory.
* Likewise, zip up the unused link:TomcatAndTDSLogs#tds[TDS servlet
logs] in *$\{tomcat_home}/content/thredds/logs* and archive them as
well.

=== Upgrading the TDS

When installing a new thredds.war, everything in
*$\{tomcat_home}/webapps/* is overwritten. However, nothing in
*$\{tomcat_home}/content/* is overwritten.

Use one of the following methods to deploying a new version of the TDS

* <<GettingStarted#manager,Tomcat manager application>>
* <<GettingStarted#deploying,manual installation>>
