:source-highlighter: coderay
[[threddsDocs]]

= *Forecast Model Run Collection*

_last changed: Aug 11, 2006_

== 1. Current design to track GRIB inventory in the TDS

=== *ForecastModelRunInventory*

Encapsulates actual inventory of one GridDataset, writes ``.fmrInv.xml''
XML files to summarize the inventory. Reads it back if it exists,
instead of reading the GridDataset:

_________________________________________________________________________________________________________
public static ForecastModelRun **open**(ucar.nc2.util.DiskCache2 cache,
String ncfileLocation, int mode);

public static ForecastModelRun **readXML**(String xmlLocation);
_________________________________________________________________________________________________________

On motherlode, these files are created in a chron job.

There is some specialization for GRIB files, in order to determine the
missing data. A GridDataset will be square in vert X time coordinate,
but GRIB files may have missing planes that we want to track for
inventory purposes. This may not matter for formica.

-------------------------------------------------------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<forecastModelRun dataset="DGEX_Alaska_12km_20060317_1200.grib2" runTime="2006-03-17 12:00:00Z">

1)<vertCoord id="0" name="pressure" units="hPa">100000.0 85000.0 70000.0 50000.0 25000.0</vertCoord>
  <vertCoord id="1" name="pressure_difference" units="hPa">3000.0 6000.0 9000.0 12000.0 15000.0 18000.0</vertCoord>
  <vertCoord id="2" name="pressure4" units="hPa">85000.0 70000.0 50000.0</vertCoord>
  <vertCoord id="3" name="pressure1" units="hPa">85000.0 70000.0 50000.0 25000.0</vertCoord>

2)<offsetHours id="0">
    90.0 96.0 102.0 108.0 114.0 120.0 126.0 132.0 138.0 144.0 150.0 156.0 162.0 168.0 174.0 180.0 186.0 192.0
    <variable name="Geopotential_height" vert_id="0">
3)    <missing>9,0 9,3 10,0 10,3 11,1 11,2 11,4</missing>
    </variable>
    <variable name="Maximum_temperature" />
    <variable name="Minimum_temperature" />
    <variable name="Relative_humidity_pressure" vert_id="2">
      <missing>9,2 10,2 11,0 11,1</missing>
    </variable>
    <variable name="Surface_Lifted_Index" />
    <variable name="Temperature" vert_id="1">
      <missing>11,0 11,1 11,2 11,3</missing>
    </variable>
    <variable name="Temperature_pressure" vert_id="2">
      <missing>9,0 9,1 10,0 10,1 11,2</missing>
    </variable>
    <variable name="U_component_of_wind" vert_id="1">
      <missing>11,0 11,1 11,2</missing>
    </variable>
    <variable name="U_component_of_wind_pressure" vert_id="3">
      <missing>9,0 9,1 9,3 10,0 10,1 10,3 11,2</missing>
    </variable>
    <variable name="V_component_of_wind_pressure" vert_id="3">
      <missing>9,2 10,2 11,0 11,1 11,3</missing>
    </variable>
  </offsetHours>

  <offsetHours id="1">
    90.0
    <variable name="Geopotential_height_surface" />
  </offsetHours>

  <offsetHours id="2">
    90.0 96.0 102.0 108.0 114.0 120.0 126.0 132.0 138.0 144.0 150.0 162.0 168.0 174.0 180.0 186.0 192.0
    <variable name="MSLP_Eta_Reduction" />
    <variable name="Pressure" />
    <variable name="Relative_humidity_height_above_ground" />
    <variable name="V_component_of_wind_height_above_ground" />
  </offsetHours>

  <offsetHours id="3">
    90.0 96.0 102.0 108.0 114.0 120.0 126.0 132.0 138.0 144.0 156.0 162.0 168.0 174.0 180.0 186.0 192.0
    <variable name="Pressure_reduced_to_MSL" />
  </offsetHours>

  <offsetHours id="4">
    90.0 96.0 102.0 108.0 114.0 120.0 126.0 132.0 138.0 156.0 162.0 168.0 174.0 180.0 186.0 192.0
    <variable name="Relative_humidity" vert_id="1" />
    <variable name="Temperature_height_above_ground" />
    <variable name="Total_cloud_cover" />
    <variable name="U_component_of_wind_height_above_ground" />
    <variable name="V_component_of_wind" vert_id="1" />
    <variable name="Vertical_velocity_pressure" />
  </offsetHours>

  <offsetHours id="5">
    84.0 90.0 96.0 102.0 108.0 114.0 120.0 126.0 132.0 150.0 156.0 162.0 168.0 174.0 180.0 186.0
    <variable name="Total_precipitation" />
  </offsetHours>

4)<horizBB west="-139.530" east="-14.202" south="-0.569" north="32.405" />
</forecastModelRun>
-------------------------------------------------------------------------------------------------------------------

1.  The vertical coordinates, referenced by *vert_id* in the variable
elements.
2.  The set of offset hours, and the list of variables that use them.
Assumes hours: is that a problem?
3.  A list of missing planes for this variable (timeIndex, vertIndex),
reletive to the time X vert coordinate matrix.
4.  Optionally track the lat/lon bounding box.

This file is created without reference to the FmrcDefinition. If we had
it, could show the anomolies against that.

=== FmrcDefinition

Defines the expected inventory of a Forecast Model Run Collection.
Writes to an ``.fmrcDefinition.xml'' XML file. TDS keeps these in
https://thredds.ucar.edu/thredds/content/modelInventory/.

Can create one from a ForecastModelRunCollection:

_____________________________________________________________________________
public void **makeFromCollectionInventory**(ForecastModelRunCollection
fmrc);
_____________________________________________________________________________

You need to review and hand edit these. An example:

---------------------------------------------------------------------------------------------------------------------------------------------------------
  <?xml version="1.0" encoding="UTF-8"?>
1)<fmrcDefinition dataset="NCEP-NDFD-CONUS_5km" suffixFilter=".grib2">

2)  <vertCoord id="0" name="isobaric1">250.0 500.0 700.0 850.0</vertCoord>
    <vertCoord id="1" name="isobaric">250.0 300.0 500.0 700.0 850.0 1000.0</vertCoord>
    <vertCoord id="2" name="isobaric2">300.0 400.0 500.0 700.0 850.0 1000.0</vertCoord>

3)  <offsetHours id="0">0.0 12.0 24.0 36.0 48.0 60.0 72.0 84.0 96.0 108.0 120.0 132.0 144.0 156.0 168.0 180.0 192.0 204.0 216.0 228.0 240.0</offsetHours>
    <offsetHours id="1">12.0 24.0 36.0 48.0 60.0 72.0 84.0 96.0 108.0 120.0 132.0 144.0 156.0 168.0 180.0 192.0 204.0 216.0 228.0 240.0</offsetHours>
---------------------------------------------------------------------------------------------------------------------------------------------------------

---------------------------------------------------------------------------------------------
4)  <runSequence
  allUseSeq="0">
      <variable name="Absolute_vorticity" vertCoord="0" />
      <variable name="Geopotential_height" vertCoord="1" />
      <variable name="N5-wave_geopotential_height" />
      <variable name="Pressure_reduced_to_MSL" />
      <variable name="Relative_humidity" vertCoord="2" />
      <variable name="Relative_humidity_layer_between_two_pressure_difference_from_ground" />
      <variable name="Relative_humidity_layer_between_two_sigmas" />
      <variable name="Temperature" vertCoord="1" />
    </runSequence>

    <runSequence allUseSeq="1">
      <variable name="Convective_precipitation" />
      <variable name="Total_precipitation" />
     </runSequence>
  </fmrcDefinition>
---------------------------------------------------------------------------------------------

1.  A convenient place to specify that these files end in *_.grib2_*
2.  The possible vertical coordinates, referenced by *vertCoord* in the
variable elements. Maybe should have units?
3.  The possible time coordinates, represented as offset hours. Assumes
hours: is that a problem?
4.  The list of variables that use time coord 0, ie <offsetHours
id=``0''>. The *allUseSeq* means that all model runs use time coord 0.

If a model run collection can be represented by this format, it is
called *__regular__.* Things can be more complicated when different run
times use different time coordinates. We then need to represent the
collection as a sequence of runs, for example:

----------------------------------------------------------------
  <offsetHours id="0">0.0 1.0 2.0 3.0 6.0 9.0 12.0</offsetHours>
  <offsetHours id="1">0.0 1.0 2.0 3.0</offsetHours>
----------------------------------------------------------------

---------------------------------------------------
  <runSequence>
    <run runHour="0.0" offsetHourSeq="0" />
    <run runHour="1.0" offsetHourSeq="1" />
    <run runHour="2.0" offsetHourSeq="1" />
    <run runHour="3.0" offsetHourSeq="0" />
    <run runHour="4.0" offsetHourSeq="1" />
    <run runHour="5.0" offsetHourSeq="1" />
    <run runHour="6.0" offsetHourSeq="0" />
    <run runHour="7.0" offsetHourSeq="1" />
    <run runHour="8.0" offsetHourSeq="1" />
    <run runHour="9.0" offsetHourSeq="0" />
    <run runHour="10.0" offsetHourSeq="1" />
    <run runHour="11.0" offsetHourSeq="1" />
    <run runHour="12.0" offsetHourSeq="0" />
    <run runHour="13.0" offsetHourSeq="1" />
    <run runHour="14.0" offsetHourSeq="1" />
    <run runHour="15.0" offsetHourSeq="0" />
    <run runHour="16.0" offsetHourSeq="1" />
    <run runHour="17.0" offsetHourSeq="1" />
    <run runHour="18.0" offsetHourSeq="0" />
    <run runHour="19.0" offsetHourSeq="1" />
    <run runHour="20.0" offsetHourSeq="1" />
    <run runHour="21.0" offsetHourSeq="0" />
    <run runHour="22.0" offsetHourSeq="1" />
    <run runHour="23.0" offsetHourSeq="1" />
    <run runHour="24.0" offsetHourSeq="0" />

    <variable name="Accumulated_snow" />
    <variable name="Baseflow-groundwater_runoff" />
    <variable name="Cloud_water" vertCoord="0" />
    <variable name="Convective_Avail_Pot_Energy" />
  </runSequence>
---------------------------------------------------

Here the 0, 3, 6, etc hour *runs* have forecasts out to 9 hours, while
the rest go out to 3. Repeating patterns like this can be more concisely
represented like:

---------------------------------------------------
  <runSequence>
    <run runHour="0.0" offsetHourSeq="0" />
    <run runHour="1.0" offsetHourSeq="1" />
    <run runHour="2.0" offsetHourSeq="1" />
    <run runHour="3.0" offsetHourSeq="0" />

    <variable name="Accumulated_snow" />
    <variable name="Baseflow-groundwater_runoff" />
    <variable name="Cloud_water" vertCoord="0" />
    <variable name="Convective_Avail_Pot_Energy" />
  </runSequence>
---------------------------------------------------

In this case the first and last must have the same *offsetHourSeq* value
, and the pattern is generated out to 24 hours.

One more possible complication:

------------------------------------------------------------------------------
<vertCoord id="1" name="isobaric1">200.0 300.0 500.0 700.0 850.0</vertCoord>
<offsetHours id="5">0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 12.0</offsetHours>
<offsetHours id="8">0.0 1.0 2.0 3.0</offsetHours>

<runSequence>
  <run runHour="0.0" offsetHourSeq="5"/>
  <run runHour="1.0" offsetHourSeq="8"/>
  <run runHour="2.0" offsetHourSeq="8"/>
  <run runHour="3.0" offsetHourSeq="5"/>

  <variable name="Pressure_vertical_velocity" vertCoord="1">
    <vertTimeCoord restrict="850.0 700.0 500.0 300.0">2.0
    6.0</vertTimeCoord>
    <vertTimeCoord restrict="500.0">12.0</vertTimeCoord>
  </variable>
</runSequence>
------------------------------------------------------------------------------

This says that for the *Pressure_vertical_velocity* variable, the 2.0
and 6.0 offset hours are only output on the 850.0, 700.0, 500.0 and
300.0 vertical levels, while the 12.0 forecast hour only appears on the
500.0 level.

=== FmrcInventory

A _*FmrcInventory*_ is a collection of **ForecastModelRunInventory**,
along with an **FmrcDefinition**. This allows you to tell what inventory
is missing.

This method will scan a directory, create *ForecastModelRunInventory*
objects for each file, find the *FmrcDefinition,* and create the
resulting *FmrcInventory:*

---------------------------------------------------------------------------------------
  /**
   * Create a ForecastModelRun Collection from the files in a directory.
   * @param fmrcDefinitionPath put/look for fmrc definition files in this directory
   * @param collectionName name of collection
   * @param fmr_cache cache fmr inventory files here
   * @param dirName  scan this directory
   * @param suffix filter on this suffix
   * @param mode one of the ForecastModelRun.OPEN_ modes
   * @return ForecastModelRunCollection or null if no files exist
   * @throws Exception
   */
  public static FmrcInventory make(String fmrcDefinitionPath, String collectionName,
          ucar.nc2.util.DiskCache2 fmr_cache, String dirName, String suffix, int mode);
---------------------------------------------------------------------------------------

Once you have constructed, you can create an
_*forecastModelRunCollectionInventory*_ XML document that summarize the
inventory:

 

'''''

== 2. CDM / NcML

=== ucar.nc2.dt.Grid

------------------------------------------------
public interface GridCoordSystem {
   public String getName();
   public List getDomain();

   // axes
   public boolean isProductSet(); // all are 1D
   public List getCoordinateAxes();
   public CoordinateAxis getXHorizAxis();
   public CoordinateAxis getYHorizAxis();
   public CoordinateAxis1D getVerticalAxis();
   public CoordinateAxis getTimeAxis();
   public CoordinateAxis1D getEnsembleAxis();
   public CoordinateAxis1DTime getRunTimeAxis();
------------------------------------------------

--------------------------------------------------------------------------------
   // transforms
   public List getCoordinateTransforms();
   public ProjectionCT getProjectionCT();
   public ucar.unidata.geoloc.ProjectionImpl getProjection();
   public VerticalCT getVerticalCT();
   public ucar.unidata.geoloc.vertical.VerticalTransform getVerticalTransform();
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------------
   // horiz
   public boolean isLatLon();              // else has a Projection
   public boolean isRegularSpatial();      // x,y are 1D and regularly spaced
   public ucar.unidata.geoloc.LatLonRect getLatLonBoundingBox();
   public ucar.unidata.geoloc.ProjectionRect getBoundingBox();
   public java.util.List getRangesFromLatLonRect(ucar.unidata.geoloc.LatLonRect llbb);
   public int[] findXYindexFromCoord(double x_coord, double y_coord, int[] result);
--------------------------------------------------------------------------------------

--------------------------------
   // vertical
   public boolean isZPositive();
--------------------------------

----------------------------------------------------------------
   // time
   public thredds.datatype.DateRange getDateRange();
   public boolean hasTimeAxis();
   public boolean hasTimeAxis1D();
   public CoordinateAxis1DTime getTimeAxis1D();
   public CoordinateAxis1DTime getTimeAxisForRun(int run_index);
}
----------------------------------------------------------------

=== NcML Aggregation

*A forecastModelRunCollection* aggregation is similar to a *JoinNew* in
that each file defines one slice in a synthetic dimension:

-----------------------------------------------------------------------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2">
  <aggregation dimName="run" type="forecastModelRunCollection">
    <scan location="C:/data/grib/nam/c20s/" suffix=".grib1" enhance="true" dateFormatMark="NAM_CONUS_20km_surface_#yyyyMMdd_HHmm"/>
  </aggregation>
</netcdf>
-----------------------------------------------------------------------------------------------------------------------------------

The synthesized runtime coordinate:

------------------------------------------------------------
   String run(run=7);
     :long_name = "Run time for ForecastModelRunCollection";
     :_CoordinateAxisType = "RunTime";
------------------------------------------------------------

is constructed in several ways. The *dateFormatMark* attribute can be
used when the time is encoded in the filename in a uniform way.

When you explicitly list the datasets, you can add a coordinate value.

-------------------------------------------------------------
<aggregation dimName="run" type="forecastModelRunCollection">
  <netcdf location="/my/data/modelrun01.nc" coordValue="0"/>
  <netcdf location="/my/data/modelrun02.nc" coordValue="1"/>
  <netcdf location="/my/data/modelrun03.nc" coordValue="2"/>
</aggregation>
-------------------------------------------------------------

*A forecastModelRunCollection* aggregation creates a NetcdfDataset,
which can wrapped in a GridDataset to create variables with 2 time
dimensions:

-------------------------------------------------------------------
  float varname( runTime, forecastTime, z_coord, y_coord, x_coord);
-------------------------------------------------------------------

We thus need a two dimensional time variable:

-----------------------------------------------
  float forecastTime( runTime, forecastTime);
    :long_name = "forecast time";
    :units = "hour since 2006-03-17T00:00:00Z";
    :_CoordinateAxisType = "Time";
-----------------------------------------------

*Case 1.*

Assume the time units are all the same in the nested datasets. this is
the case for __aggFmrcNetcdf.xml__, that works on the files in
_*C:/data/ncmodels/*_ :

-------------------------------------
   double valtime(run=14, record=11);
     :long_name = "valid time";
     :units = "hours since 1992-1-1";
     :_CoordinateAxisType = "Time";
-------------------------------------

------
 data:
------

------------------------------------------------------------------------------------------------------------------
 {
   {122100.0, 122106.0, 122112.0, 122118.0, 122124.0, 122130.0, 122136.0, 122142.0, 122148.0, 122154.0, 122160.0},
   {122112.0, 122118.0, 122124.0, 122130.0, 122136.0, 122142.0, 122148.0, 122154.0, 122160.0, 122166.0, 122172.0},
   {122124.0, 122130.0, 122136.0, 122142.0, 122148.0, 122154.0, 122160.0, 122166.0, 122172.0, 122178.0, 122184.0},
   {122136.0, 122142.0, 122148.0, 122154.0, 122160.0, 122166.0, 122172.0, 122178.0, 122184.0, 122190.0, 122196.0},
   {122148.0, 122154.0, 122160.0, 122166.0, 122172.0, 122178.0, 122184.0, 122190.0, 122196.0, 122202.0, 122208.0},
   {122160.0, 122166.0, 122172.0, 122178.0, 122184.0, 122190.0, 122196.0, 122202.0, 122208.0, 122214.0, 122220.0},
   {122172.0, 122178.0, 122184.0, 122190.0, 122196.0, 122202.0, 122208.0, 122214.0, 122220.0, 122226.0, 122232.0},
   {122184.0, 122190.0, 122196.0, 122202.0, 122208.0, 122214.0, 122220.0, 122226.0, 122232.0, 122238.0, 122244.0},
   {122196.0, 122202.0, 122208.0, 122214.0, 122220.0, 122226.0, 122232.0, 122238.0, 122244.0, 122250.0, 122256.0},
   {122208.0, 122214.0, 122220.0, 122226.0, 122232.0, 122238.0, 122244.0, 122250.0, 122256.0, 122262.0, 122268.0},
   {122220.0, 122226.0, 122232.0, 122238.0, 122244.0, 122250.0, 122256.0, 122262.0, 122268.0, 122274.0, 122280.0},
   {122232.0, 122238.0, 122244.0, 122250.0, 122256.0, 122262.0, 122268.0, 122274.0, 122280.0, 122286.0, 122292.0},
   {122244.0, 122250.0, 122256.0, 122262.0, 122268.0, 122274.0, 122280.0, 122286.0, 122292.0, 122298.0, 122304.0},
   {122256.0, 122262.0, 122268.0, 122274.0, 122280.0, 122286.0, 122292.0, 122298.0, 122304.0, 122310.0, 122316.0}
 }
------------------------------------------------------------------------------------------------------------------

*Case 2.*

The time units differ for the nested datasets. This is the case for
__aggFmrcGrib.xml__, that works on the files in
_*C:/data/grib/nam/c20s/*_ . So we have to adjust the values.

------------------------------------------------
   int time(run=7, time=29);
     :long_name = "forecast time";
     :units = "hour since 2006-03-15T12:00:00Z";
     :_CoordinateAxisType = "Time";
------------------------------------------------

------
 data:
------

------------------------------------------------------------------------------------------------------------------------------
 {
   {0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84},
   {6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90},
   {12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96},
   {18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99, 102},
   {24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99, 102, 105, 108},
   {30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99, 102, 105, 108, 111, 114},
   {36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99, 102, 105, 108, 111, 114, 117, 120}
 }
------------------------------------------------------------------------------------------------------------------------------

Indicate that the time coordinate units change, with the
*timeUnitsChange* attribute :

-----------------------------------------------------------------------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2">
  <aggregation dimName="run" type="forecastModelRunCollection" timeUnitsChange="true">
    <scan location="C:/data/grib/nam/c20s/" suffix=".grib1" enhance="true" dateFormatMark="NAM_CONUS_20km_surface_#yyyyMMdd_HHmm"/>
  </aggregation>
</netcdf>

-----------------------------------------------------------------------------------------------------------------------------------

=== Persistence

Type.JOIN_EXISTING will write an aggegation XML document to diskCache2
().

String cache2 = ServletParams.getInitParameter(``CacheAged'',
contentPath + ``cacheAged/''); = ``/data/tmp/thredds/cacheAged/''

'''''

== 3. Formica Project

An FMRC can be thought of as a collection of grids (aka fields or
parameters or variables) with 2 or 3 spatial dimensions and 2 time
dimensions. We will provide subsets of the FMRC by selecting a 1D subset
of the 2D times:

1.  **Forecast Model Run Dataset**: all forecast times for a single run
time. (horizontal row). **Time dimension = forecast times**.
2.  **Constant Forecast Date Dataset**: all run times for a single
forecast date, i.e. successively shorter forecasts of the same endpoint.
(diagonal). **Time dimension = run times**.
3.  **Constant Forecast Offset Dataset**: contain the grids with the
same forecast time offset, e.g. all the 3 hour forecasts in the
collection (vertical column) **Time dimension = forecast times**.
Auxilary coordinate= **run times**.
4.  **Best time series dataset**: contains the first time step in each
of the runs, plus all of the time steps in the most recent run.(first
vertical column plus the top row). **Time dimension = forecast times**.
Auxilary coordinate= **run times**.

If there are N Forecast Model Runs (FMR) files in a collection, and each
FMR contains M forecast dates, then there are M constant offset datasets
and N+M constant forecast date datasets. By integrating virtual datasets
directly into the TDS, we can automatically generate these N + 2M new
datasets in a THREDDS catalog and provide OPeNDAP (and possibly WCS)
URLs through which the virtual datasets can be accessed. The N original
FMR files can be explicitly named in the TDS configuration catalog, or
if the files are all contained under a single directory, the directory
can be automatically scanned to determine the files.

=== Uniform Forecast Hours

NAM 80 km

Number of 2D records present (or) Number present / Number expected.

Valid Time offset (hours)

Run Time

Total

0.0

6.0

12.0

18.0

24.0

30.0

36.0

42.0

48.0

54.0

60.0

2006-07-14 12.00Z

1847

167

168

168

168

168

168

168

168

168

168

168

2006-07-14 00.00Z

1847

167

168

168

168

168

168

168

168

168

168

168

2006-07-13 12.00Z

1847

167

168

168

168

168

168

168

168

168

168

168

2006-07-13 00.00Z

1847

167

168

168

168

168

168

168

168

168

168

168

2006-07-12 12.00Z

1847

167

168

168

168

168

168

168

168

168

168

168

2006-07-12 00.00Z

1847

167

168

168

168

168

168

168

168

168

168

168

2006-07-11 12.00Z

1847

167

168

168

168

168

168

168

168

168

168

168

2006-07-11 00.00Z

1847

167

168

168

168

168

168

168

168

168

168

168

2006-07-10 12.00Z

1847

167

168

168

168

168

168

168

168

168

168

168

2006-07-10 00.00Z

1847

167

168

168

168

168

168

168

168

168

168

168

2006-07-09 12.00Z

1847

167

168

168

168

168

168

168

168

168

168

168

2006-07-09 00.00Z

1847

167

168

168

168

168

168

168

168

168

168

168

2006-07-08 12.00Z

1847

167

168

168

168

168

168

168

168

168

168

168

2006-07-08 00.00Z

1847

167

168

168

168

168

168

168

168

168

168

168

2006-07-07 12.00Z

1847

167

168

168

168

168

168

168

168

168

168

168

 

=== Non Uniform Forecast Hours

RUC hourly model:

Number of 2D records present (or) Number present / Number expected.

Valid Time offset (hours)

Run Time

Total

0.0

1.0

2.0

3.0

4.0

5.0

6.0

7.0

8.0

9.0

12.0

2006-07-14 15.00Z

149/1358

149

*0/142*

*0/141*

*0/149*

*0/141*

*0/141*

*0/147*

*0/25*

*0/27*

*0/148*

*0/148*

2006-07-14 14.00Z

606

149

150

149

158

2006-07-14 13.00Z

606

149

150

149

158

2006-07-14 12.00Z

1438

149

150

149

158

149

149

156

31

33

157

157

2006-07-14 11.00Z

606

149

150

149

158

2006-07-14 10.00Z

606

149

150

149

158

2006-07-14 09.00Z

1438

149

150

149

158

149

149

156

31

33

157

157

2006-07-14 08.00Z

606

149

150

149

158

2006-07-14 07.00Z

606

149

150

149

158

2006-07-14 06.00Z

1438

149

150

149

158

149

149

156

31

33

157

157

2006-07-14 05.00Z

606

149

150

149

158

2006-07-14 04.00Z

149/581

149

*0/142*

*0/141*

*0/149*

2006-07-14 03.00Z

1438

149

150

149

158

149

149

156

31

33

157

157

1.  The first row is partially complete (missing grids in red) because
its currently being written.
2.  The 0,3 etc runs go out to 12 hours, the rest go out to3 hours
3.  Different numbers across indicate that different variables have
different forecast hour patterns.
4.  The red columns in the next to bottom row indicate data that was
never recieved for one reason or another.

 

=== TDS Configuration

Add a new element, somewhat like **datasetScan**:

-------------------------------------------------------------------------------------------------------------------------------
<datasetFmrc path="models/GFS/Alaska_191km" name="GFS Alaska 191km Model" serviceName="myserver" >

 <netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2">
   <aggregation dimName="run" type="forecastModelRunCollection">
     <scan location="/data/ldm/grib/gfs/Alaska_191km/" suffix=".grib1" dateFormatMark="NAM_CONUS_20km_surface_#yyyyMMdd_HHmm"/>
   </aggregation>
 </netcdf>

</datasetFmrc>
-------------------------------------------------------------------------------------------------------------------------------

Generates the following catalog:

---------------------------------------------------------------------------------------------------------------------------------------------
<dataset ID="models/GFS/Alaska_191km" name="GFS Alaska 191km Model" serviceName="myserver" >

 <dataset name="Forecast Model Run Datasets" ID="models/GFS/Alaska_191km/runs">
   <dataset name="GFS Alaska 191km Model run 2006-07-12 18:00" urlPath="models/GFS/Alaska_191km/runs/GFS_Alaska_191km_20060712_1800.grib1">
   <dataset name="GFS Alaska 191km Model run 2006-07-12 15:00" urlPath="models/GFS/Alaska_191km/runs/GFS_Alaska_191km_20060712_1500.grib1">
   <dataset name="GFS Alaska 191km Model run 2006-07-12 12:00" urlPath="models/GFS/Alaska_191km/runs/GFS_Alaska_191km_20060712_1200.grib1">
   ...

 <dataset>

 <dataset name="Constant Forecast Date Datasets" ID="models/GFS/Alaska_191km/forecast">
   <dataset name="GFS Alaska 191km Model constant forecast date 2006-07-12 18:00"  urlPath="models/GFS/Alaska_191km/forecast/20060712_1800">
   <dataset name="GFS Alaska 191km Model constant forecast date 2006-07-12 17:00"  urlPath="models/GFS/Alaska_191km/forecast/20060712_1700">
   <dataset name="GFS Alaska 191km Model constant forecast date 2006-07-12 16:00"  urlPath="models/GFS/Alaska_191km/forecast/20060712_1600">
   ...

 <dataset>

 <dataset name="Constant Forecast Offset Datasets" ID="models/GFS/Alaska_191km/offset">
   <dataset name="GFS Alaska 191km Model constant forecast offset 0 hours"  urlPath="models/GFS/Alaska_191km/offset/0_hour">
   <dataset name="GFS Alaska 191km Model constant forecast offset 3 hours"  urlPath="models/GFS/Alaska_191km/offset/3_hour">
   <dataset name="GFS Alaska 191km Model constant forecast offset 6 hours"  urlPath="models/GFS/Alaska_191km/offset/6_hour">
   ...

 <dataset>

 <dataset name="Best Time Series Dataset" ID="models/GFS/Alaska_191km/best" urlPath="models/GFS/Alaska_191km/best" />

</dataset>
---------------------------------------------------------------------------------------------------------------------------------------------

Doesnt have to be an aggregation, but it does have to be an NcML
dataset:

---------------------------------------------------------------------------------------------------------------
<datasetFmrc path="models/ECMWF/cnmr" name="ECMWF cnmr Model" serviceName="myserver" >
  <netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2" location="C:/data/MM_cnrm_129_red.nc">
</datasetFmrc>
---------------------------------------------------------------------------------------------------------------

Has to be a dataset with two time axes, forecast and run time. We have
to write an adapter that takes such a dataset and creates a
ForecastModelRunCollection.

Because of the complication of missing data in the GRIB Collections,
that should probably be a seperate implementation.
