:source-highlighter: coderay
[[threddsDocs]]


Logical View
============

== 4. Subset a variable’s data

In the example below, we use _*logicalView*_ elements to define new
variables (__T-FHAG, T-MandatoryLevels,__ and __T-BoundaryLayers__)
whose data are subsets of an existing variable (named _*t*_ in the
file). We do this because the original file has 3 vertical coordinates
munged together in the levels_25 dimension, and we want to break that
into 3 separate variables.

The logicalView element currently has only one attribute _*section*_
whose value defines the data section, according to these rules:

* to select all of a dimension, use as asterisk (*)
* to select one slice, just use the value of the index
* to select a range, use start:end, eg 1:19

---------------------------------------------------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<netcdf xmlns="http://www.ucar.edu/schemas/netcdf"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.ucar.edu/schemas/netcdf http://www.unidata.ucar.edu/schemas/netcdfDataset2.xsd"
    uri="file:///C:/data/conventions/awips/awipsTestFilename.nc">
---------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------
 <dimension name="record" length="11" isUnlimited="true"/>
 <dimension name="x" length="93"/>
 <dimension name="y" length="65"/>
 <dimension name="levels_25" length="25"/>
 <dimension name="FHAG" length="1"/>
 <dimension name="MandatoryLevels" length="19"/>
 <dimension name="BoundaryLayers" length="5"/>

 <variable name="T-FHAG" shape="record FHAG y x" type="float"    nameInFile="t">
   <attribute name="long_name" type="string" value="Temperature    at fixed height above ground"/>
   <attribute name="units" type="string" value="K"/>
   <attribute name="valid_range" type="float" value="180.0    330.0"/>
   <attribute name="_FillValue" type="float" value="-99999.0"/>
   <logicalView section="*,0,*,*" />
 </variable>

 <variable name="T-MandatoryLevels" shape="record MandatoryLevels    y x" type="float" nameInFile="t">
   <attribute name="long_name" type="string" value="Temperature    on Mandatory Levels"/>
   <attribute name="units" type="string" value="K"/>
   <attribute name="valid_range" type="float" value="180.0    330.0"/>
   <attribute name="_FillValue" type="float" value="-99999.0"/>
   <logicalView section="*,1:19,*,*" />
 </variable>

 <variable name="T-BoundaryLayers" shape="record BoundaryLayers    y x" type="float" nameInFile="t">
   <attribute name="long_name" type="string" value="Temperature    on BoundaryLayers"/>
   <attribute name="units" type="string" value="K"/>
   <attribute name="valid_range" type="float" value="180.0    330.0"/>
   <attribute name="_FillValue" type="float" value="-99999.0"/>
   <logicalView section="*,20:24,*,*" />
 </variable>

 <variable name="t" shape="record levels_25 y x" type="float">
   <attribute name="long_name" type="string" value="Temperature"/>
   <attribute name="units" type="string" value="K"/>
   <attribute name="valid_range" type="float" value="180.0    330.0"/>
   <attribute name="_FillValue" type="float" value="-99999.0"/>
 </variable>

 <variable name="FHAG" type="float" shape="FHAG">
   <attribute name="long_name" type="string" value="fixed height above ground"/>
   <attribute name="units" type="string" value="m"/>
   <attribute name="positive" type="string" value="up"/>
   <values>2.0</values>
 </variable>

 <variable name='MandatoryLevels' type="int" shape="MandatoryLevels">
   <attribute name="units" type="string" value="hPa"    />
   <attribute name="long_name" type="string" value="Pressure    Levels" />
   <values>1000 950 900 850 800 750 700 650 600 550 500 450 400 350 300 250    200 150 100</values>
 </variable>

 <variable name="BoundaryLayers" shape="BoundaryLayers"    type="double">
   <attribute name="units" type="string" value="hPa"    />
   <attribute name="long_name" type="string" value="BoundaryLayer    hectoPascals above ground" />
   <values start="0.0" increment="30.0" npts="5"    />
  </variable >

</netcdf>

------------------------------------------------------------------------------------------------------

NB: This example is taken from the infamous AWIPS formatted netCDF
files, and is a good example of using the logicalView element. If you
have to work with AWIPS files, the dataset convention parsing code will
do all the hard work, so you do not need to use NcML to break up the
variables yourself.
