:source-highlighter: coderay
[[threddsDocs]]


= Data Reading

== Data Reading Control Flow

last updated Mar 2010, on version 4.2.

'''''

=== NetcdfFile

All reading is channelled through:

-----------------------------------------------------------------------------------------------------------
 protected Array readData(ucar.nc2.Variable v, Section ranges) throws IOException, InvalidRangeException  {
   Array result = spi.readData(v, ranges);
   result.setUnsigned(v.isUnsigned());
   return result;
 }
-----------------------------------------------------------------------------------------------------------

With these exceptions:

* this is for reading variables that are members of structures

----------------------------------------------------------------------------------------------
  public Array readSection(String variableSection) throws IOException, InvalidRangeException {
   ParsedSectionSpec cer = ParsedSectionSpec.parseVariableSection(this, variableSection);
   if (cer.child == null) {
     Array result = cer.v.read(cer.section);
     result.setUnsigned(cer.v.isUnsigned());
     return result;
   }

   if (spi == null)
     return IospHelper.readSection(cer);
   else
     // allow iosp to optimize
     return spi.readSection(cer);
   }

----------------------------------------------------------------------------------------------

* experimental version to try to use direct transfer I/O (read directly
from file to socket)

--------------------------------------------------------------------------------------------------
 protected long readToByteChannel(ucar.nc2.Variable v, Section section, WritableByteChannel wbc) {
   if ((spi == null) || v.hasCachedData())
     return IospHelper.copyToByteChannel(v.read(section), wbc);
   else
     return spi.readToByteChannel(v, section, wbc);
   }

--------------------------------------------------------------------------------------------------

These seem to break the normal Variable chain, so probably cant be used
generally.

===  +
 Variable

all reading is channelled through: +

--------------------------------------------------------------------------------------
 protected Array _read() throws IOException {
    // caching overrides the proxyReader
    // check if already cached
    if (cache != null && cache.data != null) {
      if (debugCaching) System.out.println("got data from cache " + getName());
      return cache.data.copy();
    }

    Array data = proxyReader.reallyRead(this, null);

    // optionally cache it
    if (isCaching()) {
      setCachedData(data);
      if (debugCaching) System.out.println("cache " + getName());
      return cache.data.copy(); // dont let users get their nasty hands on cached data
    } else {
      return data;
    }
 }
--------------------------------------------------------------------------------------

Note that caching is checked before the ProxyReader is called. By
default, a Variable is its own ProxyReader:

------------------------------------------------------------------------------------
protected ProxyReader proxyReader = this;


public Array reallyRead(Variable client, CancelTask cancelTask) throws IOException {
  try {
    return ncfile.readData(this, getShapeAsSection());
  } catch (InvalidRangeException e) {
    e.printStackTrace();
    throw new IOException(e.getMessage()); // cant happen haha
  }
}
------------------------------------------------------------------------------------

So the call is eventually sent to **ncfile.readData**(). So Variable
must be part of ncfile, ie known by the spi. ncfile is thus the data
source for a Variable, not _necessarily_ the same as the logical
container.

=== ProxyReader

Canonical use of ProxyReader is to create logical subsets, eg
**slice**() and **section**(). Example:

---------------------------------------------------------------------
  public Variable slice(int dim, int value) {
    ...
    // create a copy of this variable with a proxy reader
    Variable sliceV = copy(); // subclasses must override
    Section slice = new Section( getShapeAsSection());
    slice.replaceRange(dim, new Range(value, value)).makeImmutable();
    sliceV.setProxyReader( new SliceReader(this, dim, slice));
    sliceV.createNewCache(); // dont share the cache
    sliceV.setCaching(false); // dont cache
  }
---------------------------------------------------------------------

Note we are creating a new Variable and setting its proxyReader, not
replacing the proxyReader on an existing Variable.

--------------------------------------------------------------------------------------
class SliceReader implements ProxyReader {

  ...
  public Array reallyRead(Variable client, CancelTask cancelTask) throws IOException {
    Array data;
    try {
      data = client._read( slice);
    } catch (InvalidRangeException e) {
      log.error("InvalidRangeException in slice, var="+ client);
      throw new IllegalStateException(e.getMessage());
    }
    data = data.reduce( sliceDim);
    return data;
  }
}
--------------------------------------------------------------------------------------

=== VariableDS

The usual way to wrap a Variable by a VariableDS (used by NcML,
NetcdfDataset(NetcdfFile ncfile)) :

--------------------------------------------------------------

public VariableDS(Group g, Variable orgVar, boolean enhance) {
  super(orgVar);
  if (g != null) this.group = g;
  setDimensions( getDimensionsString());

   // dont share cache, iosp : all IO is delegated
  this.ncfile = null;
  this.spiObject = null;
  createNewCache();

  this.orgVar = orgVar;
  this.orgDataType = orgVar.getDataType();

  if (orgVar instanceof VariableDS) {
     VariableDS ncVarDS = (VariableDS) orgVar;
     this.enhanceProxy = ncVarDS.enhanceProxy;
     this.scaleMissingProxy = ncVarDS.scaleMissingProxy;
     this.enhanceMode = ncVarDS.enhanceMode;
  } else {
     this.enhanceProxy = new EnhancementsImpl( this);
     if (enhance) {
       enhance(NetcdfDataset.getDefaultEnhanceMode());
     } else {
       this.scaleMissingProxy = new EnhanceScaleMissingImpl();
     }
  }
}
--------------------------------------------------------------

VariableDS overrrides Variable._read(), so that it can enhance if
needed. If proxyReader already does enhancement, you must be sure not to
trigger it again (eg remove scale/offset attributes).

---------------------------------------------------------------------
protected Array _read() throws IOException {
  Array result;
  if (hasCachedData())
    result = super._read(); // cache only raw data, so not twice room
  else
    result = proxyReader.reallyRead(this, null);

  // LOOK not caching
  if (needScaleOffsetMissing)
    return convertScaleOffsetMissing(result);
  else if (needEnumConversion)
    return convertEnums(result);
  else
    return result;
 }

---------------------------------------------------------------------

The super(orgVar) constructor does not copy the proxyReader from orgVar.
So VariableDS is by default also its own ProxyReader:

------------------------------------------------------------------------------------
public Array reallyRead(Variable client, CancelTask cancelTask) throws IOException {
   if (orgVar == null)
     return getMissingDataArray(shape);
   return orgVar.read();
}
------------------------------------------------------------------------------------

A VariableDS either

1.  has self contained data array (cached data)
2.  has a ProxyReader set
3.  wraps another Variable (orgVar != null)
4.  returns missing values, or default fill values if no data is set

When wrapping, eg CoordinateAxis, use the orgVar mechanism:

--------------------------------------------------------------------------------
protected VariableDS( VariableDS vds) {
  super(vds);
  // how to read ??
  this.orgVar = vds;


  this.orgDataType = vds.orgDataType;
  this.orgName = vds.orgName;


  this.scaleMissingProxy = vds.scaleMissingProxy;
  this.enhanceProxy = new EnhancementsImpl( this); //decouple coordinate systems

  // LOOK not sure of this
  this.enhanceMode = vds.enhanceMode;
  this.needScaleOffsetMissing = vds.needScaleOffsetMissing;
  this.needEnumConversion = vds.needEnumConversion;
}
--------------------------------------------------------------------------------

=== FmrcDataset

Aggregation datasets create synthetic VariableDS and set a ProxyReader
to handle the data reading.
