:source-highlighter: coderay
[[threddsDocs]]

= GRIB IOSP notes

== Use Cases

. client
.. single data file mode
.. collection index mode
. server with small, static collections S
.. <update startup=``nocheck'' trigger=``allow''/> from tds, must have write permission, no rescan needed.
.. if no update, will be created when first accessed
. server with small, dynamic collections; lazy updating
.. <collection recheckEvery=``time''/>
. server with small, dynamic collections; active updating in background tds task
.. <update startup=``true'' rescan=``0 0/5 * * * ? *''
trigger=``allow''/> from tds, must have write permission
. server with small, dynamic collections; active updating in background tdm task
.. <tdm startup=``true'' rescan=``0 0/5 * * * ? *'' trigger=``allow''/> from separate tdm process
.. if tdm hasn't run, tds will create grib collection index if possible
. server with large, dynamic collections
.. use timePartition. This builds global ncx from time partitioned ncx, for performance.

== Notes

* You must put in **<dataFormat>GRIB-1</dataFormat>**, otherwise GRIB-2 is assumed
* olderThan=``5 min'' now excludes files only if they are not already in the collection. OTOH is this needed anymore? Rectilyze should prevent fragmented coordinates.
* Don't mix recheck with update/tdm. recheck means when a dataset is accessed, scan if this much time has elapsed since the last scan. so its synchronous, wheras update is asynch.
* trigger from user means go scan collection
* trigger from tdm means index is created, but rebuild gc object from it. maybe thats fast enough that you can do it when next request comes in. but other fc (point, fmrc) may be different ??

== Single Data File Mode

Pass the data file location to the IOSP. Assumes its a File (ie not remote, etc). Call *GribIndex.makeCollection()*

. Check for grib index (**gbx9**).
.. If exists, check last modified against data file.
.. Read grib index. *GribIndex.readIndex().*
.. (Re)write if needed. *GribIndex.makeIndex().*
.. Not using DiskCache
. Check for collection index (**ncx**).
*GribCollectionBuilder.createFromSingleFile().*
.. If exists, check last modified against data file.
.. Read collection index. *GribCollectionBuilder.readIndex().*
.. (Re)write if needed. *GribCollectionBuilder.createIndex()*
.. Not using DiskCache

== Collection Index Mode

Pass the *ncx* file to the IOSP. In this case, the collection is created from reading the ncx file with no checking against the original data file(s).

You can create an *ncx* file based on a collection spec in: Tools UI: IOSP/GRIB1(2)/GribCollection. Enter the collection spec and hit Enter. To write the index file, hit the ``Write Index'' button on the right. Give it a memorable name and hit Save.

== FeatureCollection Mode

. At TDS startup, only the configuration info is read and stored. No scanning or object building, etc.
. if *recheckEvery* is defined on the collection
.. on every request, test to see if *recheckEvery* time has passed since last checked - InvDatasetFcGrib.checkState()
.. if so, rescan and recreate if needed
. If *<update>* is defined
.. then a task is added to the CollectionUpdater, to be run in the background.
.. task call CollectionManager.scan().
.. if scan() finds a change, InvDatasetFcGrib.update() is called, which recreates the collection.
. If *<tdm>* is defined
.. then a task is added to the CollectionUpdater, to be run in the background.
.. task call CollectionManager.scan().
.. if scan() finds a change, InvDatasetFcGrib.update() is called, which recreates the collection.

== Indexing

Rule of thumb is ~ 500 bytes / GRIB record. (check with GRIB1). So a collection of 7M records cost 3.5 Gb. If TdmRunner has 4 threads, can get OOM error. Solution is probably to use time partitions.

== Time partitions

It appears that all the partitions are open at once, rather than opening and closing as needed. each partition is a grib collection with an open ncx RAF.

Leave top collections open, but manage time partitions in a cache.

Time partition indexes have to be deleted by hand when the underlying indexes need updating.

ncx indices need to be deleted by hand if you want to modify them with gribConfig or code changes, unless I update the version. partition by day reads all file in, then divides them up by date.

Partition by directory looks at each directory seperately, not all files at once.

== Memory use

Top level gc are kept in memory. 68 total 42 M, avg = 600K.

== NcML

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2" location="E:/ncep/NDFD_CONUS_5km_conduit_20120119_1800.grib2">
 <iospParam>
   <gdsHash from="-2121584860" to="28944332"/>
 </iospParam>
</netcdf>

NAM_CONUS_12km_conduit:
 <iospParam>
    <intvFilter excludeZero="true"/>
   <intvFilter intvLength="3">
     <variable id="0-1-8"/>
     <variable id="0-1-10"/>
   </intvFilter>
 </iospParam>
----

'''''

== Problems in 4.2

. IDD pqact was wrong on

[source,bash]
----
Q:\cdmUnitTest\tds\new\NAM_CONUS_20km_selectsurface_20100426_1800.grib2

Q:\cdmUnitTest\tds\new\NAM_CONUS_40km_conduit_20100506_1800.grib2
----

. GridVertCoord.useVertcoord = true incorrectly exclude records for
variables with n > 1 records.

. Statistic (eg Average, Accumunulation) was ignored.

When same parameter had both, only one variable was created (eg
/testdata:/cdmUnitTest/rtmodels/06091200_nmm_alt1.GrbF02800):

----
 float Convective_cloud_cover(time, y, x);
----

should be

----
 float Convective_cloud_cover(time, y, x);
 float Convective_cloud_cover_Average(time1, y, x);
----

. Interval Time coordinates were ignored*

When same parameter had both, only one variable was created, with
arbitrary mixture.

. Confusion of local and WMO tables

systemic, eg code table 4.5 200 hard coded with NCEP : see Grib2Tables.codeTable4_5()

. Confusion of GRIB1 and GRIB2

eg using time range id as product template, see:

[source,java]
----
 Grib1PDS.getProductDefinitionTemplate() {  return getTimeRange(); }
----

== Time Interval Coordinates

=== Case 1: even intervals

Q:\cdmUnitTest\tds\new\NAM_CONUS_12km_20100520_0000.grib2

----
 float Probability_of_frozen_Precipitation(time1=28, y=428, x=614);
 :long_name = "Probability_of_frozen_Precipitation (Accumulation for 3 hour Intervals) @ surface";
 :cell_methods = "time1: sum";
 :units = "percent";
 :missing_value = NaNf; // float
 :grid_mapping = "Lambert_Conformal";
 :GRIB_param_discipline = "Hydrological_products";
 :GRIB_param_category = "Hydrology_probabilities";
 :GRIB_param_name = "Probability_of_frozen_precipitation";
 :GRIB_param_id = 2, 1, 1, 193; // int
 :GRIB_product_definition_type = "Average, accumulation, extreme values or other statistically processed value at a horizontal level in a time interval";
 :GRIB_product_definition_template = 8; // int
 :GRIB_level_type = 1; // int
 :GRIB_VectorComponentFlag = "gridRelative";
----

Run accum algorithm from IOSP/GRIB2:

all: (28) 0-3 3-6 6-9 9-12 12-15 15-18 18-21 21-24 24-27 27-30 30-33
33-36 36-39 39-42 42-45 45-48 48-51 51-54 54-57 57-60 60-63 63-66 66-69
69-72 72-75 75-78 78-81 81-84 Interval=3

Time coordinate
----
 int time1(time1=28);
 :long_name = "time for 3hour intervals";
 :units = "hour since 2010-05-20T00:00:00Z";
 :bounds = "time1_bounds";
 :GRIB_orgReferenceTime = "2010-05-20T00:00:00Z";
 :GRIB2_significanceOfRTName = "Start of forecast";
 :_CoordinateAxisType = "Time";
----

time1 = +
{3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84}

edges= 0.0 3.0 6.0 9.0 12.0 15.0 18.0 21.0 24.0 27.0 30.0 33.0 36.0 39.0
42.0 45.0 48.0 51.0 54.0 57.0 60.0 63.0 66.0 69.0 72.0 75.0 78.0 81.0
84.0

----
 int time1_bounds(time1=28, ncell=2);
 :long_name = "3hour intervals";
 :units = "hour since 2010-05-20T00:00:00Z";
----

data:

----
{
  {0, 3},
  {3, 6},
  {6, 9},
  {9, 12},
  {12, 15},
  {15, 18},
  {18, 21},
  {21, 24},
  {24, 27},
  {27, 30},
  {30, 33},
  {33, 36},
  {36, 39},
  {39, 42},
  {42, 45},
  {45, 48},
  {48, 51},
  {51, 54},
  {54, 57},
  {57, 60},
  {60, 63},
  {63, 66},
  {66, 69},
  {69, 72},
  {72, 75},
  {75, 78},
  {78, 81},
  {81, 84}
}
----

=== Case 2: mixed intervals, unique endpoints, two coordinates with same endpoints and different intervals

Accumulation variables have different intervals than Average variables,
both time coordinate have the same set of values.

Q:\cdmUnitTest\tds\new\NAM_Polar_90km_20100525_1200.grib2

----
 float Evaporation(time1=28, y=110, x=147);
 :long_name = "Evaporation (Accumulation for 3 hour Intervals) @ surface";
 :cell_methods = "time1: sum";
 :units = "kg m-2";
----

all: (28) 0-3 0-6 0-9 0-12 12-15 12-18 12-21 12-24 24-27 24-30 24-33
24-36 36-39 36-42 36-45 36-48 48-51 48-54 48-57 48-60 60-63 60-66 60-69
60-72 72-75 72-78 72-81 72-84 Mixed

----
  int time1(time1=28);
     :long_name = "forecast time for (mixed intervals)";
     :units = "hour since 2010-05-25T12:00:00Z";
     :bounds = "time1_bounds";
     :GRIB_orgReferenceTime = "2010-05-25T12:00:00Z";
     :GRIB2_significanceOfRTName = "Start of forecast";
     :_CoordinateAxisType = "Time";
----

time1 = +
  {3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54,
57, 60, 63, 66, 69, 72, 75, 78, 81, 84}

bound1= 0.0 0.0 0.0 0.0 12.0 12.0 12.0 12.0 24.0 24.0 24.0 24.0 36.0
36.0 36.0 36.0 48.0 48.0 48.0 48.0 60.0 60.0 60.0 60.0 72.0 72.0 72.0
72.0

bound2= 3.0 6.0 9.0 12.0 15.0 18.0 21.0 24.0 27.0 30.0 33.0 36.0 39.0
42.0 45.0 48.0 51.0 54.0 57.0 60.0 63.0 66.0 69.0 72.0 75.0 78.0 81.0
84.0

----
 float Total_cloud_cover(time2=28, y=110, x=147);
  :long_name = "Total_cloud_cover (Average for  Mixed Intervals) @ entire_atmosphere";
  :cell_methods = "time2: mean";
  :units = "percent";


 int time2(time2=28);
  :long_name = "forecast time for  (mixed intervals)";
  :units = "hour since 2010-05-25T12:00:00Z";
  :bounds = "time2_bounds";
  :GRIB_orgReferenceTime = "2010-05-25T12:00:00Z";
  :GRIB2_significanceOfRTName = "Start of forecast";
  :_CoordinateAxisType = "Time";
----

time2 = +
{3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54,
57, 60, 63, 66, 69, 72, 75, 78, 81, 84}

bound1= 0.0 0.0 6.0 6.0 12.0 12.0 18.0 18.0 24.0 24.0 30.0 30.0 36.0
36.0 42.0 42.0 48.0 48.0 54.0 54.0 60.0 60.0 66.0 66.0 72.0 72.0 78.0
78.0

bound2= 3.0 6.0 9.0 12.0 15.0 18.0 21.0 24.0 27.0 30.0 33.0 36.0 39.0
42.0 45.0 48.0 51.0 54.0 57.0 60.0 63.0 66.0 69.0 72.0 75.0 78.0 81.0
84.0

=== Case 3: Mixed, non-unique endpoints

Appear to be duplicates:

Q:\cdmUnitTest\tds\new\NAM_CONUS_20km_selectsurface_20100426_1800.grib2

Total_precipitation/Ground or water surface (8) +
 all: Unique=false(44) 0-3 0-3 3-6 3-6 6-9 6-9 9-12 9-12 12-15 12-15
15-18 15-18 18-21 18-21 21-24 21-24 24-27 24-27 27-30 27-30 30-33 30-33
33-36 33-36 36-39 36-39 39-42 39-42 42-45 42-45 45-48 45-48 48-51 51-54
54-57 57-60 60-63 63-66 66-69 69-72 72-75 75-78 78-81 81-84 Interval=3 +

Q:\cdmUnitTest\tds\new\NAM_CONUS_40km_conduit_20100506_1800.grib2

Total_precipitation/Ground or water surface (8) +
 all: Unique=false(44) 0-3 0-3 3-6 3-6 6-9 6-9 9-12 9-12 12-15 12-15
15-18 15-18 18-21 18-21 21-24 21-24 24-27 24-27 27-30 27-30 30-33 30-33
33-36 33-36 36-39 36-39 39-42 39-42 42-45 42-45 45-48 45-48 48-51 51-54
54-57 57-60 60-63 63-66 66-69 69-72 72-75 75-78 78-81 81-84 Interval=3


Q:\cdmUnitTest\tds\new\RUC2_CONUS_20km_pressure_20100509_1300.grib2 +
 Convective_precipitation/Ground or water surface (8) +
 all: Unique=false(45) 0-1 0-2 1-2 0-3 2-3 0-4 3-4 3-5 4-5 0-5 0-6 5-6
3-6 6-7 0-7 0-8 7-8 6-8 0-9 8-9 6-9 0-10 9-10 0-11 10-11 9-11 11-12 9-12
0-12 12-13 0-13 12-14 13-14 0-14 14-15 12-15 0-15 15-16 0-16 16-17 15-17
0-17 0-18 17-18 15-18 Mixed +
 hourAccum: Unique=true Interval=1 +
 runAccum: Unique=true Mixed +
 remaining: Unique=true Mixed

Large_scale_precipitation/Ground or water surface (8) +
 all: Unique=false(45) 0-1 1-2 0-2 2-3 0-3 3-4 0-4 3-5 4-5 0-5 0-6 5-6
3-6 6-7 0-7 7-8 0-8 6-8 8-9 6-9 0-9 9-10 0-10 10-11 9-11 0-11 9-12 0-12
11-12 12-13 0-13 12-14 0-14 13-14 12-15 0-15 14-15 15-16 0-16 15-17 0-17
16-17 17-18 0-18 15-18 Mixed +
 hourAccum: Unique=true Interval=1 +
 runAccum: Unique=true Mixed +
 remaining: Unique=true Mixed +

Q:\cdmUnitTest\tds\new\RUC2_CONUS_20km_surface_20100516_1600.grib2 +
 Convective_precipitation/Ground or water surface (8) +
 all: Unique=false(15) 0-1 0-2 1-2 2-3 0-3 3-6 5-6 6-9 8-9 9-12 11-12
14-15 12-15 15-18 17-18 Mixed +
 hourAccum: Unique=true Interval=1 +
 remaining: Unique=true Mixed

Large_scale_precipitation/Ground or water surface (8) +
 all: Unique=false(15) 0-1 0-2 1-2 2-3 0-3 3-6 5-6 6-9 8-9 11-12 9-12
12-15 14-15 15-18 17-18 Mixed +
 hourAccum: Unique=true Interval=1 +
 remaining: Unique=true Mixed +

Q:/cdmUnitTest/tds/new/RUC2_CONUS_20km_pressure_20100509_1300.grib2

float Convective_precipitation(time=45, y=225, x=301); +
 :long_name = ``Convective_precipitation (Accumulation for Mixed
Intervals) @ surface''; +
 :cell_methods = ``time: sum''; +
 :units = ``kg m-2'';

time = +
{1, 2, 2, 3, 3, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 8, 8, 8, 9, 9, 9, 10,
10, 11, 11, 11, 12, 12, 12, 13, 13, 14, 14, 14, 15, 15, 15, 16, 16, 17,
17, 17, 18, 18, 18}

bound1= 1.0 2.0 2.0 3.0 3.0 4.0 4.0 5.0 5.0 5.0 6.0 6.0 6.0 7.0 7.0 8.0
8.0 8.0 9.0 9.0 9.0 10.0 10.0 11.0 11.0 11.0 12.0 12.0 12.0 13.0 13.0
14.0 14.0 14.0 15.0 15.0 15.0 16.0 16.0 17.0 17.0 17.0 18.0 18.0 18.0

bound2= 0.0 1.0 0.0 2.0 0.0 3.0 0.0 4.0 3.0 0.0 5.0 3.0 0.0 6.0 0.0 7.0
6.0 0.0 8.0 6.0 0.0 9.0 0.0 10.0 9.0 0.0 11.0 9.0 0.0 12.0 0.0 13.0 12.0
0.0 14.0 12.0 0.0 15.0 0.0 16.0 15.0 0.0 17.0 15.0 0.0

int time_bounds(time=45, ncell=2); +
 :long_name = ``bounds for time''; +
 :units = ``hour since 2010-05-09T13:00:00Z'';

data:

----
{
  {0, 1},
  {1, 2},
  {0, 2},
  {2, 3},
  {0, 3},
  {3, 4},
  {0, 4},
  {4, 5},
  {3, 5},
  {0, 5},
  {5, 6},
  {3, 6},
  {0, 6},
  {6, 7},
  {0, 7},
  {7, 8},
  {6, 8},
  {0, 8},
  {8, 9},
  {6, 9},
  {0, 9},
  {9, 10},
  {0, 10},
  {10, 11},
  {9, 11},
  {0, 11},
  {11, 12},
  {9, 12},
  {0, 12},
  {12, 13},
  {0, 13},
  {13, 14},
  {12, 14},
  {0, 14},
  {14, 15},
  {12, 15},
  {0, 15},
  {15, 16},
  {0, 16},
  {16, 17},
  {15, 17},
  {0, 17},
  {17, 18},
  {15, 18},
  {0, 18}
}
----

== Case 4: mixed but contiguous

Q:/cdmUnitTest/tds/new/GFS_CONUS_80km_20100513_0600.grib1

total_precipitation

int time4(time4=35); +
 :long_name = ``forecast time for (mixed intervals)''; +
 :units = ``hour since 2010-05-13T06:00:00Z''; +
 :bounds = ``time4_bounds'';

time4 = +
  {6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96, 102,
108, 114, 120, 126, 132, 138, 144, 150, 156, 162, 168, 174, 180, 192,
204, 216, 228, 240}

edges= 0.0 6.0 12.0 18.0 24.0 30.0 36.0 42.0 48.0 54.0 60.0 66.0 72.0
78.0 84.0 90.0 96.0 102.0 108.0 114.0 120.0 126.0 132.0 138.0 144.0
150.0 156.0 162.0 168.0 174.0 180.0 192.0 204.0 216.0 228.0 240.0

int time4_bounds(time4=35, ncell=2); +
 :long_name = ``bounds for time4''; +
 :units = ``hour since 2010-05-13T06:00:00Z'';

data:

----
{
  {0, 6}, <&#916; -> 6>
  {6, 12},
  {12, 18},
  {18, 24},
  {24, 30},
  {30, 36},
  {36, 42},
  {42, 48},
  {48, 54},
  {54, 60},
  {60, 66},
  {66, 72},
  {72, 78},
  {78, 84},
  {84, 90},
  {90, 96},
  {96, 102},
  {102, 108},
  {108, 114},
  {114, 120},
  {120, 126},
  {126, 132},
  {132, 138},
  {138, 144},
  {144, 150},
  {150, 156},
  {156, 162},
  {162, 168},
  {168, 174},
  {174, 180},
  {180, 192}, <&#916; -> 12>
  {192, 204},
  {204, 216},
  {216, 228},
  {228, 240}
}
----
