:source-highlighter: coderay
[[threddsDocs]]

CalendarDateTime
================

= Time

=== instant

=== interval

=== climatology

work through CF
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/cf-conventions.html#time-coordinate

The intervals over which various statistical methods are applied are
determined by decomposing the date and time specifications of the
climatological time bounds of a cell

*time: method1 within years   time: method2 over years*

* __method1__ is applied to the time intervals (mdHMS0-mdHMS1) within
individual years
* __method2__ is applied over the range of years (y0-y1).

*time: method1 within days   time: method2 over days*

* __method1__ is applied to the time intervals (HMS0-HMS1) within
individual days
* __method2__ is applied over the days in the interval (ymd0-ymd1).

*time: method1 within days   time: method2 over days   time:
method3 over years*

* __method1__ is applied to the time intervals (HMS0-HMS1) within
individual days
* __method2__ is applied over the days in the interval (md0-md1)
* __method3__ is applied over the range of years (y0-y1).

 

*Example 7.8. Climatological seasons*

This example shows the metadata for the average seasonal-minimum
temperature for the four standard climatological seasons MAM JJA SON
DJF, made from data for March 1960 to February 1991.

--------------------------------------------------------------------------------
dimensions:
  time=4;
  nv=2;
variables:
  float temperature(time,lat,lon);
    temperature:long_name="surface air temperature";
    temperature:cell_methods="time: minimum within years time: mean over years";
    temperature:units="K";
  double time(time);
    time:climatology="climatology_bounds";
    time:units="days since 1960-1-1";
  double climatology_bounds(time,nv);
data:  
  time="1960-4-16", "1960-7-16", "1960-10-16", "1961-1-16" ;
  climatology_bounds="1960-3-1",  "1990-6-1",
                     "1960-6-1",  "1990-9-1",
                     "1960-9-1",  "1990-12-1",
                     "1960-12-1", "1991-3-1" ;
                    
--------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------------------------------------------
cell_methods="time: minimum within years time: mean over years"

1) compute minimum temperature in 4 intervals (1960-3-1, 1960-6-1), (1960-6-1, 1960-9-1), (1960-9-1, 1960-12-1), (1960-12-1, 1961-3-1) for 30 years 

2) average each interval over 30 years 1960-1990
----------------------------------------------------------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------------------------------------------------------
desc= "Average minimum temperature for the four standard  climatological seasons MAM JJA SON DJF, made from data for March 1960 to February 1991"

desc= "Average minimum temperature by season, March 1960 to February 1991"

data desc = "Average minimum temperature"
time desc = "climatological season, March 1960 to February 1991"

interval = 3 Months (MAM JJA SON DJF) (climatological season)
range =  March 1960 to February 1991
contiguous = true

time unit = calendar months since March 1960
time coord = "MAM 1960", "JJA 1960", "SON 1960", "DJF 1960", "MAM 1961", "JJA 1961", ...
time coord = "Spring 1960", "Summer 1960", "Fall 1960", "Winter 1960", "Spring 1961", "Summer 1961", ...
time interval = (0,2), (3,5), (6,8), (9,11), (12,14), ...
              = (Mar 1960, May 1960), (Jun 1960, Aug 1960), (Sep 1960, Nov 1960), (Dec 1960, Feb 1961), ...



-------------------------------------------------------------------------------------------------------------------------------------------------

add aux coordinate with alternate time names. should be attached to time
coord, not data variable,

*Example 7.9. Decadal averages for January*

Average January precipitation totals are given for each of the decades
1961-1970, 1971-1980, 1981-1990.

------------------------------------------------------------------------------
dimensions:
  time=3;
  nv=2;
variables:
  float precipitation(time,lat,lon);
    precipitation:long_name="precipitation amount";
    precipitation:cell_methods="time: sum within years time: mean over years";
    precipitation:units="kg m-2";
  double time(time);
    time:climatology="climatology_bounds";
    time:units="days since 1901-1-1";
  double climatology_bounds(time,nv);
data:  // time coordinates translated to date/time format
  time="1965-1-15", "1975-1-15", "1985-1-15" ;
  climatology_bounds="1961-1-1", "1970-2-1",
                     "1971-1-1", "1980-2-1",
                     "1981-1-1", "1990-2-1" ;
------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------
desc= "Average precipitation in Jan for each of the decades 1961-1970, 1971-1980, 1981-1990"

data desc = "Average precipitation"
time desc = "Average January by decade"
interval = Month
contiguous = false
range = 1961-1990

time unit = calendar years since Jan 1961
time interval = (0,9), (10,19), (20,29)
              = (Jan 1961, Jan 1970), (Jan 1971, Jan 1980), (Jan 1981, Jan 1990)

time coord = "Jan 1961-1970", "Jan 1971-1980", "Jan 1981-1990"
--------------------------------------------------------------------------------------------

*Example 7.10. Temperature for each hour of the average day*

Hourly average temperatures are given for April 1997.

---------------------------------------------------------------------------
dimensions:
  time=24;
  nv=2;
variables:
  float temperature(time,lat,lon);
    temperature:long_name="surface air temperature";
    temperature:cell_methods="time: mean within days time: mean over days";
    temperature:units="K";
  double time(time);
    time:climatology="climatology_bounds";
    time:units="hours since 1997-4-1";
  double climatology_bounds(time,nv);
data:  // time coordinates translated to date/time format
  time="1997-4-1 0:30", "1997-4-1 1:30", ... "1997-4-1 23:30" ;
  climatology_bounds="1997-4-1 0:00",  "1997-4-30 1:00",
                     "1997-4-1 1:00",  "1997-4-30 2:00",
                      ...
                      "1997-4-1 23:00", "1997-5-1 0:00" ;

                    
---------------------------------------------------------------------------

-------------------------------------------------------------------------------
Partial = Hour 
desc = "Average Surface Air Temperature for each hour of the day in April 1997"
  
data desc = "Average Surface Air Temperature"                 
time desc = "hour in day in April 1997"
partial = Hour
range = april 1997
                    
time coord = ("1997-4-1 0:00",  "1997-4-30 1:00"),
             ("1997-4-1 1:00",  "1997-4-30 2:00"),
             ...
             ("1997-4-1 23:00", "1997-5-1 0:00)

or

time coord unit = "calendar hours since 1997-4-1"
time coord bounds =  1,2,3...24
time coord bounds = (0,1), (1,2), .. (23,24)

            
-------------------------------------------------------------------------------

*Example 7.12. Temperature for each hour of the typical climatological
day*

This is a modified version of the previous example, ``Temperature for
each hour of the average day''. It now applies to April from a 1961-1990
climatology.

----------------------------------------------------------------
variables:
  float temperature(time,lat,lon);
    temperature:long_name="surface air temperature";
    temperature:cell_methods="time: mean within days ",
      "time: mean over days time: mean over years";
    temperature:units="K";
  double time(time);
    time:climatology="climatology_bounds";
    time:units="days since 1961-1-1";
  double climatology_bounds(time,nv);
data:  // time coordinates translated to date/time format
  time="1961-4-1 0:30", "1961-4-1 1:30", ..., "1961-4-1 23:30" ;
  climatology_bounds="1961-4-1 0:00", "1990-4-30 1:00",
                     "1961-4-1 1:00", "1990-4-30 2:00",
                     ...
                     "1961-4-1 23:00", "1990-5-1 0:00" ;
                    
----------------------------------------------------------------

*Example 7.11. Extreme statistics and spell-lengths*

Number of frost days during NH winter 2007-2008, and maximum length of
spells of consecutive frost days. A ``frost day'' is defined as one
during which the minimum temperature falls below freezing point (0
degC). This is described as a climatological statistic, in which the
minimum temperature is first calculated within each day, and then the
number of days or spell lengths meeting the specified condition are
evaluated. In this operation, the standard name is also changed; the
original data are `air_temperature `.

---------------------------------------------------------------------------------
variables:
  float n1(lat,lon);
    n1:standard_name="number_of_days_with_air_temperature_below_threshold"; 
    n1:coordinates="threshold time";
    n1:cell_methods="time: minimum within days time: sum over days";
  float n2(lat,lon);
    n2:standard_name="spell_length_of_days_with_air_temperature_below_threshold";
    n2:coordinates="threshold time";
    n2:cell_methods="time: minimum within days time: maximum over days";
  float threshold;
    threshold:standard_name="air_temperature";
    threshold:units="degC";
  double time;
    time:climatology="climatology_bounds";
    time:units="days since 2000-6-1";
  double climatology_bounds(time,nv);
data: 
  time="2008-1-16 6:00";
  climatology_bounds="2007-12-1 6:00", "2000-8-2 6:00";
  threshold=0.; 

                    
---------------------------------------------------------------------------------

*Example 7.13. Monthly-maximum daily precipitation totals*

Maximum of daily precipitation amounts for each of the three months
June, July and August 2000 are given. The first daily total applies to 6
a.m. on 1 June to 6 a.m. on 2 June, the 30th from 6 a.m. on 30 June to 6
a.m. on 1 July. The maximum of these 30 values is stored under time
index 0 in the precipitation array.

--------------------------------------------------------------------------------
dimensions:
  time=3;
  nv=2;
variables:
  float precipitation(time,lat,lon);
    precipitation:long_name="Accumulated precipitation";
    precipitation:cell_methods="time: sum within days time: maximum over days"; 
    precipitation:units="kg";
  double time(time);
    time:climatology="climatology_bounds";
    time:units="days since 2000-6-1";
  double climatology_bounds(time,nv);
data:  // time coordinates translated to date/time format
  time="2000-6-16", "2000-7-16", "2000-8-16" ;
  climatology_bounds="2000-6-1 6:00:00", "2000-7-1 6:00:00",
                     "2000-7-1 6:00:00", "2000-8-1 6:00:00",
                     "2000-8-1 6:00:00", "2000-9-1 6:00:00" ;
                    
--------------------------------------------------------------------------------
