/* Generated By:JavaCC: Do not edit this line. DASParserConstants.java */
package dods.dap.parser;

public interface DASParserConstants {

  int EOF = 0;
  int ATTR = 6;
  int ALIAS = 7;
  int BYTE = 8;
  int INT16 = 9;
  int UINT16 = 10;
  int INT32 = 11;
  int UINT32 = 12;
  int FLOAT32 = 13;
  int FLOAT64 = 14;
  int STRING = 15;
  int URL = 16;
  int WORD = 17;
  int STR = 18;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<ATTR>",
    "<ALIAS>",
    "<BYTE>",
    "<INT16>",
    "<UINT16>",
    "<INT32>",
    "<UINT32>",
    "<FLOAT32>",
    "<FLOAT64>",
    "<STRING>",
    "<URL>",
    "<WORD>",
    "<STR>",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\";\"",
  };

}
