:source-highlighter: coderay
[[threddsDocs]]

= GRIB

== Standards

=== GRIB1 and GRIB2

The World Meteorological Organization (WMO) Commission for Basic Systems (CBS) met in 1985 to create the GRIB (GRIdded Binary) format.
GRIB Edition 1 was approved in February 1994. GRIB Edition 2 format was approved in 2003. Transition to GRIB-2 has been slow, despite the severe limitations of GRIB-1.
By international treaty, national weather services are required to publish their data in GRIB (and BUFR) for international exchange.

Data is stored in compressed binary format, replacing earlier text encoding formats.

=== Standard Tables / Local Tables

Information in the files references external tables, either WMO standard tables or local tables defined by each National Center.
For criticism of GRIB table handling practices, see: https://doi.org/10.5065/vkan-dp10[Archiving in GRIB considered Harmful].

==== WMO
- The GRIB Bible: http://www.wmo.int/pages/prog/www/WMOCodes/WMO306_vI2/VolumeI.2.html[Manual on Codes (WMO-No. 306)]
- WMO Standard Tables: http://www.wmo.int/pages/prog/www/WMOCodes/WMO306_vI2/LatestVERSION/LatestVERSION.html
- WMO now publishes their standard tables in XML for GRIB2 (though not GRIB1): http://www.wmo.int/pages/prog/www/WMOCodes/WMO306_vI2/LatestVERSION/GRIB2_15_1_0.zip

==== NCEP

NCEP does not publish their tables in a machine-readable format, so we periodically screenscrape their HTML pages. The results are stored in the THREDDS GIT site.

* NCEP GRIB-1 Tables: http://www.nco.ncep.noaa.gov/pmb/docs/on388/[Original]  https://github.com/Unidata/thredds/tree/master/grib/src/main/resources/resources/grib1/ncep[CDM XML]
* NCEP GRIB-2 Tables: http://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc.shtml[Original] https://github.com/Unidata/thredds/tree/master/grib/src/main/resources/resources/grib2/ncep[CDM XML]

==== NCAR

* NCAR / RDS has extensive documentation on the datasets they support: http://rda.ucar.edu/
* Example : http://rda.ucar.edu/datasets/ds628.0/docs/


== Raw GRIB

=== Streaming

GRIB is a record-oriented format, each record is nominally independent of any other. GRIB files typically consist of concateneated GRIB records.
To read the individual records in a GRIB-1 file, one can use the following:

[source,java]
----
      RandomAccessFile dataRaf = new RandomAccessFile(location, "r");
      Grib1RecordScanner scan = new Grib1RecordScanner(dataRaf);
      while (scan.hasNext()) {
        Grib1Record r = scan.next();
        if (r == null) break; // done
        // do stuff
        Grib1SectionGridDefinition gdss = r.getGDSsection();
        ...
      }
----

Grib2RecordScanner and GRIB2record are similarly used for GRIB-2 records. See those classes for more details. Note that these are not considered public APIs.


=== Reference Time / Valid Time

=== ToolsUI

=== Vertical Coordinates

=== Time Intervals

=== Ensembles

=== Data Encoding / Compression

== Turning GRIB into netCDF with the CDM

=== Variables grouped by PDS
<<collections/GribConfig#pdsHash,Control how PDS are made into variables>>

=== Horizontal Reference System grouped by GDS

<<collections/GribConfig#gdsHash,Fix errors in GDS encoding>>

=== Time Intervals

<<collections/GribConfig#intvFilter,Time Interval filters>>

=== Table Handling

== Grib Collections

=== Grib Indexes

=== Collection Indexes

=== Partitions

<<collections/Partitions#,Grib Partitions>>

=== Checking large collections

<<collections/TDM#GCPass1,GCPass1>>


== TDS and GRIB Feature Collections

=== Configuration

<<collections/GribConfig#, Grib Configuration>>
<<collections/GribCollectionFaq#,How do I control where the index files are written?>>
