:source-highlighter: coderay
[[threddsDocs]]

= Subset Service for Radar Level2 Data (version 1.0)

*Please note that the interface described here is still a prototype, and subject to change.*

_Please send comments to the mailto:thredds@unidata.ucar.edu[THREDDS
email group]_

== Example urls

Some interesting URLs for the radarServer service:

* Radar Collections
http://thredds.ucar.edu/thredds/radarServer/catalog.xml
* Level2 Stations for IDD dataset
http://thredds.ucar.edu/thredds/radarServer/nexrad/level2/IDD/stations.xml
* Level2 Stations for CCS039 dataset
http://thredds.ucar.edu/thredds/radarServer/nexrad/level2/CCS039/stations.xml
* Level2 IDD Dataset
http://thredds.ucar.edu/thredds/radarServer/nexrad/level2/IDD/dataset.xml
* Level2 CCS039 Dataset
http://thredds.ucar.edu/thredds/radarServer/nexrad/level2/CCS039/dataset.xml

== Subsetting Parameters

Some interesting URLs for the radarServer query service:

* IDD dataset with Bounding Box and last hour
http://thredds.ucar.edu/thredds/radarServer/nexrad/level2/IDD?north=40.00&south=39.00&west=-105.2&east=-100.0&time=present[http://thredds.ucar.edu/thredds/radarServer/nexrad/level2/IDD?north=40.00&south=39.00&west=-105.0&east=-100.0&time_end=present&time_duration=PT1H]
* IDD dataset and station KFTG latest time
http://thredds.ucar.edu/thredds/radarServer/nexrad/level2/IDD?stn=KFTG&time=present
* IDD dataset and station KFTG one day
http://thredds.ucar.edu/thredds/radarServer/nexrad/level2/IDD?stn=KFTG&time_end=present&time_duration=PT24H
* IDD dataset and station KFTG all times
http://thredds.ucar.edu/thredds/radarServer/nexrad/level2/IDD?stn=KFTG&temporal=all
* CCS039 dataset Station KDMX all times
http://thredds.ucar.edu/thredds/radarServer/nexrad/level2/CCS039?stn=KDMX&temporal=all
* CCS039 dataset Station KDMX 2 hour time range
http://thredds.ucar.edu/thredds/radarServer/nexrad/level2/CCS039?stn=KDMX&time_start=1998-06-29T18:00:00&time_end=1998-06-29T19:00:00

=== Specify spatial extent

Latitude, longitude values are specified in decimal degrees north and
east, respectively.

Use one of the following methods:

==== Specify lat/lon bounding box

Specify all of these parameters (order does not matter):

* **north**: latitude north (decimal degrees)
* **south**: latitude south (decimal degrees)
* **east**: longitude east (decimal degrees)
* **west**: longitude west (decimal degrees)

The bounding box has *west* as its west edge, includes all points going
*east* until the east edge. Units must be degrees east, may be positive
or negative, and will be taken modulo 360. Therefore, when crossing the
dateline, the west edge may be greater than the east edge. Examples:

* *north=17.3&south=12.088&west=140.2&east=160.0*

==== Specify lat/lon point

* *latitude:* latitude of point, decimal degrees north
* *longitude:* longitude of point, decimal degrees east

The requested point must lie within the dataset spatial range. The
station closest to the requested point will be used.

Examples:

* *latitude=17.3&longitude=140.2*

==== Specify station(s)

*You may specify a list of stations instead of the lat/lon point or
bounding box*

* **stn=**name of stations, separated by `,` (comma)

The list of valid stations is available from the Dataset Description.
Station names with spaces or other illegal characters must be escaped.

Examples:

* *stn=KFTG*
* *stn=KFTG,KGLD,KPUX*
* *stn=KFTG&stn=KGLD&stn=KPUX*

=== Specify time

Use one of the following methods:

==== Time range

Specify 2 of these 3 parameters (order does not matter):

* **time_start**: starting time as an W3C date string or `present`
* **time_end**: ending time as an W3C date string or `present`
* **time_duration**: length of time as an W3C time duration

The intersection of the requested time range with the dataset time range
will be returned.

Examples:

* *time_start=2007-03-29T12:00:00Z&time_end=2007-03-29T13:00:00Z*
(between 12 and 1 pm Greenwich time)
* *time_start=present&time_duration=P3D* (get 3 day forecast starting
from the present)
* *time_end=present&time_duration=PT3H* (get last 3 hours)

==== Time point

* *time:* time as an W3C date string or `'present'`

The `latest` data retrieval is obtained by `time=present`. The requested
time point must lie within the dataset time range. The time slice/point
closest to the requested time will be returned.

Examples:

* *time=2007-03-29T12:00:00Z*
* *time=present*

==== All Times

* *temporal=all*

This returns data from all available times.

=== Specify the return format

The accept parameter default is xml and it is the only legal one at this
time.
