= NcStream Data message (version 1)
[[threddsDocs]]

This documents version 1 of the NcStream Data message, used by CDM/TDS < 5.0.

== Grammar

----
dataMessage := MAGIC_DATA, vlenb, NcStreamProto.Data, regData | vlenData | seqData | structData

regData := vlenb, (byte)*vlenb
vlenData := vlenn, {vlenb, (byte)*vlenb}*vlenn
seqData := {MAGIC_VDATA, vlenb, NcStreamProto.StructureData}*, MAGIC_VEND
structData := vlenb, NcStreamProto.StructureData

vlenb := variable length encoded positive integer == length of the following object in bytes
vlenn := variable length encoded positive integer == number of objects that follow
NcStreamProto.Data := Data message encoded by protobuf
byte := actual bytes of data, encoding described by the NcStreamProto.Data message
----

* Primitive types are fixed length, following Java; StructureData has no padding.
* If StructureData member list is empty, then all members are present.


== NcStreamProto.Data

----

message Range {
  uint64 start = 1;
  uint64 size = 2;   // 0 = empty, -1 = vlen (maybe leave off vlens)
  uint64 stride = 3;
}
message Section {
  repeated Range range = 1;
}
enum Compress {
  NONE = 0;
  DEFLATE = 1;
}
message Data {
  string varName = 1; # <1>
  DataType dataType = 2; # <2>
  Section section = 3; # <3>
  oneof bigend_present { # <4>
    bool bigend = 4;  // [default=true] in proto2
  }
  uint32 version = 5; // version=2 for proto2, =3 for proto3 (v5.0+) # <5>
  Compress compress = 6; # <6>
  bool vdata = 7; # <7>
  uint32 uncompressedSize = 8; # <8>
}
----

<1>  full name of Variable
<2>  _DataType_ for the returned array (corresponds to _ucar.nc2.DataType_)
<3>  Section of the full variable's shape.
<4>  Stored in big or small endian (reader makes right). One must test if version >= 3 to deal with missing values.
http://stackoverflow.com/questions/33204321/upgrading-protobuf-from-version-2-to-3-incompatible-with-protobuf-default-valu[Details]
<5>  version of the data storage format.
<6>  compression algorithm.
<7>  if the Variable is variable-length
<8>  uncompressed size of the returned data, in bytes.

**Primitive types**: arrays of primitives are stored in row-major order.

* *char* is a legacy data type contains uninterpreted characters, one character per byte. Typically these contain 7-bit ASCII characters.
* *byte, short, int, long* (signed) and *ubyte, ushort, uint, ulong* (unsigned), or **float**, *double* specified by the __dataType__.

*Variable length types (String, Opaque):* The number of objects is written, then each object, preceded by its length in bytes as a vlen. Strings
are encoded as UTF-8 bytes. Opaque is just a bag of bytes.

*Variable length arrays:* First the number of objects is written, then each object, preceded by its length in bytes as a vlen.

*Structure types (Structure, Sequence):* An array of StructureData. _Can be encoded in row or col (?)._

== Data Encoding

=== String array example

----
String desc(5);
----
.  5 (as vlen)
.  then 5 String objects, for each:
..  length in bytes (as vlen)
..  UTF-8 bytes

=== Vlen data example

----
int levels(ninst= 23, acqtime=100, *);
----

.  2300 (as vlen)
.  then 2300 objects, for each:
..  length in bytes (as vlen)
..  nelems (as vlen)
..  nelems integers

=== Compound Type

Should be able to pop this in and out of a ByteBuffer (java) or void * (C), then use pointer manipulation to decode on the fly. Maybe good candidate
for encoding with protobuf

.  n
.  n structs
.  nheap
.  nheap objects

in this case, you have to read everything. if buffer has no vlens or strings, could use fixed size offsets. otherwise record the offsets.

.  n
.  n structs
..  nheap
..  nheap objects

(each struct contains its own heap)

.  n
.  n lengths
.  n structs
..  nheap
..  nheap objects

(each struct contains its own heap)

this indicates maybe we should rewrite ArrayStructureBB to have separate heaps for each struct.

=== Nested Vlen

A nested variable length field, goes on the heap

----
netcdf Q:/cdmUnitTest/formats/netcdf4/vlen/cdm_sea_soundings.nc4 {
 dimensions:
   Sounding = 3;

 variables:

  Structure {
    int sounding_no;
    float temp_vl(*);
  } fun_soundings(Sounding=3);
}
----
