:source-highlighter: coderay
[[threddsDocs]]

= Collection Specification String

A *_collection specification string_* creates a collection of files by
scanning file directories and looking for matches. It can optionally
extract a date from a filename. It has these parts:

. A root directory (absolute file path).
. Followed by an optional _``/**/''_ indicating to scan all
subdirectories under the root directory.
. Followed by a regular expression that is applied to the filename.
. An optional _*date extractor*_ may be specified that computes a date
from the filename.

== Example 1

[source,bash]
----
 /data/ldm/pub/native/grid/NCEP/GFS/Alaska_191km/.*nc$
----

All files ending with ``nc'' in the directory
__/data/ldm/pub/native/grid/NCEP/GFS/Alaska_191km__. The ``.*nc$'' is a
regular expression which tries to match the path name after the top
directory __/data/ldm/pub/native/grid/NCEP/GFS/Alaska_191km/__. The
``.*'' means ``any number of any character'' and the ``nc$'' means
"ending with __nc"__. If you want to make sure it ends with ``.nc'', you
need:

[source,bash]
----
 /data/ldm/pub/native/grid/NCEP/GFS/Alaska_191km/.*\.nc$
----

Since ``.'' is a special character in regular expressions, one needs to
escape it to match a literal ``.'', so ``\.nc$'' means match the
characters ``.'' ``n'' ``c'' at the end of the string.

Its generally important to use the `$' to indicate the end of string,
since a common convention is to write auxilary files by naming them <org
file>.<ext>, and you need to eliminate the auxilary files from the
collection.

== Example 2

[source,bash]
----
 /data/ldm/pub/native/grid/NCEP/GFS/Alaska_191km/**/.*\.nc$
----

All files ending with ``.nc'' in the directory
_/data/ldm/pub/native/grid/NCEP/GFS/Alaska_191km_ and its
subdirectories.

== Example 3

[source,bash]
----
/data/ldm/pub/native/grid/NCEP/GFS/Alaska_191km/**/GFS_Alaska_191km_#yyyyMMdd_HHmm#\.nc$
----

Search the directory _/data/ldm/pub/native/grid/NCEP/GFS/Alaska_191km_
and its subdirectories for files that match the regular expression:

[source,bash]
----
 GFS_Alaska_191km.........\.nc$
----

Remember that an unescaped ``.'' matches any character. An escaped ``\.'' matches the literal ``.'' character.

From the filename, extract the date by applying the
<<SimpleDateFormat#,SimpleDateFormat>> template _yyyyMMdd_HHmm_ to
the portion of the filename after

[source,bash]
----
GFS_Alaska_191km
----

== Method for constructing collection specification Strings

The idea is that one copies an example file path, and then modifies it:
For example, copy an example filename:

[source,bash]
----
/data/ldm/pub/native/grid/NCEP/GFS/Alaska_191km/20090301/GFS_Alaska_191km_20090301_0600.grib1
----

Modify it to include subdirectories:

[source,bash]
----
/data/ldm/pub/native/grid/NCEP/GFS/Alaska_191km/**/GFS_Alaska_191km_20090301_0600.grib1
----

Demarcate the part of the filename where the run date is encoded, using
`#' chars:

[source,bash]
----
/data/ldm/pub/native/grid/NCEP/GFS/Alaska_191km/**/GFS_Alaska_191km_#20090301_0600#.grib1
----

Substitute a <<SimpleDateFormat#,SimpleDateFormat>>:

[source,bash]
----
/data/ldm/pub/native/grid/NCEP/GFS/Alaska_191km/**/GFS_Alaska_191km_#yyyyMMdd_HHmm#.grib1
----

Make sure that the name ends with ``grib1'':

[source,bash]
----
/data/ldm/pub/native/grid/NCEP/GFS/Alaska_191km/**/GFS_Alaska_191km_#yyyyMMdd_HHmm#\.grib1$
----

=== Notes:

You have to escape any of these regular expression literal characters
that you want to match. Its a good idea to avoid these characters in
directory and file names, with the exception of the `.'

[source,bash]
----
 .|*?+(){}[]^$\
----

* The dot character `.' matches any single character.
* A `^' character matches the null string at the start of a line.
* A `$' character matches the null string at the end of a line.

The *date extractor* can only be used on the filename in a collection
specification string. If the date is part of a directory name, use the
more general *dateFormatMark* on the
*<<FeatureCollections#collection,collection>>* element.

The *date extractor* element cannot be used after the regular
expression. So **GFS_Alaska_191km_#yyyyMMdd_HHmm#.*grib**$ is ok but
**GFS.*km#yyyyMMdd_HHmm#grib$**. This is because the . Use the more
general **dateFormatMark**:

[source,xml]
----
<collection spec="/data/ldm/pub/native/grid/NCEP/GFS/Alaska_191km/**/GFS.*km.*grib$" dateFormatMark="yyyyMMdd_HHmm#.grib#$" />
----

=== Resources for Regular Expressions:

* http://en.wikipedia.org/wiki/Regular_expression[Wikipedia]
* http://www.araxis.com/merge/topic_regexpreference.html[Reference]
