:source-highlighter: coderay
[[threddsDocs]]

= TDS and ncISO: Metadata Services

The TDS distribution includes the
http://www.ngdc.noaa.gov/eds/tds/[ncISO package] from NOAA/NGDC (many
thanks to Dave Neufeld and Ted Habermann).

== ncISO Services

ncISO supports three new services for datasets:

* **NCML**: an NcML representation ofthe dataset’s structure and metadata;
* **ISO**: an ISO 19115 metadata representation of the dataset; and
* **UDDC**: an evaluation of how well the metadata contained in the dataset conforms to the
<<../../netcdf-java/metadata/DataDiscoveryAttConvention#,NetCDF
Attribute Convention for Data Discovery (NACDD)>> (also see the
https://geo-ide.noaa.gov/wiki/index.php?title=NetCDF_Attribute_Convention_for_Dataset_Discovery[NOAA/NGDC
page on NACDD]).

== Enabling ncISO Services

The ncISO services are disabled by default and can be enabled for
locally served datasets by including the following in the
threddsConfig.xml file:

-----------------------------
<NCISO>
  <ncmlAllow>true</ncmlAllow>
  <uddcAllow>true</uddcAllow>
  <isoAllow>true</isoAllow>
</NCISO>
-----------------------------

== Providing ncISO Services for Datasets

Once ncISO is enabled, datasets can be configured to have the three
ncISO services in the TDS catalog configuration files similar to the way
other services are configured. The service element’s serviceType and
base attribute values must be as follows:

---------------------------------------------------------------
<service name="ncml" serviceType="NCML" base="/thredds/ncml/"/>
<service name="uddc" serviceType="UDDC" base="/thredds/uddc/"/>
<service name="iso" serviceType="ISO" base="/thredds/iso/"/>
---------------------------------------------------------------

The dataset to be served must reference a containing compound service by
the service name. For instance, if a compound service named _all_
contained all three services listed above:

------------------------------------------------------------
<dataset ID="sample" name="Sample Data" urlPath="sample.nc">
  <serviceName>all</serviceName>
</dataset>
------------------------------------------------------------
