:source-highlighter: coderay
[[threddsDocs]]


Auth
====

= HTTP Authorization Control +

== Dennis Heimbigner +
 Unidata +
 July 20, 2011 +
 Revised: September 15, 2011

== HTTPAuthStore

New classes are introduced to the package ucar.httpclient to support a
variety of authorization mechanisms. These mechanisms currently are Http
BASIC and DIGEST, and client side keys for SSL connections. Note that
for outgoing firewalls that require authentication, the BASIC or DIGEST
schemes will be used as a rule.

Most of these classes are invisible to the user. The user indirectly
accesses them through the HTTPSession interface.

The primary new classes are

* _HTTPAuthStore_
* _HTTPAuthScheme_
* _HTTPAuthProvider_
* _HTTPSSLProvider_

The goal of these new classes is to provide a general approach to the
problem of client-side authorization with respect to some server. The
approach is to provide various kinds of authorization credentials
(broadly construed) to servers by clients.

Before reading this document, the reader should have read the
<<./Session.html,Session.adoc>> and the HTTPauthentication.html
documents to understand the context in which the authorization
mechanisms operate. The section <<#Status,Status>> should also be read
to get important information about the current state of this code.

The authorization schemes currently supported are as follows.

1.  HTTP Basic
2.  HTTP Digest
3.  Client-side keys using java keystores and truststores.

=== Global and Per-Connection Credentials

There is an additional factor. It is desirable to support both
``global'' and ``per-session'' authorization.

* Global — this means that a single set of credentials is set globally
and is adequate for all code running within a single program (i.e. linux
or windows process).
* Per-session — this means that each session (HTTPSession instance) may
have a separate set of credentials. Further, it must be guaranteed that
no connection is re-used to avoid inadvertent access to some other set
of credentials.

=== Delegation

Finally, there is the ``delegation'' problem. This is when a client
program (or a server program acting as a client) wants to masquerade as
some user and utilize the authorizations provided for that user. Of
course, this requires that the program be sufficiently trusted so that
is will handle the delegation responsibly.

Delegation is likely to be most common on the server-side because a
server will be handling multiple clients and may have to access
additional information on behalf of various clients.

== Approach

Access rights are stored in a ``database'' that is globally accessible
to all code within a single operating system process and is independent
of any threading. The fact that this database is shared is important so
that a consistent set of credentials is provided everywhere within the
operating system process.

This database is kept as class level object consisting of a set of row
instances of type __HTTPAuthStore.Entry__. The columns of each entry are
as follows.

1.  scheme of type _HTTPAuthScheme_ (with a special instance acting as
the wildcard ANY_SCHEME).
2.  url of type _String_ (with a special instance acting as the wildcard
ANY_URL).
3.  creds of type
__org.apache.commons.httpclient.auth.CredentialsProvider__.

The _HTTPAuthStore_ <<#HTTPAuthStore.API,API>> itself provides
operations to insert and delete rows, and to search for rows matching
specified criteria.

== Class Descriptions

=== HTTPSSLProvider

Note that any typical implementation of the _CredentialsProvider_
interface may be used for an _HTTPAuthStore_ database row. As a special
case and when the scheme is SSL, then the user should use the provided
_HTTPSSLProvider_ <<#HTTPSSLProvider.API,class>> for this field. Its
constructor requires arguments for the client side keystore plus
password and the client side truststore plus password. The keystore and
truststore arguments are absolute paths.

If the truststore is not specified then essentially any certificate
provided by the server will be accepted (including, specifically,
self-signed certificates).

=== HTTPAuthScheme

The scheme field is assumed to store an instance of the enum type
<<#HTTPAuthScheme.API,HTTPAuthScheme>>. The elements of the enum are
as follows:

* BASIC
* DIGEST
* SSL
* ANY

BASIC and DIGEST operate essentially the same and require as credentials
a principal and a password. The SSL scheme is to accomodate client-side
key authentication. It requires information about a keystore and
truststore and their associated passwords. The ANY value serves as a
wildcard.

=== HTTPAuthProvider

The _HTTPAuthProvider_ class implements the
_org.apache.commons.httpclient.auth.CredentialsProvider_ interface. It
is used as a wrapper for the _HTTPAuthStore.Entry_ creds field and
manages accessing the auth store at the appropriate point to obtain the
information needed for getting the proper credentials.

The constructor for _HTTPAuthProvider_ takes a URL as an argument. When
the _getCredentials_ method is invoked the URL plus the _AuthScheme_
argument are used to locate the most specific matching entry in the auth
store database. This entry is then used to properly invoke the correct
_CredentialsProvider_ instance.

== URL Matching

When searching the auth store rows for matches, schemes are either
simple equal or not equal. However, when matching the url field, urls
may match in a more complicated way. In particular, a missing user info
field or missing path will act as a wildcard when matching to another
url. For the path, prefix matching also can result in a match.

== Serialization

Encrypted serialization of the auth store is supported with significant
limitations. The relevant methods are as follows.

* static public void serialize(OutputStream ostream, String password)
throws HTTPException
* static public void deserialize(InputStream istream, String password)
throws HTTPException

Serialization (and de-serialization) of the scheme and url fields are
straightforward.

**WARNING**: Serialization of the creds field is tricky because the
instance may or may itself be serializable. If it supports the
_Serializable_ interface, then it will be serialized. If it does not
implement that interface, then the class of the _creds_ field is
serialized instead. This will be ok for essentially stateless
implementations of __CredentialsProvider__, but otherwise will produce
incorrect results.

== Appendices: Authorization APIs

=== HTTPAuthStore API

The primary API methods are described. All of the following methods are
tagged ``static public''. Other, minor methods, exist and the Javadoc
should be consulted for those.

==== Insert

The single method takes an _HTTPAuthStore.Entry_ instance to insert into
the auth store database. It returns false if the entry instance replaces
an existing row, else returns true.

------------------------------------------
boolean insert(HTTPAuthStore.Entry entry);
------------------------------------------

==== Remove

The single method takes an _HTTPAuthStore.Entry_ instance to remove from
the auth store database. It returns false if the entry instance is not
in the current database, else returns true.

------------------------------------------
boolean remove(HTTPAuthStore.Entry entry);
------------------------------------------

==== Search

The single method takes an _HTTPAuthStore.Entry_ instance to serve as
the pattern to search the auth store database. It returns an array of
matching entries, which may be zero length. The returned list is ordered
from most restrictive to least restrictive.

------------------------------------------
Entry[] search(HTTPAuthStore.Entry entry);
------------------------------------------

The search pattern match is defined by the following tests.

[width="100%",cols="100%",]
|========================================================
a|
Scheme

Comparison is by ==; wildcard is specified by ANY_SCHEME.

a|
URL

Comparison is as defined <<#url.match,above>>.

|========================================================

=== HTTPAuthScheme API

The primary methods of _HTTPAuthScheme_ enum are as follows.

* public String getSchemeName() returns a canonical string representing
the name of the scheme.
* static public HTTPAuthScheme schemeForName(String name) returns an
HTTPAuthScheme value given a string and returns null if there is no such
value.
* static public HTTPAuthScheme fromAuthScope(String name) returns an
HTTPAuthScheme value given a string from an _AuthScope_ instance and
returns null if the name is not recognized.

=== HTTPAuthProvider API

The primary methods of the _HTTPAuthProvider_ class are as follows.

* public HTTPAuthProvider(String url) is the constructor taking a url
for controlling the search into the auth store.
* public Credentials getCredentials(AuthScheme authscheme, String host,
int port, boolean isproxy) throws CredentialsNotAvailableException is
invoked by the underlying authorization code to get the credentials and
this method in turn consults the auth store.

=== HTTPSSLProvider API

The primary methods of the _HTTPAuthProvider_ class are as follows.

* public HTTPSSLProvider(String keystore,String keypass, String
truststore,String trustpass)
* public HTTPSSLProvider(String keystore, String keypass)
* public String getKeystore()
* public String getKeypassword()
* public String getTruststore()
* public String getTrustpassword()
* public Credentials getCredentials(AuthScheme authscheme, String host,
int port, boolean isproxy) throws CredentialsNotAvailableException +
 (Note that this interface is abused and is not intended for external
invocation).

== Status

* Currently, this code is in the Thredds code trunk. Backward
compatibility is provided for the old handling of ESG keystore arguments
using the java -D flags __keystore__, __keystorepassword__,
__truststore__, and __truststorepassword__.

== Author

Author: Dennis Heimbigner +
 Affiliation: UCAR/Unidata +
 email: dmh@ucar.edu
