:source-highlighter: coderay
[[threddsDocs]]

// Enables non-selectable callout icons drawn using CSS.
:icons: font

= Runtime Loading

These are the various classes that can be plugged in at runtime:

== Register an `IOServiceProvider`

[source,java]
-----------------------------------------------------------
 ucar.nc2.NetcdfFile.registerIOProvider( String className);
-----------------------------------------------------------

The registered class must implement `ucar.nc2.IOServiceProvider`. When
a `NetcdfFile` is opened, we loop through the `IOServiceProvider`
classes and call

[source,java]
------------------------------------------------------------
  boolean isValidFile( ucar.unidata.io.RandomAccessFile raf)
------------------------------------------------------------

on each, until one returns true. This method must be fast and accurate.

== Register a `CoordSysBuilder`

[source,java]
-----------------------------------------------------------------------------------------------
 ucar.nc2.dataset.CoordSysBuilder.registerConvention( String conventionName, String className);
-----------------------------------------------------------------------------------------------

The registered class must implement `ucar.nc2.dataset.CoordSysBuilderIF`.
The `NetcdfDataset` is checked if it has a *Convention* attribute, and if so,
it is matched by __conventionName__. If not, loop through the `CoordSysBuilderIF`
classes and call

[source,java]
-----------------------------------
 boolean isMine(NetcdfFile ncfile)
-----------------------------------

on each, until one returns true. If none are found, use the default
*_Coordinate* Convention.

== Register a `CoordTransBuilder`

[source,java]
-----------------------------------------------------------------------------------------------
 ucar.nc2.dataset.CoordTransBuilder.registerTransform( String transformName, String className);
-----------------------------------------------------------------------------------------------

The registered class must implement
`ucar.nc2.dataset.CoordTransBuilderIF`. The Coordinate Transform
Variable must have the transform name as one of its parameters.

== Register a `FeatureDatasetFactory`

[source,java]
------------------------------------------------------------------------------------------------------
 ucar.nc2.ft.FeatureDatasetFactoryManager.registerFactory( FeatureType featureType, String className);
------------------------------------------------------------------------------------------------------

The registered class must implement `ucar.nc2.ft.FeatureDatasetFactory`,
see javadoc for that interface.

== Register a GRIB1 or GRIB2 Lookup Table (4.2 and before)

[source,java]
-----------------------------------------------------------------------------
  ucar.grib.grib1.GribPDSParamTable.addParameterUserLookup( String filename);
  ucar.grib.grib2.ParameterTable.addParametersUser( String filename);
-----------------------------------------------------------------------------

== Register a GRIB1 table (4.3)

[source,java]
-----------------------------------------------------------------------------------------------------------------------------------
  ucar.nc2.grib.grib1.tables.Grib1ParamTables.addParameterTable(int center, int subcenter, int tableVersion, String tableFilename);
-----------------------------------------------------------------------------------------------------------------------------------

* This registers a single table for the given center/subcenter/version.
* See <<formats/GribTables#,GribTables>> for more information
about parameter tables.
* GRIB2 table handling is still being developed.

== Register a GRIB1 lookup table (4.3)

[source,java]
--------------------------------------------------------------------------------------------
 ucar.nc2.grib.grib1.tables.Grib1ParamTables.addParameterTableLookup(String lookupFilename);
--------------------------------------------------------------------------------------------

* This registers one or more tables for different
center/subcenter/versions.
* See <<formats/GribTables#,GribTables>> for more information
about lookup tables.
* GRIB2 table handling is still being developed.

== Register a BUFR Table lookup

[source,java]
-----------------------------------------------------------------------------------------------------------
  ucar.nc2.iosp.bufr.tables.BufrTables.addLookupFile( String filename) throws throws FileNotFoundException;
-----------------------------------------------------------------------------------------------------------

The file must be a <<formats/BufrTables#,BUFR table lookup file>>.

''''

== Runtime Configuration

Instead of calling the above routines in your code, you can pass the CDM
library an XML configuration file. Note that your application must call
**ucar.nc2.util.xml.RuntimeConfigParser.read()**.

The configuration file looks like this:

[source,xml]
----
<?xml version="1.0"?>
<nj22Config>
  <ioServiceProvider  class="edu.univ.ny.stuff.FooFiles"/>  <!--1-->
  <coordSysBuilder convention="foo" class="test.Foo"/>  <!--2-->
  <coordTransBuilder name="atmos_ln_sigma_coordinates" type="vertical" class="my.stuff.atmosSigmaLog"/>  <!--3-->
  <featureDatasetFactory featureType="Point" class="gov.noaa.obscure.file.Flabulate"/>  <!--4-->
  <gribParameterTable edition="1" center="58" subcenter="-1" version="128">C:/grib/tables/ons288.xml</gribParameterTable>  <!--5-->
  <gribParameterTableLookup edition="1">C:/grib/tables/ncepLookup.txt</gribParameterTableLookup>  <!--6-->
  <table type="GRIB1" filename="/grib/tables/userlookup.lst"/>  <!--7-->
  <table type="GRIB2" filename="/grib/tables/grib2userparameters" />  <!--8-->
  <bufrtable filename="C:/my/files/lookup.txt" />  <!--9-->
  <grib1Table strict="false"/>  <!--10-->
  <Netcdf4Clibrary>  <!--11-->
     <libraryPath>/usr/local/lib</libraryPath>
     <libraryName>netcdf</libraryName>
     <useForReading>false</useForReading>
  </Netcdf4Clibrary>
</nj22Config>
----
// We're doing a normal numbered list here instead of callout items because item 11 requires a nested list.
// However, callout items do not support complex content: https://github.com/asciidoctor/asciidoctor/issues/1478
1.  Loads an `IOServiceProvider` with the given class name
2.  Loads a `CoordSysBuilderIF` with the given class name, which looks for the given *Convention* attribute value.
3.  Loads a `CoordTransBuilderIF` with the given class name, which looks
for the given *transformName* in the dataset. The type must be _vertical_ or __projection__.
4.  Loads a `FeatureDatasetFactory` with the given class name which open *FeatureDatasets* of the given *featureType*.
5.  Load a <<formats/GribTables#,GRIB-1 parameter table>> (as of version 4.3)
6.  Load a <<formats/GribTables#,GRIB-1 parameter table lookup>> (as of version 4.3)
7.  Load a <<formats/GribTables#,GRIB-1 parameter lookup table>> (versions < 4.3, deprecated)
8.  Load a <<formats/GribTables#,GRIB-2 parameter lookup table>> (versions < 4.3, deprecated)
9.  Load a <<formats/BufrTables#,BUFR table lookup>> file
10. Turn <<formats/GribTables.adoc#strict,strict GRIB1 table handling>> off.
11. Configure how the <<netcdf4Clibrary#,netCDF-4 C library>> is discovered and used.
    ** `libraryPath`: The directory in which the native library is installed.
    ** `libraryName`: The name of the native library. This will be used to locate the proper .DLL, .SO, or .DYLIB file
        within the `libraryPath` directory.
    ** `useForReading`: By default, the native library is only used for writing NetCDF-4 files; a pure-Java layer is
       responsible for reading them. However, if this property is set to true, then it will be used for reading
       NetCDF-4 (and HDF5) files as well.

There are several ways pass the Runtime Configuration XML to the CDM
library. From your application, you can pass a `java.io.InputStream` (or http://www.jdom.org/[JDOM] element) to
`ucar.nc2.util.xml.RuntimeConfigParser`, as in the following examples:

[source,java]
----
  // Example 1: read from file
  StringBuffer errlog = new StringBuffer();
  FileInputStream fis = new FileInputStream( filename);
  ucar.nc2.util.RuntimeConfigParser.read( fis, errlog);
  System.out.println( errlog);

  // Example 2: read from resource
  ClassLoader cl = this.getClassLoader();
  InputStream is = cl.getResourceAsStream("resources/nj22/configFile.xml");
  ucar.nc2.util.RuntimeConfigParser.read( is, errlog);

  // Example 3: extract JDOM element from a larger XML document:
  Document doc;
  SAXBuilder saxBuilder = new SAXBuilder();
  try {
    doc = saxBuilder.build(filename);
  } catch (JDOMException e) {
    throw new IOException(e.getMessage());
  }
  Element root = doc.getRootElement();
  Element elem = root.getChild("nj22Config");
  if (elem != null)
    ucar.nc2.util.RuntimeConfigParser.read( elem, errlog);
----

For example, the ToolsUI application allows you to specify this file on
the command line with the -**nj22Config** parameter:

[source,java]
----
public void main(String[] args) {

  for (int i = 0; i < args.length; i++) {
    if (args[i].equalsIgnoreCase("-nj22Config") && (i < args.length-1)) {
      String runtimeConfig = args[i+1];
      i++;
      try {
        StringBuffer errlog = new StringBuffer();
        FileInputStream fis = new FileInputStream( runtimeConfig);
        ucar.nc2.util.xml.RuntimeConfigParser.read( fis, errlog);
        System.out.println( errlog);

     } catch (IOException ioe) {
       System.out.println( "Error reading "+runtimeConfig+"="+ioe.getMessage());
     }
   }
 }
...
}
----

If none is specified on the command line, it will look for the XML
document in *$USER_HOME/.unidata/nj22Config.xml*.

== Runtime Loading of IOSP using `javax.imageio.spi.ServiceRegistry`

You can create an IOSP and have it discovered at runtime automatically.

1.  Your class must implement `ucar.nc2.iosp.IOServiceProvider`
2.  Create a JAR file with a **services** subdirectory in
the META-INF directory. This directory contains a file called
`ucar.nc2.iosp.IOServiceProvider`, which contains the name(s) of the
implementing class(es). For example, if the JAR file contained a class
named `com.mycompany.MyIOSP`, the JAR file would contain a file named:
+
---------------------------------------------------
 META-INF/services/ucar.nc2.iosp.IOServiceProvider
---------------------------------------------------
+
containing the line:
+
--------------------
com.mycompany.MyIOSP
--------------------
+
See: http://docs.oracle.com/javase/1.4.2/docs/api/javax/imageio/spi/ServiceRegistry.html

(thanks to Tom Kunicki at USGS for this contribution)
