= NcStream Data Row-oriented (version 2)
[[threddsDocs]]

* This documents version 2 of the NcStream Data message, used by CDM/TDS >= 5.0.
* This is the "row oriented" variant.
* Leaving out compression for now.

== Grammar

----
data2Message := MAGIC_DATA2, vlenb, NcStreamProto.DataRow

vlenb := variable length encoded positive integer == length of the following object in bytes
NcStreamProto.DataRow := Data message encoded by protobuf
----

== NcStreamProto.DataRow

----
message DataRow {
  string fullName = 1;
  DataType dataType = 2;
  Section section = 3;
  bool bigend = 4;
  uint32 version = 5;
  bool isVlen = 7;
  uint32 nelems = 9;

  bytes primdata = 10;              // rectangular, primitive array # <1>
  repeated string stringdata = 11;  // string dataType # <2>
  repeated uint32 vlens = 12;       // isVlen true # <3>
  repeated bytes opaquedata = 13;   // opaque dataTypes # <4>
  ArrayStructureRow structdata = 14;// structure/seq dataType # <5>
}
----

=== Arrays and vlen Arrays (not Structures)

<1> *primdata* has `nelems * sizeof(dataType)` bytes, turn into multidim array of primitives with `section` and `bigend`
<2> *stringdata* has `nelems` strings, turn into multidim array of `String` with `section`
<3> *vlens* has `section.size` array lengths; `section` does not include the last (vlen) dimension; data in `primdata`
<4> *opaquedata* has `nelems` `Opaque` objects, turn into multidim array of `Opaque` with `section`
<5> *structdata* has `nelems` `StructureData` objects, turn into multidim array of `StructureData` with `section`

=== Arrays of primitive data

* For all primitive data types, specified by `dataType`, with `isVlen=false.`
* The data is laid out in row-major order in `primdata`.
* The number of elements is `nelems`.
* The shape of the `Array` is specified by `section`.
* Endianness is specified by `bigend`. This is _reader-make-right_.

=== Arrays of string

* For `dataType = STRING`.
* The data is laid out in row-major order in `stringdata`.
* The number of elements is `nelems`.
* The shape of the `Array` is specified by `section`.
* `String` data is always UTF-8 encoded.

=== Arrays of opaque

* For `dataType = OPAQUE`.
* The data is laid out in row-major order in `opaquedata`.
* The number of elements is `nelems`.
* The shape of the Array is specified by `section`.
* `Opaque` data are variable length of bytes, aka blobs.

=== Vlen

Variable-length data can only have a variable length in its innermost (fastest varying) dimension, so it has the form:

----
  dataType varname(d1,d2,di,*);

  where
    d1,d2,di are 0 or more fixed length dimensions; this is the data's "fixed shape".
    * is the last, variable-length dimension.
----

* For `isVlen_ = true`.
* The data is laid out in row-major order in `primdata`, `stringdata`, or `opaquedata`, depending on the `dataType`.
* The total number of elements in the data array is `nelems`.
* The fixed shape of the data is specified by `section`.
* The length of each variable-length array is stored in `vlens`. There will be `shape.size()` of them.
* The sum of the `vlens` is equal to `nelems`.
* see <<../../CDM/VariableLengthData#,vlen data>>

Examples:

. when encoding, the length of each vlen is known, so:
.. `float vlen(*)` will have a known length, so can be encoded the same as a regular array
.. `float vlen(3,7, *)` has 21 variable length arrays, stored in the vlens array
... `primdata` has `nelems * sizeof(dataType)` bytes, turn into dim array of primitives, use vlens to divide into variable length arrays


== Structures

----
message Member {
  string shortName = 1;
  DataType dataType = 2;
  repeated uint32 shape = 3;  // or section?
  bool isVlen = 4;
}

message ArrayStructureRow {
  repeated Member members = 1;
  uint64 nrows = 5;      // number of rows in this message
  uint32 rowLength = 6;  // length in bytes of each row

  bytes fixdata = 10;              // fixed data # <1>
  repeated string stringdata = 11;  // string dataType # <2>
  repeated bytes bytedata = 13;     // opaque dataType and vlens # <3>
  repeated ArrayStructureRow structdata = 14;  // structure/seq dataType # <4>
}
----

<1> `fixdata` has `nrows * rowLength` bytes, which must be parsed based on the `Member` dataTypes.
<2> `stringdata` is a list of `Strings` referenced from `String` datatypes in `fixdata`.
<3> `opaquedata` is a list of byte arrays referenced from `Opaque` datatypes in `fixdata`.
<4> for the `Member`s that are a `Structure` or `Sequence`. May be zero or more.

How to parse `fixdata`:

* For each `Member` with primitive type:
** The number of elements in each row is `shape.size()`.
** No padding
* For `String`, `Opaque`, `Vlen`, and `Structure`, a 4 byte integer is in the `fixdata` row, which is an index into
`stringdata`, `bytedata`, or the nested `ArrayStructureRow`.
* Having replaced the variable length data with 4 byte integers, each row is now the same size.

=== Nested Structures

A nested structure like

----
Structure {
  int fld1
  string fld2(12);

  Structure {
    float fld3;
    long fld4(2,3);
  } inner(99);

  Sequence {
    string fld5;
    byte fld6[10];
    int fld7(2, *);
  } seq;

} outer(123)
----

Has a DataRow message with

----
message DataRow {
  string fullName = "outer"
  DataType dataType = "DataType.STRUCTURE"
  Section section = "0:122"
  bool isVlen = "false"
  uint32 nelems = "123"

  bytes primdata = null;
  repeated string stringdata = null;
  repeated uint32 vlens = null
  repeated bytes opaquedata = null
  ArrayStructureRow structdata = present
}
----

Call this *ArrayStructureRow* `outer`. It has 4 members `fld1`, `fld2`, `inner` and `seq`, like:

----
message ArrayStructureDataRow {
  repeated Members members = size: 4
  uint64 nrows = "123"
  uint32 rowLength = "16"

  bytes fixdata = size: 123 * 16
  repeated string stringdata = size: 123 * 12
  repeated bytes bytedata = null
  repeated ArrayStructureRow structdata = size 2: inner and seq
}
----

The data in `outer.fixdata` will be laid out like this:

There will be 123 rows, each row is 16 bytes long:

[cols=",,,,",options="header",]
|=======================================================================
|Member |bytes | offset | contents | meaning
|fld1 | 4 | 0 | int32 | value of fld1
|fld2 | 4 | 4 | uint32 | index into outer.stringdata
|inner | 4 | 8 | uint32 | row index into inner.arrayStruct
|seq | 4 | 12 | uint32 | row index into seq.arrayStruct
|=======================================================================

The `stringdata` list will have 12 * 123 strings in it. (The 12 comes from the shape of `fld2`, times 123 rows).
In the first row, `outer.fixdata.fld2` will equal 0, in the second row it will equal 12, the third 24, etc.

If there were opaque and vlens in this Structure they would share the `bytedata` list.

The fields in the nested structures hold the data for all the rows. The `inner` Structure has 99 rows for every outer row, so
there will be 123 * 99 rows stored in the `outer.inner` `ArrayStructureRow`, which has 2 fields, `fld3` and `fld4`:

----
message ArrayStructureRow {
  repeated Members members = size: 2
  uint64 nrows = "123 * 99"
  uint32 rowLength = "12"

  bytes fixdata = size: 123 * 99 * 12
  repeated string stringdata = null
  repeated bytes bytedata = null
  repeated ArrayStructureRow structdata = null
}
----

the data is laid out like:

[cols=",,,,",options="header",]
|=======================================================================
|Member |bytes | offset | contents | meaning
|fld3 | 4 | 0 | float | value of fld3
|fld4 | 4 | 4 | int64 | value of fld4
|=======================================================================

Now we can come back to the `outer` ArrayStructureRow to understand the index values of the `inner` field.
In the first row, `outer.fixdata.inner` will equal 0, in the second row it will equal 99, the third 198, etc.
It is naming the row number in the `inner` ArrayStructureRow where `outer.inner` for that row starts. Because inner is
fixed length, we could of course compute this.

Similarly, `outer.fixdata.seq` is the row number in the `seq` `ArrayStructureRow` where `outer.seq` for that row starts.
In this case we don't know the number of rows for each sequence, so this value is very important!
This is the only way that one can find out how long each nested seq is.

Here is what the `seq` `ArrayStructureRow` is like.
Assume for this example that when all of the rows in the 123 nested `seq` are added together, there are 456 of them. So:

----
message ArrayStructureRow {
  repeated Members members = size: 3 ("fld5", "fld6", "fld7")
  uint64 nrows = "456"
  uint32 rowLength = "18"

  bytes fixdata = size: 456 * 18
  repeated string stringdata = size : 456
  repeated bytes bytedata = size : 456 * 2
  repeated ArrayStructureRow structdata = null
}
----

the data is laid out like:

[cols=",,,,",options="header",]
|=======================================================================
|Member |bytes | offset | contents | meaning
|fld5 | 4 | 0 | uint32 | index into seq.stringdata
|fld6 | 10 | 4 | bytes | value of fld6
|fld7 | 4 | 14 | uint32 | index into seq.bytedata
|=======================================================================

Each of the `fld7` variable length arrays are stored in a separate protobuf *bytes* data structure in `bytearray`. There are two of them
for each seq object.
