// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ucar/nc2/iosp/noaa/GhcnmIndex.proto

package ucar.nc2.iosp.noaa;

public final class GhcnmProto {
  private GhcnmProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class StationIndex extends
      com.google.protobuf.GeneratedMessage {
    // Use StationIndex.newBuilder() to construct.
    private StationIndex() {
      initFields();
    }
    private StationIndex(boolean noInit) {}
    
    private static final StationIndex defaultInstance;
    public static StationIndex getDefaultInstance() {
      return defaultInstance;
    }
    
    public StationIndex getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ucar.nc2.iosp.noaa.GhcnmProto.internal_static_ghcnm_StationIndex_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ucar.nc2.iosp.noaa.GhcnmProto.internal_static_ghcnm_StationIndex_fieldAccessorTable;
    }
    
    // required uint64 stnid = 1;
    public static final int STNID_FIELD_NUMBER = 1;
    private boolean hasStnid;
    private long stnid_ = 0L;
    public boolean hasStnid() { return hasStnid; }
    public long getStnid() { return stnid_; }
    
    // required uint64 stnPos = 2;
    public static final int STNPOS_FIELD_NUMBER = 2;
    private boolean hasStnPos;
    private long stnPos_ = 0L;
    public boolean hasStnPos() { return hasStnPos; }
    public long getStnPos() { return stnPos_; }
    
    // required uint64 dataPos = 3;
    public static final int DATAPOS_FIELD_NUMBER = 3;
    private boolean hasDataPos;
    private long dataPos_ = 0L;
    public boolean hasDataPos() { return hasDataPos; }
    public long getDataPos() { return dataPos_; }
    
    // required uint32 dataCount = 4;
    public static final int DATACOUNT_FIELD_NUMBER = 4;
    private boolean hasDataCount;
    private int dataCount_ = 0;
    public boolean hasDataCount() { return hasDataCount; }
    public int getDataCount() { return dataCount_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasStnid) return false;
      if (!hasStnPos) return false;
      if (!hasDataPos) return false;
      if (!hasDataCount) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasStnid()) {
        output.writeUInt64(1, getStnid());
      }
      if (hasStnPos()) {
        output.writeUInt64(2, getStnPos());
      }
      if (hasDataPos()) {
        output.writeUInt64(3, getDataPos());
      }
      if (hasDataCount()) {
        output.writeUInt32(4, getDataCount());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasStnid()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, getStnid());
      }
      if (hasStnPos()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, getStnPos());
      }
      if (hasDataPos()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, getDataPos());
      }
      if (hasDataCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, getDataCount());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndex parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndex parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndex parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndex parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndex parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndex parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndex parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndex parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndex parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndex parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ucar.nc2.iosp.noaa.GhcnmProto.StationIndex prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private ucar.nc2.iosp.noaa.GhcnmProto.StationIndex result;
      
      // Construct using ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new ucar.nc2.iosp.noaa.GhcnmProto.StationIndex();
        return builder;
      }
      
      protected ucar.nc2.iosp.noaa.GhcnmProto.StationIndex internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new ucar.nc2.iosp.noaa.GhcnmProto.StationIndex();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.getDescriptor();
      }
      
      public ucar.nc2.iosp.noaa.GhcnmProto.StationIndex getDefaultInstanceForType() {
        return ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public ucar.nc2.iosp.noaa.GhcnmProto.StationIndex build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private ucar.nc2.iosp.noaa.GhcnmProto.StationIndex buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public ucar.nc2.iosp.noaa.GhcnmProto.StationIndex buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        ucar.nc2.iosp.noaa.GhcnmProto.StationIndex returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ucar.nc2.iosp.noaa.GhcnmProto.StationIndex) {
          return mergeFrom((ucar.nc2.iosp.noaa.GhcnmProto.StationIndex)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ucar.nc2.iosp.noaa.GhcnmProto.StationIndex other) {
        if (other == ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.getDefaultInstance()) return this;
        if (other.hasStnid()) {
          setStnid(other.getStnid());
        }
        if (other.hasStnPos()) {
          setStnPos(other.getStnPos());
        }
        if (other.hasDataPos()) {
          setDataPos(other.getDataPos());
        }
        if (other.hasDataCount()) {
          setDataCount(other.getDataCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setStnid(input.readUInt64());
              break;
            }
            case 16: {
              setStnPos(input.readUInt64());
              break;
            }
            case 24: {
              setDataPos(input.readUInt64());
              break;
            }
            case 32: {
              setDataCount(input.readUInt32());
              break;
            }
          }
        }
      }
      
      
      // required uint64 stnid = 1;
      public boolean hasStnid() {
        return result.hasStnid();
      }
      public long getStnid() {
        return result.getStnid();
      }
      public Builder setStnid(long value) {
        result.hasStnid = true;
        result.stnid_ = value;
        return this;
      }
      public Builder clearStnid() {
        result.hasStnid = false;
        result.stnid_ = 0L;
        return this;
      }
      
      // required uint64 stnPos = 2;
      public boolean hasStnPos() {
        return result.hasStnPos();
      }
      public long getStnPos() {
        return result.getStnPos();
      }
      public Builder setStnPos(long value) {
        result.hasStnPos = true;
        result.stnPos_ = value;
        return this;
      }
      public Builder clearStnPos() {
        result.hasStnPos = false;
        result.stnPos_ = 0L;
        return this;
      }
      
      // required uint64 dataPos = 3;
      public boolean hasDataPos() {
        return result.hasDataPos();
      }
      public long getDataPos() {
        return result.getDataPos();
      }
      public Builder setDataPos(long value) {
        result.hasDataPos = true;
        result.dataPos_ = value;
        return this;
      }
      public Builder clearDataPos() {
        result.hasDataPos = false;
        result.dataPos_ = 0L;
        return this;
      }
      
      // required uint32 dataCount = 4;
      public boolean hasDataCount() {
        return result.hasDataCount();
      }
      public int getDataCount() {
        return result.getDataCount();
      }
      public Builder setDataCount(int value) {
        result.hasDataCount = true;
        result.dataCount_ = value;
        return this;
      }
      public Builder clearDataCount() {
        result.hasDataCount = false;
        result.dataCount_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ghcnm.StationIndex)
    }
    
    static {
      defaultInstance = new StationIndex(true);
      ucar.nc2.iosp.noaa.GhcnmProto.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ghcnm.StationIndex)
  }
  
  public static final class StationIndexList extends
      com.google.protobuf.GeneratedMessage {
    // Use StationIndexList.newBuilder() to construct.
    private StationIndexList() {
      initFields();
    }
    private StationIndexList(boolean noInit) {}
    
    private static final StationIndexList defaultInstance;
    public static StationIndexList getDefaultInstance() {
      return defaultInstance;
    }
    
    public StationIndexList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ucar.nc2.iosp.noaa.GhcnmProto.internal_static_ghcnm_StationIndexList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ucar.nc2.iosp.noaa.GhcnmProto.internal_static_ghcnm_StationIndexList_fieldAccessorTable;
    }
    
    // repeated .ghcnm.StationIndex list = 1;
    public static final int LIST_FIELD_NUMBER = 1;
    private java.util.List<ucar.nc2.iosp.noaa.GhcnmProto.StationIndex> list_ =
      java.util.Collections.emptyList();
    public java.util.List<ucar.nc2.iosp.noaa.GhcnmProto.StationIndex> getListList() {
      return list_;
    }
    public int getListCount() { return list_.size(); }
    public ucar.nc2.iosp.noaa.GhcnmProto.StationIndex getList(int index) {
      return list_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      for (ucar.nc2.iosp.noaa.GhcnmProto.StationIndex element : getListList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (ucar.nc2.iosp.noaa.GhcnmProto.StationIndex element : getListList()) {
        output.writeMessage(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (ucar.nc2.iosp.noaa.GhcnmProto.StationIndex element : getListList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList result;
      
      // Construct using ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList();
        return builder;
      }
      
      protected ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList.getDescriptor();
      }
      
      public ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList getDefaultInstanceForType() {
        return ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.list_ != java.util.Collections.EMPTY_LIST) {
          result.list_ =
            java.util.Collections.unmodifiableList(result.list_);
        }
        ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList) {
          return mergeFrom((ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList other) {
        if (other == ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList.getDefaultInstance()) return this;
        if (!other.list_.isEmpty()) {
          if (result.list_.isEmpty()) {
            result.list_ = new java.util.ArrayList<ucar.nc2.iosp.noaa.GhcnmProto.StationIndex>();
          }
          result.list_.addAll(other.list_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.Builder subBuilder = ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addList(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .ghcnm.StationIndex list = 1;
      public java.util.List<ucar.nc2.iosp.noaa.GhcnmProto.StationIndex> getListList() {
        return java.util.Collections.unmodifiableList(result.list_);
      }
      public int getListCount() {
        return result.getListCount();
      }
      public ucar.nc2.iosp.noaa.GhcnmProto.StationIndex getList(int index) {
        return result.getList(index);
      }
      public Builder setList(int index, ucar.nc2.iosp.noaa.GhcnmProto.StationIndex value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.list_.set(index, value);
        return this;
      }
      public Builder setList(int index, ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.Builder builderForValue) {
        result.list_.set(index, builderForValue.build());
        return this;
      }
      public Builder addList(ucar.nc2.iosp.noaa.GhcnmProto.StationIndex value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.list_.isEmpty()) {
          result.list_ = new java.util.ArrayList<ucar.nc2.iosp.noaa.GhcnmProto.StationIndex>();
        }
        result.list_.add(value);
        return this;
      }
      public Builder addList(ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.Builder builderForValue) {
        if (result.list_.isEmpty()) {
          result.list_ = new java.util.ArrayList<ucar.nc2.iosp.noaa.GhcnmProto.StationIndex>();
        }
        result.list_.add(builderForValue.build());
        return this;
      }
      public Builder addAllList(
          java.lang.Iterable<? extends ucar.nc2.iosp.noaa.GhcnmProto.StationIndex> values) {
        if (result.list_.isEmpty()) {
          result.list_ = new java.util.ArrayList<ucar.nc2.iosp.noaa.GhcnmProto.StationIndex>();
        }
        super.addAll(values, result.list_);
        return this;
      }
      public Builder clearList() {
        result.list_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ghcnm.StationIndexList)
    }
    
    static {
      defaultInstance = new StationIndexList(true);
      ucar.nc2.iosp.noaa.GhcnmProto.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ghcnm.StationIndexList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ghcnm_StationIndex_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ghcnm_StationIndex_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ghcnm_StationIndexList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ghcnm_StationIndexList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#ucar/nc2/iosp/noaa/GhcnmIndex.proto\022\005g" +
      "hcnm\"Q\n\014StationIndex\022\r\n\005stnid\030\001 \002(\004\022\016\n\006s" +
      "tnPos\030\002 \002(\004\022\017\n\007dataPos\030\003 \002(\004\022\021\n\tdataCoun" +
      "t\030\004 \002(\r\"5\n\020StationIndexList\022!\n\004list\030\001 \003(" +
      "\0132\023.ghcnm.StationIndexB \n\022ucar.nc2.iosp." +
      "noaaB\nGhcnmProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ghcnm_StationIndex_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ghcnm_StationIndex_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ghcnm_StationIndex_descriptor,
              new java.lang.String[] { "Stnid", "StnPos", "DataPos", "DataCount", },
              ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.class,
              ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.Builder.class);
          internal_static_ghcnm_StationIndexList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ghcnm_StationIndexList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ghcnm_StationIndexList_descriptor,
              new java.lang.String[] { "List", },
              ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList.class,
              ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
