
# expect/tcl code to test the das scanner
# jhrg
#
# $Log: scanner.1.exp,v $
# Revision 1.1  2003/08/11 20:50:09  ndp
# Initial revision
#
# Revision 1.3  2002/05/31 17:09:18  jimg
# Updated tests from C++. This includes some changes for the Java code.
#
# Revision 1.1  1996/07/16 16:54:31  jimg
# Added.
#
# Revision 1.3  1996/05/14 15:40:41  jimg
# These changes have already been checked in once before. However, I
# corrupted the source repository and restored it from a 5/9/96 backup
# tape. The previous version's log entry should cover the changes.
#
# Revision 1.2  1995/10/23  23:47:02  jimg
# Modified...
#
# Revision 1.1  1995/02/16  15:34:43  jimg
# Added these tests. See comments in files in parent directory.
#
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_name' is the name of the das input file for this test.

set test_name scanner.1

set prompt "das-test:"
set timeout 2

das-test_start s

expect {
    -re "^$prompt $" { 
	pass "$test_name" 
    }
    timeout { 
	send_user "Timeout\n"
	fail "$test_name" 
    }
}

das-test_exit


