# expect/tcl code to test the das parser and scanner
# jhrg
#
# $Log: test.20.exp,v $
# Revision 1.1  2003/08/11 20:50:10  ndp
# Initial revision
#
# Revision 1.2  2003/03/05 00:02:48  ndp
# *** empty log message ***
#
# Revision 1.1  2002/05/31 17:16:22  jimg
# Added
#
# Revision 1.8  2001/06/15 23:49:05  jimg
# Merged with release-3-2-4.
#
# Revision 1.7.4.2  2001/06/06 06:40:57  jimg
# *** empty log message ***
#
# Revision 1.7.4.1  2001/06/06 04:12:30  jimg
# Updated for the new DAS error reporting scheme (Some errors are reported
# in the DAS itself).
#
# Revision 1.7  2000/09/22 02:52:59  jimg
# Fixes to the tests to recognize some of the new error messages. Also,
# the test drivers were modified to catch the exceptions now thrown by
# some of the parsers.
#
# Revision 1.6  2000/06/16 18:15:01  jimg
# Merged with 3.1.7
#
# Revision 1.4.6.2  2000/06/15 02:24:57  jimg
# Fixed the tests: problems with PATH, etc. broke the tests on my new machine
#
# Revision 1.5  2000/04/07 00:20:36  jimg
# Fixed expresion tests.
#
# Revision 1.4.6.1  1999/10/19 16:48:40  jimg
# Version 3.1.2
#
# Revision 1.4  1999/04/29 00:05:39  jimg
# *** empty log message ***
#
# Revision 1.6  1997/05/13 23:29:18  jimg
# *** empty log message ***
#
# Revision 1.5  1997/03/27 18:19:58  jimg
# Update for version 2.13
#
# Revision 1.4  1996/11/13 19:23:44  jimg
# *** empty log message ***
#
# Revision 1.3  1996/08/12 22:22:18  jimg
# Changed for the new error message text from the parser.
#
# Revision 1.2  1996/04/05 22:00:13  jimg
# Misc Changes for release 2.0.1 of the core software - for developers.
#
# Revision 1.1  1995/02/16  15:34:52  jimg
# Added these tests. See comments in files in parent directory.
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_name' is the name of the das input file for this test.

set test_name test.20

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

#  set test_out "Attributes {
#      test {
#          Int32 x 70000;
#          test_dods_errors {
#              Int16 y 80000;
#              String y_explanation \"`80000' is not an Int16 value.\";
#          }
#      }
#  }"

set test_out "Attributes {
    test {
        Int32 x 70000;
        test_dods_errors {
            Int16 y 80000;
            String y_explanation \"`80000' is not an Int16 value.\";
        }
    }
}"

das-test_start p $srcdir/$test_name


if {$verbose >= 1} {
    send_user "\n----- Expected output -----\n"
    send_user "$test_out"
    send_user "\n---------------------------\n";
}




if ![string compare $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}
