Attributes {
    SDS_None {
        Int32 _FillValue 0;
    }
    SDS_Deflate {
        Int32 _FillValue 0;
    }
    SDS_Skip_Huffman {
        Int32 _FillValue 0;
    }
    SDS_RLE_dim_0 {
        String name "fakeDim2";
    }
    SDS_RLE_dim_1 {
        String name "fakeDim3";
    }
    SDS_Deflate_dim_0 {
        String name "fakeDim8";
    }
    SDS_Deflate_dim_1 {
        String name "fakeDim9";
    }
    SDS_Skip_Huffman_dim_0 {
        String name "fakeDim6";
    }
    SDS_Skip_Huffman_dim_1 {
        String name "fakeDim7";
    }
    SDS_N%2dbit_dim_0 {
        String name "fakeDim4";
    }
    SDS_N%2dbit_dim_1 {
        String name "fakeDim5";
    }
    SDS_None_dim_0 {
        String name "fakeDim0";
    }
    SDS_None_dim_1 {
        String name "fakeDim1";
    }
    SDS_RLE {
        Int32 _FillValue 0;
    }
    SDS_N%2dbit {
        Int32 _FillValue 0;
    }
}
