Attributes {
    SDS_DFNT_UINT8_dim_0 {
        String name "fakeDim5";
    }
    SDS_DFNT_FLOAT32_dim_0 {
        String name "fakeDim6";
    }
    SDS_DFNT_INT16_dim_0 {
        String name "fakeDim2";
    }
    SDS_DFNT_INT32_dim_0 {
        String name "fakeDim0";
    }
    SDS_DFNT_UINT16_dim_0 {
        String name "fakeDim3";
    }
    SDS_DFNT_FLOAT64_dim_0 {
        String name "fakeDim7";
    }
    SDS_DFNT_INT8_dim_0 {
        String name "fakeDim4";
    }
    SDS_DFNT_UCHAR8_dim_0 {
        String name "fakeDim9";
    }
    SDS_DFNT_UINT32_dim_0 {
        String name "fakeDim1";
    }
    SDS_DFNT_CHAR8_dim_0 {
        String name "fakeDim8";
    }
}
