Attributes {
    Vdata_DFNT_UINT8 {
        Byte Attr_DFNT_UINT8 0, 1, 255;
    }
    Vdata_DFNT_FLOAT32 {
        Float64 Attr_DFNT_FLOAT32 0, 1, -1, 3.40282e+38, 1.4013e-45, -3.40282e+38, -1.4013e-45;
    }
    Vdata_DFNT_INT32 {
        Int32 Attr_DFNT_INT32 0, 1, -1, 2147483647, -2147483648;
    }
    Vdata_DFNT_CHAR8 {
        String Attr_DFNT_CHAR8 "\000\001\377\177\200";
    }
    Vdata_DFNT_UINT32 {
        UInt32 Attr_DFNT_UINT32 0, 1, 4294967295;
    }
    Vdata_DFNT_INT16 {
        Int32 Attr_DFNT_INT16 0, 1, -1, 32767, -32768;
    }
    Vdata_DFNT_INT8 {
        Int32 Attr_DFNT_INT8 0, 1, -1, 127, -128;
    }
    Vdata_DFNT_UINT16 {
        UInt32 Attr_DFNT_UINT16 0, 1, 65535;
    }
    Vdata_DFNT_FLOAT64 {
        Float64 Attr_DFNT_FLOAT64 0, 1, -1, 1.79769e+308, 4.94066e-324, -1.79769e+308, -4.94066e-324;
    }
    Vdata_DFNT_UCHAR8 {
        String Attr_DFNT_UCHAR8 "\000\001\377";
    }
}
