Attributes {
    SDS_DFNT_UINT8_dim_0 {
        String name "Axis_DFNT_UINT8";
    }
    SDS_DFNT_INT32 {
        Int32 valid_range -2147483648, 2147483647;
        Int32 SDS_ATTR_DFNT_INT32 0, 1, -1, 2147483647, -2147483648;
    }
    SDS_DFNT_FLOAT64 {
        Float64 valid_range -1.79769e+308, 1.79769e+308;
        Float64 SDS_ATTR_DFNT_FLOAT64 0, 1, -1, 1.79769e+308, 4.94066e-324, -1.79769e+308, -4.94066e-324;
    }
    SDS_DFNT_UINT32 {
        UInt32 valid_range 0, 4294967295;
        UInt32 SDS_ATTR_DFNT_UINT32 0, 1, 4294967295;
    }
    HDF_GLOBAL {
        Int32 GLOBAL_ATTR_DFNT_INT32 0, 1, -1, 2147483647, -2147483648;
        UInt32 GLOBAL_ATTR_DFNT_UINT32 0, 1, 4294967295;
        Int32 GLOBAL_ATTR_DFNT_INT16 0, 1, -1, 32767, -32768;
        UInt32 GLOBAL_ATTR_DFNT_UINT16 0, 1, 65535;
        Int32 GLOBAL_ATTR_DFNT_INT8 0, 1, -1, 127, -128;
        Byte GLOBAL_ATTR_DFNT_UINT8 0, 1, 255;
        Float64 GLOBAL_ATTR_DFNT_FLOAT32 0, 1, -1, 3.40282e+38, 1.4013e-45, -3.40282e+38, -1.4013e-45;
        Float64 GLOBAL_ATTR_DFNT_FLOAT64 0, 1, -1, 1.79769e+308, 4.94066e-324, -1.79769e+308, -4.94066e-324;
        String GLOBAL_ATTR_DFNT_CHAR8 "\000\001\377\177\200";
        String GLOBAL_ATTR_DFNT_UCHAR8 "\000";
    }
    SDS_DFNT_UINT8 {
        Byte valid_range 0, 255;
        Byte SDS_ATTR_DFNT_UINT8 0, 1, 255;
    }
    SDS_DFNT_FLOAT32_dim_0 {
        String name "Axis_DFNT_FLOAT32";
    }
    SDS_DFNT_INT16_dim_0 {
        String name "Axis_DFNT_INT16";
    }
    SDS_DFNT_INT32_dim_0 {
        String name "Axis_DFNT_INT32";
    }
    SDS_DFNT_FLOAT32 {
        Float64 valid_range -3.40282e+38, 3.40282e+38;
        Float64 SDS_ATTR_DFNT_FLOAT32 0, 1, -1, 3.40282e+38, 1.4013e-45, -3.40282e+38, -1.4013e-45;
    }
    SDS_DFNT_CHAR8 {
        String valid_range "\200\177";
        String SDS_ATTR_DFNT_CHAR8 "\000\001\377\177\200";
    }
    SDS_DFNT_UINT16_dim_0 {
        String name "Axis_DFNT_UINT16";
    }
    SDS_DFNT_FLOAT64_dim_0 {
        String name "Axis_DFNT_FLOAT64";
    }
    SDS_DFNT_INT8_dim_0 {
        String name "Axis_DFNT_INT8";
    }
    SDS_DFNT_INT16 {
        Int32 valid_range -32768, 32767;
        Int32 SDS_ATTR_DFNT_INT16 0, 1, -1, 32767, -32768;
    }
    SDS_DFNT_UCHAR8 {
        String valid_range "\000";
        String SDS_ATTR_DFNT_UCHAR8 "\000";
    }
    SDS_DFNT_UCHAR8_dim_0 {
        String name "Axis_DFNT_UCHAR8";
    }
    SDS_DFNT_INT8 {
        Int32 valid_range -128, 127;
        Int32 SDS_ATTR_DFNT_INT8 0, 1, -1, 127, -128;
    }
    SDS_DFNT_UINT16 {
        UInt32 valid_range 0, 65535;
        UInt32 SDS_ATTR_DFNT_UINT16 0, 1, 65535;
    }
    SDS_DFNT_UINT32_dim_0 {
        String name "Axis_DFNT_UINT32";
    }
    SDS_DFNT_CHAR8_dim_0 {
        String name "Axis_DFNT_CHAR8";
    }
}
