:source-highlighter: coderay
[[threddsDocs]]

:stylesheet: ../../tds_adoc.css
:linkcss:

=== CdmrFeature Coverage Subsetting Parameters

[width="100%",cols="20%,10%,30%,30%,10%",options="header",]
|=====================================================================================================================================================
|Parameter Name |Required  |Description / possible values                               |Constraints                                   |default
|*var*            |yes       |Name(s) of variables (comma separated, no blanks), or _all_.  |Variables must be in the dataset description. |
|*north, south, east, west* |no |lat/lon bounding box, units of degrees_east, degrees_north | south < north, west < east; if crossing 180 meridian, use east boundary > 180  |
|*minx, miny, maxx, maxy* |no |Projection bounding box, in projection coordinate units (km) |min < max; use only for gridded data on a projection |
|*horizStride* |no |Take only every nth point (both x and y) | |1
|*time* |no | Datetime as a link:{w3cDate}[W3C date] or _present_ (the time slice closest to the requested time is returned) or _all_ (all times are returned) |Must be a time within the dataset time range |_present_
|*time_start, time_end, time_duration* |no |Used to specify a time range (two of these must be present). Datetime may be a link:#W3Cdate[W3C date] or _present_. Duration is a udunit time or link:{w3cDuration}[W3C time duration] |The requested time range must intersect the dataset time range |
|*timeStride*|no |Take every nth time in the available series |Used with time_range or _all_ | 1
|*runtime*   |no |Datetime as a link:{w3cDate}[W3C date] or _latest_ (restrict to that runtime) or _all_. |Used only if there is an independent runtime coordinate. | _latest_
|*timeOffset*|no |Time as an offset from the runtime coordinate, or _first_ or _all_ |Used only for 2D time coordinate, units same as the dataset | all
|*vertCoord* |no |Restrict to specified vertical level coordinate value. |Used only if there is a vertical coordinate. |all
|*ensCoord*  |no |Restrict to specified ensemble coordinate. |Used only if there is an ensemble coordinate. |all
|=====================================================================================================================================================

Variable subsetting::

* You *must* specify a list of valid variable names, or "_all_".
* variable names are case-sensitive and must be URL encoded. Be careful not to URL encode twice.

Horizontal spatial subsetting::

* You may specify a lat/lon bounding box or, if the dataset is on a projection, a projection bounding box. If none, return the entire horizontal grid.
* Lat/lon bounds start at the west value and includes the area going east, until the east value.
* Best practice is to make east > west longitude, by adding 360 to it if needed.

Vertical spatial subsetting::

* You may specify a vertical coordinate. The closest level is returned. If not specified, all vertical levels are returned.

Temporal subsetting::

* These rules apply to non-2D time datasets.
* You may specify a time range, or a time point. If both, only the time point is used. If neither, use the present time.
* A time range (__time_start, time_end, time_duration__) will request all times that intersect the range (__timeStride__ is used if present).
* Two of _time_start, time_end, time_duration_ must be present to define a valid time range. _time_start, time_end_ may equal _present_.
. _time_start, time_end_ : specified range
. _time_start, time_duration_ : starting from _time_start_ until _time_start + time_duration_
. _time_end, time_duration_ : starting from _time_end - time_duration_ until _time_end_
* A time point will request the time that is closest to that value.
* If you set __time="all"__, then all times are returned (__timeStride__ is used if present). All other time parameters are ignored.
* time duration: 1) udunit time unit string or 2) link:{w3cDuration}[W3C time duration]
* datetime: link:{w3cDate}[W3C date] or _present_
* The dataset determines what Calendar is used, so you must use that calendar. There can only be one calendar per dataset.
* If no time range or time point, a timeOffset can be used to specify the time point.

2D Time subsetting::

* A 2D time dataset will have CoverageType set to _FMRC_.
* You may specify a *runtime* with a date, _latest_ or _all_. Default is _latest_.
* You may specify a *timeOffset* with a numeric value, _first_, or _all_. A timeOffset value is a duration of time, it is added
  to the runtime to give the requested time. Its units must be the same as the dataset. Default is _all_.
* *Time* parameters may be used only used if timeOffset is not. There are 2 cases:
. Runtime is set to a specific value or _latest_ (not _all_). Time parameters (point or range) can then be used.
. Runtime to set to _all_. Time point (date, or _present_) only can then be used.
* If no runtime, timeOffset, or time parameters are set, then return all times for latest runtime.
* Special cases:
. Set specific runtime = _constant runtime dataset_
. Set specific timeOffset, set runTime to _all_ = _constant offset dataset_
. Set specific time, set runTime to _all_ = _constant forecast dataset_

Interval coordinate::

* If the coordinate is an _interval coordinate_ (common for vertical or time coordinates), it has a lower and upper bound, eg (2.0-10.0 m) or (12-24 hours).
* The request is still made with a single value. The interval that contains the requested value is used.
* If the requested value is contained in more than one interval (happens with mixed interval time coordinates),
the midpoint of the interval is calculated, and the closest midpoint to the requested value is used.
