echo "Trying for a clean exit!"

#
# try killing all java processes owned by tomcat
#
# This is a clean kill and allows things to finish,
# if, for example, the TDM is indexing a file.
#
pkill -u tomcat java

echo "Done!"

exit
