:source-highlighter: coderay
[[threddsDocs]]


= Grib Collections

A GRIB Collection is a collection of files that have GRIB records in
them. Each file will have a grib index (__gbx9__) file generated for it.
Once generated, gbx9 files never have to be redone.

Each logical collection has a CDM index (__ncx2__) file. All the records
for a single runtime comprise a logical collection, called a RC.

== case 1. \{collection} has single runtime

----------------------------------------------------------------------------------------------------
<dataset name="GRIB Collection Example for tutorial (single runtime)" serviceName="gribServices" >
 <featureCollection name="Ismoro Single Runtime" featureType="GRIB1" harvest="true" path="Grib/srt">
  <collection name="collsrt" spec="/machine/tds/data/grib/ecmwf/.*grib$" />
  <update startup="test" />
 </featureCollection>
</dataset>
----------------------------------------------------------------------------------------------------

Single RC dataset, single CDM index file. One time dimension. May have
multiple groups (horizontal domains).

== case 2. \{collection} has multiple runtimes

----------------------------------------------------------------------------------------------------
<dataset name="GRIB Collection Example for tutorial (multiple runtimes)" serviceName="gribServices">
 <featureCollection name="GFS multiple runtime" featureType="GRIB2" harvest="true" path="Grib/mrt">
  <collection name="collmrt" spec="/machine/tds/data/grib/gfsmrt/.*grib2$" />
  <update startup="test" />
 </featureCollection>
</dataset>
----------------------------------------------------------------------------------------------------

One RC dataset for each runtime, plus PofGC ``collection dataset'' with
both runtime and time dimensions.

== case 3. \{collection} has multiple runtimes, one per file: use
_file_ partition

-------------------------------------------------------------------------------------------------
<dataset name="GRIB Collection Example for tutorial (file partition)" serviceName="gribServices">
 <featureCollection name="GFS file partition" featureType="GRIB2" harvest="true" path="Grib/fp">
  <collection name="collfp" spec="/machine/tds/data/grib/gfsfp/.*grib2$" timePartition="file"/>
  <update startup="test" />
 </featureCollection>
</dataset>
-------------------------------------------------------------------------------------------------

One RC dataset for each runtime, plus PofGC ``collection dataset'' with
both runtime and time dimensions. More efficient indexing.

== case 4. \{collection} has multiple runtimes, time partitioned by
directory: use _directory_ partition

-------------------------------------------------------------------------------------------------------
<dataset name="GRIB Collection Example for tutorial (directory partition)" serviceName="gribServices">
  <featureCollection name="GFS file partition" featureType="GRIB1" harvest="true" path="Grib/dp">
    <collection name="colldp" spec="/machine/tds/data/grib/rfc/**/.*grib1$" timePartition="directory"/>
    <update startup="test" />
  </featureCollection>
</dataset>
-------------------------------------------------------------------------------------------------------

One RC dataset for each runtime, plus PofGC or PofP ``collection
dataset'' for each directory in the tree. Scales to large collections.

== case 5. \{collection} has multiple runtimes, one per file, time
partitioned by directory: use _file_ partition

One RC dataset for each runtime, plus PofGC or PofP ``collection
dataset'' for each directory in the tree. Scales to large collections.
More efficient indexing.

== Summary

\{collection} -> \{runTime} -> \{Group} : a RC is a single runtime with
1 or more groups (GDS), has a single index (ncx2) file.

PofGC = \{RC}

PofP = \{PofGC}
