:source-highlighter: coderay
[[threddsDocs]]

= Using Structures in NetCDF-3 files

_John Caron_

_last changed: Jun 04, 2005_

* link:#Station[Using Structures for Station Data]
* link:#Sounding[Using Nested Structures for Sounding Data]
* link:#Trajectory[Using Structures for Trajectory Data]

'''''

== Structures and Record variables

A _*Structure*_ is a NetCDF Variable that contains other Variables, like
a *struct* in C. All of the data in a Structure are stored together on
disk, so that it should be efficient to read all the data in a Structure
in a single read. Structures are a new part of NetCDF, introduced in the
http://www.unidata.ucar.edu/software/netcdf-java/index.html[NetCDF-Java]
library, version 2.2 as part of the Common Data Model, and will also be
implemented in
http://www.unidata.ucar.edu/software/netcdf/netcdf-4/index.html[NetCDF-4].

In the NetCDF version 3 data model, _*Record variables*_ are ones that
use the *unlimited dimension* (also known as the **record dimension**),
and these are laid out on disk differently than non-record variables.
All of the data for one non-record variable is stored contiguously on
disk. Record variables, in contrast, are divided up into **records**,
and each record contains the data for all record variables for the ith
record dimension index. You can append an unlimited number of records to
a NetCDF file.

Since data for Record variables is stored contiguously on disk in this
manner, we can think of the records as a Structure containing the Record
variables. Our motivation is to efficiently access all of the data in
the Record variables for some record, ie use a single read to fetch the
ith record. The usefulness of this obviously depends on your data access
patterns. If the dominant access pattern is to read all the data for one
Variable, then it will be more efficient to store that data
continuously, ie make it a non-record Variable. If the data access
pattern is to iterator over (for example) time, and read all the data
for all Variables for each time step, then using Record variables will
be more efficient. Efficiency differences can easily be an order of
magnitude for large files.

Another reason to use Record variables is to take advantage of the
ability to append an unlimited number of records. At some cost in
complexity, this allows us to create variable length arrays, and
collections of variable length arrays, as is shown below.

 

== Using Structures for Station Data

=== CDM Station Data

If you have the full CDM / NetCDF4 data model, here’s a way to express
station data, using nested Structures:

----------------------------------------------------
netcdf C:/data/station.nc {

 dimensions:
   nstations = 137;


 variables:

   Structure {
    char id(8);
    char description(40);
    float latitude;
        :units = "degrees_north";
    float longitude;
        :units = "degrees_east";
    int elevation;
        :units = "meters";
      :long_name = "meters above msl";
      :positive = "up";
    int numReports;

    Structure {
      int time_observation;
        :units = "seconds since 1970-01-01 00 UTC";
      float obs_data1 ;
      float obs_data2(11);
      int obs_data3;
      int obs_data4(4);
      String obs_data5;
      ...
    } stationObs(*);

  } station( nstations);
}
----------------------------------------------------

This describes an array of *station* Structures, each of which has an
**id, description, latitude, longitude, and elevation**, as well as a
nested, variable length array of *stationObs* Structures.

The (*) means that each station can have a different length array of
stationObs structures.

=== NetCDF-3 Station data

We can get the same functionality in netCDF-3 by making use of the
record (unlimited) dimension to create a 1D array of structures. Each
variable using the record dimension can be thought of as being a member
of that structure. The structures are indexed by the record dimension.

The actual netCDF-3 CDL would look like:

--------------------------------------------------
netcdf C:/data/station.nc {

 dimensions:
 station = 137;
   record = UNLIMITED;
   id_len = 8;
   location_len = 40;
   od2_len = 11;
   od4_len = 4;

 variables:

    char id(station, id_len);
    char location(station, location_len);
    float latitude(station);
    float longitude(station);
    int elevation(station);
    int firstStationObs(station);
    int numReports(station);

    int time_observation(record);
      :units = "seconds since 1970-01-01 00 UTC";
    int nextStationObs(record);
    float obs_data1(record) ;
    float obs_data2(record, od2_len);
    int obs_data3(record);
    int obs_data4(record, od4_len);
    String obs_data5(record);
    ...
}
--------------------------------------------------

Notice that the station data all uses the dimension **_station_**, and
the stationObs data all uses the unlimited dimension **_record_**. The
*_firstStationObs_* and *_lastStationObs_* creates a linked list of
stationObs for each station. Therefore we can get a list of all the
stationObs for a station efficiently, but there’s no efficient
subsetting of that list.

(Note that in the CDM, we were using anonymous dimensions for some of
the dimensions, but in netCDF-3 we have to declare all dimensions as
shared)

(With the NetCDF-Java 2.2 library (aka nj22), you can open the file to
use record structures by calling
*NetcdfFile.setUseRecordStructure(true)* and use
*Structure.readStructure(int elem)* to efficiently read one structure at
a time).

 

== Using Nested Structures for Sounding Data

=== CDM Station/Sounding Data

Now lets add the complication that each stationObs has a variable length
sounding. In CDM:

------------------------------------------------------
netcdf C:/data/station.nc {

 dimensions:
   nstations = 137;


 variables:

   Structure {
    char id(8);
    char location(40);
    float latitude;
    float longitude;
    int elevation;
    int numReports;

    Structure {
      int time_observation;
          :units = "seconds since 1970-01-01 00 UTC";
      float obs_data1 ;
      float obs_data2(11);
      ...

      Structure {
        int depth;
            :units = "m";
        int obs_data3;
        int obs_data4(4);
        String obs_data5;
          ...
      } sounding(*)

    } stationObs(*);

  } station( nstations);
}
------------------------------------------------------

=== NetCDF-3 Station/Sounding Data

To express this in the netCDF-3 model, use the same technique as before,
using a dimension to associate the variables in each structure, and
using linked lists to associate the stationObs with the stations, and
the soundings with the stationObs.

-------------------------------------------------
netcdf C:/data/station.nc {

 dimensions:
 station = 137;
  stationObs = 4700;
 record = UNLIMITED;
   id_len = 8;
   location_len = 40;
   od2_len = 11;
   od4_len = 4;

 variables:
   char id(station, id_len);
   char location(station, location_len);
   float latitude(station);
   float longitude(station);
   int elevation(station);
   int firstStationObs(station);
   int numReports(station);

   int time_observation(stationObs);
     :units = "seconds since 1970-01-01 00 UTC";
   int nextStationObs(stationObs);
   float obs_data1(stationObs) ;
   float obs_data2(stationObs, od2_len);
   String obs_data5(stationObs);
   int firstSounding(stationObs);
   ...

   float depth(record);
   int nextSounding(record);
   int obs_data3(record);
   int obs_data4(record, od4_len);
   ...
}
-------------------------------------------------

Since we only have one unlimited dimension, we use it for the sounding
structures. That means we need to determine the number of stationObs in
advance, which may or may not be easy to do. NetCDF-4 would eliminate
that need.

This allows us to compactly store the data. Again, we can efficiently
get a list of all the stationObs for a station, and all the soundings
for a stationObs, but other kinds of subsetting is not efficient.
NetCDF-4 would not add anything more to that.

Also, a client needs to understand the above structure to make efficient
use of it. The NetCDF-Java 2.2 library is adding additional APIs that
would understand the above schema, but you would have to be a Java
client to use it.

(Using *NetcdfFile.setUseRecordStructure(true)* as described above would
make the soundings into a structure, but not the stationObs. This
reflects the actual layout of data in the file, rather than the logical
structure we create by assiciating all variables that use a dimension).

 

== Using Structures for Trajectory Data

While we’re at it, heres one way to store trajectory data in netCDF-3
files. We assume there are a number of different trajectories in the
file. Each trajectory is a linked list of record structures, as before.
Each record consists of various measurements at a given time and
location.

-------------------------------------------------
netcdf C:/data/trajectory.nc {

 dimensions:
 trajectory = 11;
 record = UNLIMITED;

 variables:
   int firstObs(trajectory);
   int numObs(trajectory); // not strictly needed

   int nextObs(record);
   int time_observation(record);
     :units = "seconds since 1970-01-01 00 UTC";
   float latitude(record);
   float longitude(record);
   int depth(record);

   float obs_data1(record);
   int obs_data2(record);
   int obs_data3(record);
   ...
}
-------------------------------------------------

The likely read access pattern is to access all the data for each
trajectory in turn. Then the best storage strategy would be to store the
linked list in contiguous records.
