:source-highlighter: coderay
[[threddsDocs]]

= CDM nested table notation for DSG

*_CDM nested table notation_* expresses the data structures for point features
in a way that reflects the data layout on disk, as well as the
relationship of index space to coordinate space, which we call the
_connectedness_ of the feature type. The following are the CDM table
notation rules, which we explain further in the examples below.

* A _feature_ is represented as a structure.
* A _table_ is a collection of structures of the same type. The size of
the table may be fixed or variable length.
* A _feature type_ is represented as nested tables of specific form.
* Both _coordinates_ and _data variables_ can be at any level of the
nesting.
* A coordinate in an inner table is connected; a coordinate in the
outermost table is unconnected.
* A constant coordinate can be factored out to the top level. This is
logically _joined_ to a nested table with the same dimension.
* A _feature collection_ is an unconnected collection of a specific
feature type.

== Flat Tables

=== CDL notation:

----------------------
dimensions:
  sample = 300;
variables:
  float lat(sample);
  float lon(sample);
  float z(sample);
  float time(sample);
  float data1(sample);
  float data2(sample);
----------------------

=== CDM Structure notation:

Variables with a common outer dimension can be grouped into a
__structure__:

----------------
dimensions:
  sample = 300;
variables:
 structure {
   float lat;
   float lon;
   float z;
   float time;
   float data1;
   float data2;
 } obs(sample); 
----------------

Both the netCDF-4 file format and the NetCDF-Java CDM library support
structure data types.

=== CDM Table notation:

---------------------
dimensions:
  sample = 300;
Table {
   lat, lon, z, time;
   data1, data2, ...
} obs(sample); 
---------------------

=== SQL notation:

---------------------------------------------
CREATE TABLE obs  (
  lat float,  lon float, z float, time float,
  data1 float, data2 float, ...
)  
---------------------------------------------

=== Data rows:

[cols=",,,,,",options="header",]
|================================================
|lat |lon |z |time |data1 |data2
|23.2 |-120.5 |30 |2009-07-22 02:10:00Z |280.9 |7
|24.6 |-132.9 |30 |2009-07-22 02:10:20Z |281.0 |4
|================================================

== Nested Tables

=== CDL:

-----------------------------
dimensions:
  station = 15;
  time = 20;
variables:
  float lat(station);
  float lon(station);
  float z(station);
  float time(station, time);
  float data1(station, time);
  float data2(station, time);
-----------------------------

=== CDM Nested Structure:

---------------------
dimensions:
  station = 15;
  time = 20;
variables:
 structure {
   float lat;
   float lon;
   float z;
   structure {
     float time;
     float data1;
     float data2;
   } obs(time);
 } station(station); 
---------------------

=== CDM Nested Table:

----------------------
dimensions:
  station = 15;
  time = 20;
Table {
   lat, lon, z;
   Table {
     time;
     data1, data2, ...
   } obs(time); 
} station(station); 
----------------------

=== SQL notation:

------------------------------------------------------------------------------
CREATE TABLE station  (
  lat float,  lon float, z float,
  station_id int
) 
CREATE TABLE obs  (
  time float,
  data1 float, data2 float
  station_id int
)
CREATE INDEX obs_station_index  ON obs (station_id)    
SELECT * FROM station  INNER JOIN obs ON station.station_id = obs.station_id  
------------------------------------------------------------------------------

=== Data rows:

[cols=",,,,,,",options="header",]
|===================================================
|station_id |lat |lon |z |time |data1 |data2
|1 |23.2 |-120.5 |30 |2009-07-22 02:10:00Z |280.9 |7
|2 |24.6 |-132.9 |30 |2009-07-22 02:10:00Z |281.0 |4
|===================================================

== Factor out time coordinate

=== CDL:

-----------------------------
dimensions:
  station = 15;
  time = 20;
variables:
  float lat(station);
  float lon(station);
  float z(station);
  float time(time);
  float data1(station, time);
  float data2(station, time);
-----------------------------

=== CDM Nested Table:

----------------------
dimensions:
  station = 15;
  time = 20;
time(time);
Table {
   lat, lon, z;
   Table {
     data1, data2, ...
   } obs(time); 
} station(station); 
----------------------

We use an _index join_ to add the time coordinate to the observation.

=== SQL notation:

No way to effectively factor out time coordinate, must store redundantly
in the obs table

== Variable number of times for each station

=== CDL:

The 2D data arrays data(station, time) are flattened into a 1D arrays:
data(obs). This is a way to efficiently store __ragged arrays__, ie
non-rectangular arrays.

-------------------------
dimensions:
  station = 15;
  obs = 287;
variables:
  float lat(station);
  float lon(station);
  float z(station);
  float time(obs);
  float data1(obs);
  float data2(obs);
  int station_index(obs);
-------------------------

The _station_index_ variable is added to associate each observation with
a station, using the station dimension index. The index here acts as a
primary key for the station. The observations can be stored in any
order.

-------------------------
dimensions:
  station = 15;
  obs = 287;
variables:
  float lat(station);
  float lon(station);
  float z(station);
  int obs_count(station);
  float time(obs);
  float data1(obs);
  float data2(obs);
-------------------------

The _obs_count_ variable is added to associate each observation with a
station. All obs between rowStart(s) and rowStart(s+1) belong to station
s, where

----------------------
rowStart(stn) = 0 if stn = 0
rowStart(stn) = rowStart(stn-1) + __obs_count__(stn-1) if i > 0
----------------------

The advantage of this approach is performance for getting all the
observations for one station: the data for each station are stored
contiguously, and can be found by reading obs_count(station) instead of
station_index(obs).

=== CDM Nested Table:

----------------------
dimensions:
  station = 15;
Table {
   lat, lon, z;
   Table {
     time;
     data1, data2, ...
   } obs(*); 
} station(station); 
----------------------

The (*) means a variable number. The notation is independent of the
various ways that the ragged arrays might be stored.

=== SQL notation:

SQL tables always have a variable length number of rows.

Design Goals

* categorize point data into small number of types
* accept current practices for storing point data (as much as possible without too much complication)
* allow storing multiple features in one file
* allow variable length features
* allow user to decide on how much data redundancy
* enable generic software to read files

== Standard Names

* ragged_rowSize
* ragged_parentIndex
* station_id
* station_desc
* station_altitude // how does this play with z(z) ?? look at z units ??
* station_wmoid
* profile_id
* trajectory_id
* section_id

== Other Issues

* stationTable.limit
