:source-highlighter: coderay
[[threddsDocs]]

= HTTP Session Control

== Introduction

New public classes are introduced to the package ucar.httpclient. These
are __HTTPSession.java__, __HTTPMethod.java__,
__HTTPMethodStream.java__, __HTTPException.java__,
__HttpClientManager.java__, These classes are intended to wrap various
Apache httpclient-3 library classes so that (1) it will simplify use,
and (2) it will be possible to later switch to, say, the Apache
httpclient4 library.

These classes support a form of _session_ semantics for Java network
access. The notion of session is only loosely tied to the HTTP notion of
session.

=== HTTPSession and Session Semantics

A session is encapsulated in an instance of the class __HTTPSession__.
The encapsulation is with respect to a specific url. This means that
once a session is specified, it is tied permanently to that url and
<<URL Management, compatible URLs>>.

It is important to note that Session objects do NOT correspond with the
HttpClient objects of the Apache httpclient library. Each Session does,
however, encapsulate an instance of an Apache HttpClient.

It is possible to create a session with a null url, in which case, the
session can be used generally. For this, an _HTTPSession_ constructor
with no arguments is provided. If used, then (1) the session is tied to
no specific url, and (2) method creation must specify a url (see
<<HTTPMethod>>).

=== HTTPMethod

This class encapsulates the information about a given method request and
response. Its primary operation is __execute()__, which causes a request
to be sent to a server and a response obtained.

The _HTTPMethod_ class also operates as a factory for creating
_HTTPMethod_ instances. To create a method for doing an HTTP GET
operation, for example, one would invoke this operation

[source,java]
---------------------------------------
HTTPMethod m = HTTPMethod.Get(session);
---------------------------------------

where `session` is a previously created session object.

Alternately, one can create a method and specify a url.

[source,java]
-------------------------------------------
HTTPMethod m = HTTPMethod.Get(session,url);
-------------------------------------------

Note that any URL must be compatible (See the Section on
<<URL Management>>.

=== HTTPMethodStream

The purpose of this class is to allow other classes to access the data
stream associated with a method response. It tracks the method to allow
it to be closed when the stream hits eof or is explicitly closed.

=== HTTPException

This class is a subclass of __java.io.IOException__. It is the exception
for reporting errors out of the classes listed above.

=== HttpClientManager

This class is a utility class to perform some specialized actions. Its
name begins with "Http" rather than "HTTP" for historical reasons.

This class contains only static methods and these methods perform the
following utility operations.

Return the contents of a URL as a String

[source,java]
---------------------------------------------------------------
String getUrlContentsAsString(String urlencoded, int maxKbytes)
---------------------------------------------------------------

Make a request on the specified url and return its response as a String
of max length __maxKbytes__.

Get the contents of URL and store in a file.

[source,java]
-----------------------------------------------------------------------------
void copyUrlContentsToFile(String urlencoded, File file) throws HTTPException
-----------------------------------------------------------------------------

Make a request on the specified url, obtain its contents and write to
the specified file.

Append the contents of a URL to the end of a File

[source,java]
-------------------------------------------------------------------------
long appendUrlContentsToFile(String url, File file, long start, long end)
-------------------------------------------------------------------------

Make a request on the specified url, obtain its contents and append to
the specified file.

Initialize the Client Manager class

[source,java]
---------------------------------------------------------
void init(CredentialsProvider provider, String userAgent)
---------------------------------------------------------

Initialize to use a specified credentials provider and user agent when
making requests.

=== URL Management

It is possible to specify a url in several places.

1.  It may be inherited from the URL specified when the session was
created.
2.  It may be specified as part of the HTTPMethod constructor (via the
factory). If none is specified, then the session URL is used.
3.  It may be specified as an argument to the execute() method. If none
is specified, then the factory constructor URL is used (which might, in
turn have come from the session).

Legal url arguments to the HTTPMethod factory call and execute() call
are constrained by the URL specified in creating the HTTPSession
instance, if any. If the session was constructed with a specified URL,
then any url specified to HTTMethod (via the factory or via execute())
must be "compatible" with the session URL. The term "compatible"
basically means that the session url, as a string, must be a prefix of
the specified method url. This maintains the semantics of the Session
but allows flexibility in accessing data from the server. As an example,
if a session was created and specifed the URL
"http://motherlode.ucar.edu", then any URL specified, in say,
HTTPMethod.execute() must begin with the session URL. So, specifiying
"http://motherlode.ucar.edu/path/file.nc.dds" would be a compatible
url. Note that if the session was created with no url then a URL must be
specified to the HTTPMethod object.

There are some exceptions to the prefix rule for compatibility. Let
_surl_ be the session url and _murl_ be the url specified for the
method. The following rule holds.

* If the _surl_ does not have a principal, then the _murl_ without its
principal is tested for compatibility. In effect, a missing principal
acts like a wildcard.
+
Similarly, missing ports or paths in the _surl_ also act like wildcards.

Additionally, and for backward compatibility, if _surl_ is null or is
the empty string (""), then any other url is considered compatible.

=== Single Use Methods

A reasonably common use case is when a client wants to create a method,
execute it, get the response as a stream, and pass the stream up to some
higher level for use. In this situation, it can be tricky to close the
method and the session objects properly because they will have passed
out of scope by the time the stream is read.

To support this use case, HTTPMethod supports what amounts to a one-shot
use. The steps are as follows:

1.  HTTPMethod method = HTTPMethod.Get(). This implicitly creates a
session internal to the method instance.
2.  Set any session parameters or headers using
method.getSession().setXXX
3.  Set any parameters and headers on method
4.  method.execute(
5.  Get any response method headers
6.  InputStream stream = method.getResponseBodyAsStream()
7.  return the stream to higher levels to process.

The first thing to note is that closing the stream will automatically
close the underlying method, so even though the method object has passed
out of scope, it will still get closed when the stream is closed.

The second thing to note is that when the method object uses an
implicitly created session, closing the method will automatically close
the session.

The up shot is that closing the stream will cleanup the method and the
(implicitly created) session even though they are out of scope.

=== Examples

==== Example 1: Create/Use/Release Cycle

[source,java]
-----------------------------------------------------------------
public class Main
{
    public static void main(String[] argv)
    {
    String url = argv[0];
        HTTPSession session = new HTTPSession(url);
        HTTPMethod method = HTTPMethod.Get(session);
        int status = method.execute();
        System.out.printf("Execute: status code = %d\n", status);
    method.close();
    session.close();
    }
}
-----------------------------------------------------------------

==== Example 2: Using HttpClientManager

[source,java]
------------------------------------------------------------------------
public class Main
{
    public static void main(String[] argv)
    {
    String url = argv[0[];
    string content = HttpClientManager.getUrlContentsAsString(url,1024);
    }
}
------------------------------------------------------------------------

==== Example 3: Setting Some Global Parameters

[source,java]
-----------------------------------------------------------------------------
public class Main
{
    public static void main(String[] argv)
    {
    String url = argv[0];

        HTTPSession.setGlobalCredentialsProvider(new UserPasswordProvider());
    HTTPSession.setGlobalUserAgent("netcdf/java");
    HTTPSession.setMaxConnections(4);
    HTTPSession.setGlobalAuthenticationPreemptive(true);

        HTTPSession session = new HTTPSession(url);
        HTTPMethod method = HTTPMethod.Get(session);
        int status = method.execute();
        System.out.printf("Execute: status code = %d\n", status);
    method.close();
    session.close();
    }
}
-----------------------------------------------------------------------------

==== Example 4: Setting Some Local Parameters

[source,java]
-------------------------------------------------------------------
public class Main
{
    public static void main(String[] argv)
    {
    String url = argv[0];

        HTTPSession session = new HTTPSession(url);
        session.setCredentialsProvider(new UserPasswordProvider());
        session.setAuthenticationPreemptive(true);
        session.setUserAgent("agent");
        session.setConnectionManagerTimeout(475);
        session.setSoTimeout(475);

        HTTPMethod method = HTTPMethod.Get(session);
        int status = method.execute();
        System.out.printf("Execute: status code = %d\n", status);
    method.close();
    session.close();
    }
}
-------------------------------------------------------------------

==== Example 1: Create/Use/Release Cycle

[source,java]
-----------------------------------------------------------------
public class Main
{
    public static void main(String[] argv)
    {
    String url = argv[0];
        HTTPSession session = new HTTPSession(url);
        HTTPMethod method = HTTPMethod.Get(session);
        int status = method.execute();
        System.out.printf("Execute: status code = %d\n", status);
    method.close();
    session.close();
    }
}
-----------------------------------------------------------------

== Authorization Credentials

_HTTPSession_ operates in conjunction with the new credentialing
mechanisms to support better mechanisms for setting authorization
credentials.

The key idea is that a single, global database of credentials is
maintained. The key for the database is the combination of the
authorization scheme plus a url. This key pair maps to an instance of
CredentialsProvider. At the time an HTTP method is executed, the url
indicates when to apply authorization (if the server requests it). The
scheme indicates the kind of authorization scheme is being used: HTTP
Basic or Digest for example. The credentials provider is then invoked to
compute the set of credentials to be sent to the server.

Currently the following schemes are supported.

**Basic**: the HTTP Basic scheme based on clear-text user name and
password.

**Digest**: the HTTP digest scheme based on encrypted user name and
password.

**NTLM**: the NTLM scheme is a Microsoft specific scheme. Support is
provided, but has never been tested.

**SSL**: a scheme that uses a client-side key to authenticate the client
to the server. The ssl scheme is usually part of an SSL connection where
the server authenticates to the client and then the client authenticates
to the server.

The credentials provider (see
link:#HTTPSSLProvider.API[HTTPSSLProvider]) is used in a non-standard
way and it contains the following information.

* The path to the keystore file
* The password for decrypting the keystore file.
* The path to a truststore file
* The password for decrypting the truststore file.

The last two items are optional. If missing, then the client will accept
any certificate sent to it by the server. This includes, specifically,
self-signed certificates.

=== Setting Credentials

There are four primary credentialling methods in __HTTPSession__:

1.  Insert an arbitrary entry into the auth store. Its signature is as
follows.
+
[source,java]
--------------------------------------------------------------------------------------------------------------
static public void setAnyCredentialsProvider(HTTPAuthScheme scheme, String url,  CredentialsProvider provider)
--------------------------------------------------------------------------------------------------------------
2.  Set it for all sessions, which means it will be applied to any url
unless overridden by a more specific entry in the auth store. Its
signature is as follows.
+
[source,java]
----------------------------------------------------------------------------------------------------
static public void setGlobalCredentialsProvider(HTTPAuthScheme scheme, CredentialsProvider provider)
----------------------------------------------------------------------------------------------------
3.  Set the credentials on a per-session basis, using the url defined
for that session. Its signature is as follows.
+
[source,java]
---------------------------------------------------------------------------------------
public void setCredentialsProvider(HTTPAuthScheme scheme, CredentialsProvider provider)
---------------------------------------------------------------------------------------
4.  Set the credentials on a per-session basis, using a client provided
instance of __Credentials__. This is only useful when the credentials
are unchanging. Its signature is as follows.
+
[source,java]
---------------------------------------------------------------------
public void setCredentials(HTTPAuthScheme scheme, Credentials creds);
---------------------------------------------------------------------
5.  Set the credentials for all sessions using a client provided
instance of __Credentials__. This is only useful when the credentials
are unchanging. Its signature is as follows.
+
[source,java]
---------------------------------------------------------------------------
public void setGlobalCredentials(HTTPAuthScheme scheme, Credentials creds);
---------------------------------------------------------------------------

For backward compatibility, the following two methods are defined. They
use the Basic scheme for the scheme.

[source,java]
---------------------------------------------------------------------------
static public void setGlobalCredentialsProvider(CredentialsProvider provider)
public void setCredentialsProvider(CredentialsProvider provider)
---------------------------------------------------------------------------

== Command Line Access to the Authorization Mechanism

Before the introduction of the authorization mechanisms described in
this document, it was possible to specify the keystore+password and the
truststore+password using the command line flags

--------------------
-Dkeystore
-Dkeystorepassword
-Dtruststore
-Dtruststorepassword
--------------------

For purposes of backward compatibility, a check is made for these flags,
and if they are defined, then an entry equivalent to the following is
inserted into the auth store.

[source,java]
-----------------------------------------------------------------
insert(new Entry(HTTPAuthScheme.SSL,ANY_URL,
                 new HTTPSSLProvider(keystore,kpassword,
                                     truststore,trustpassword)));
-----------------------------------------------------------------

Proxy Support

There are two kinds of proxy support: authenticating and simple (i.e.
not authenticating). Both kinds of proxies require the specification of
a host name and a port. In addition, authenticating proxies require the
specification of some form of credentials/credentialsprovider. The
authenticating proxy usually occurs as a corporate or governmental
firewall controlling access to the ``outside world''.

Specifying the host plus port can be done in either of two ways.

1.  Programmatically by called the procedure
link:#setGlobalProxy[HTTPSession.setGlobalProxy()].
2.  Global command line parameters: ``-Dhttp.proxyHost'' and
``-Dhttp.proxyPort''; note that this is equivalent to calling
link:#setGlobalProxy[setGlobalProxy()] with the values of the
http.proxyhost and the http.proxyport command line parameters

For authentication, the authentication database is consulted to try to
locate the proper credentials for the proxy machine.

Also note that one can set the username and password into the url used
to establish an HTTPSession instance. Note that one should not use the
url of the proxy but rather the url of the target server from which one
is trying to obtain information.

----------------------------------
http://username@pwd:server.com/...
----------------------------------

This will only work if the proxy is authenticating using BASIC
authentication. If it uses, for example, NTLM, then you will need to set
the authentication programmatically.

== Miscellaneous -D flags

It is possible to control the value of certain other session
parameters using the following -D flags as arguments to the
JVM. These can be set for a client and/or a server.

[cols=2,options="header"]
|===
| -D Flag              | Description
| tds.http.conntimeout | Connection timeout in seconds
| tds.http.sotimeout   | Socket timeout in seconds
| tds.http.maxconns    | Maximum number of allowed connections
|=== 

== Miscellaneous Changes

As a side effect of the insertion of the auth mechanisms, a number of
miscellaneous changes also occurred.

1.  HttpClientManager class was moved to the same package as
HTTPSession, namely ucar.httpclient.

== Appendices: Session APIs

Note: the following set may lag the actual API, so the JavaDoc or code
should be referenced to see any modifications.

=== HTTPSession API

==== Static Get/Set Methods

* static synchronized void setGlobalUserAgent(String _userAgent)
** Set a user agent that will be used when establishing any session.
* static String getGlobalUserAgent()
* static void setGlobalThreadCount(int nthreads)
** Set the max number of threads that will be supported.
* static int getGlobalThreadCount()
* static Cookie[] getGlobalCookies()
** Returns the set of cookies available on a generic session.
* static void setGlobalAuthenticationPreemptive(boolean tf)
** Specifies that all HTTPSession instances should use global preemption
* static void setGlobalProxy(String host, int port)
** Force use of a proxy at host:port

==== Set Credentials Provider(s)

* static void setAnyCredentialsProvider(HTTPAuthScheme scheme, String
url, CredentialsProvider provider)
** Insert an arbitrary entry into the auth store.
** throws HTTPException
* static void setGlobalCredentialsProvider(HTTPAuthScheme scheme,
CredentialsProvider provider)
** Set provider for all sessions, which means it will be applied to any
url unless overridden by a more specific entry in the auth store.
** throws HTTPException
* public void setCredentialsProvider(HTTPAuthScheme scheme,
CredentialsProvider provider)
** Set the credentials on a per-session basis, using the url defined for
that session.
** throws HTTPException
* static void setGlobalCredentialsProvider(CredentialsProvider cp)
** For Backward compatibility; this method will create a row in
_HTTPAuthStore_ and an instance of _HTTPCreds_ supporting global
authorization using the specified credentials provider and the Basic
scheme.
** throws HTTPException
* static void setCredentialsProvider(CredentialsProvider)
** For Backward compatibility; this method will create a row in
_HTTPAuthStore_ and an instance of _HTTPCreds_ supporting authorization
for the session’s url, using the specified credentials provider and the
Basic scheme.
** throws HTTPException
* public void setCredentials(HTTPAuthScheme scheme, Credentials creds)
** Set the credentials on a per-session basis, using the url defined for
that session.
** throws HTTPException
* static void setGlobalCredentials(HTTPAuthScheme scheme, Credentials
creds)
** Set the credentials for all session, using the url defined for that
session.
** throws HTTPException

==== Constructor(s)

* HTTPSession(String url)
** Creates a session object with the specified session defining url.
* HTTPSession()
** Creates a session object compatible without any url.

Note that in both cases, selected command line parameters (specified by
the java -D flag) are used for initialization. There are two such cases.

1.  Simple Proxies: If defined, the values of the flags
``-Dhttp.proxyHost'' and ``-Dhttp.proxyPort'' are used as arguments to
the link:#setGlobalProxy[setGlobalProxy()"] method to establish a
global, simple (i.e. non-authenticating) proxy.
2.  SSL: If defined, the values of the flags ``-Dkeystore'',
``-Dkeystorepassword'' and ``-Dtruststore'', ``-Dtruststorepassword''
are converted to an HTTPSSLProvider object that in turn is used as an
argument to the setGlobalCredentialsProvider method to establish client
side key support.

==== Instance Get/Set Methods

* void setAuthenticationPreemptive(boolean tf)
* void setUserAgent(String agent)
* void setConnectionManagerTimeout(long timeout)
* void setSoTimeout(int timeout)
* String getCookiePolicy()
* Cookie[] getCookies()
* void setContext(HttpState cxt)
* HttpState getContext()
* void setProxy(String host, int port)
** Force use of a proxy at host:port
* void setCredentialsProvider(CredentialsProvider provider)

==== Session Shutdown Methods

* synchronized void close()
** Close this session and also any un-closed HTTPMethods associated with
this session.

=== HTTPMethod API

==== Static Methods

* static HTTPMethod \{Get|Head|Put|Post|Options}(HTTPSession session)
throws HTTPException
** Create a method associated with the specified session and session
url.
* static HTTPMethod \{Get|Head|Put|Post|Options}(HTTPSession session,
String uri) throws HTTPException
** Create a method associated with the specified session, but using the
specified ``compatible'' url.
* static HTTPMethod \{Get|Head|Put|Post|Options}(HTTPSession
session,String url) throws HTTPException
** Create a method associated with the specified session and specified
url. The specified url must be compatible with any session url.
* static HTTPMethod \{Get|Head|Put|Post|Options}(String uri) throws
HTTPException
** Create a method and implicitly create a hidden session using the
specified url.
* static HTTPMethod \{Get|Head|Put|Post|Options}() throws HTTPException
** Create a method and implicitly create a hidden session.
* static void setGlobalMethodParameter(String name, Object value)
** Set a parameter that is to be applied to all method instance
requests.
* static Enumeration getAllowedMethods()

==== Execute

* int execute() throws HTTPException
** Find the relevant url from the method or the session, send the
request, and receive and check the response.
* int execute(String url) throws HTTPException
** Using the specified url, send the request, and receive and check the
response.

==== Miscellaneous Get/Set

* HTTPSession getSession()

==== Responsebody

The API has a number of methods for getting the response body in various
forms.

* InputStream getResponseBodyAsStream()
* (aka getResponseAsStream)
* byte[] getResponseAsBytes(int maxsize)
* byte[] getResponseAsBytes()
* String getResponseAsString(String charset) (aka getResponseAsString)

==== Instance Get/Set

* int getStatusCode()
* String getStatusLine()
* void setFollowRedirects(boolean tf)

==== Request Header Set/Get

* void setMethodHeaders(List
+
headers) throws HTTPException
* void setRequestHeader(String name, String value) throws HTTPException
* void setRequestHeader(Header h) throws HTTPException
* Header getRequestHeader(String name)
* Header[] getRequestHeaders()

==== Reponse Header Get

* Header getResponseHeader(String name)
* Header[] getResponseHeaders()
* Header[] getResponseFooters()

==== Request Parameter Set/Get

* void setRequestParameter(String name, Object value)
* Object getMethodParameter(String key)
* HttpMethodParams getMethodParameters()

==== Request Content Set

* void setRequestContentAsString(String content) throws HTTPException
* void setMultipartRequest(Part[] parts) throws HTTPException

=== HTTPMethodStream API

This class subclasses _java.io.InputStream_ and provides the
_InputStream_ interface. In addition, if the stream is closed, then the
underlying method is closed as well.

=== HTTPSSLProvider API

Since no existing _CredentialsProvider_ implementation exists to support
the SSL scheme, the _HTTPSSLProvider_ class is provided for that
purpose. Its constructor requires arguments for the client side keystore
plus password and the client side truststore plus password. The keystore
and truststore arguments are absolute paths.

==== Constructor(s)

* HTTTPSSLProvider(String keystore,String keypass, String truststore,
String trustpass)
** Creates an SSL provider that uses the client side key in the keystore
and validates the server-side certificate using the truststore. If the
truststore is null, then any certificate presented by the server will be
accepted.
* HTTPSSLProvider()
** Equivalent to HTTPSSLProvider(null,``'',null,``'');
* HTTPSSLProvider(String keystore, String keypass)
** Equivalent to HTTPSSLProvider(keystore,keypass,null,``'');

==== Credentials Provider Interface

* Credentials getCredentials(AuthScheme authscheme, String host, int
port, boolean isproxy) +
 throws CredentialsNotAvailableException
** This function is here only to satisfy the interface and will never be
invoked.

== Author

Author: Dennis Heimbigner +
 Affiliation: UCAR/Unidata +
 email: dmh@ucar.edu
