#
# expect/tcl code to test the dds parser and scanner
# jhrg
#
# $Id: test.18.exp 15901 2007-02-28 23:57:28Z jimg $

global comp_output		# contains output from dds-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_name' is the name of the das input file for this test.

set test_name test.18

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "DDS past semantic check
DDS past full semantic check
Dataset {
    Grid {
     ARRAY:
        Byte temp\[100\]\[7\];
     MAPS:
        Float64 steps\[100\];
        String colors\[7\];
    } oddTemp;
} 123;"

dds-test_start p $srcdir/$test_name

if ![string compare $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}

# $Log: test.18.exp,v $
# Revision 1.1  2003/08/11 20:50:10  ndp
# Initial revision
#
# Revision 1.1  2002/05/23 01:43:33  jimg
# Added/Updated using stuff from C++.
#
# Revision 1.2  2001/06/15 23:49:06  jimg
# Merged with release-3-2-4.
#
# Revision 1.1.2.1  2001/05/08 19:11:50  jimg
# Added test for integer dataset names.
#

