# expect/tcl code to test the dds parser and scanner
# jhrg
#
# $Log: test.9.exp,v $
# Revision 1.1  2003/08/11 20:50:10  ndp
# Initial revision
#
# Revision 1.2  2002/05/23 01:43:33  jimg
# Added/Updated using stuff from C++.
#
# Revision 1.7  2000/10/03 22:18:04  jimg
# Fixes to the tests to accomodate debugging fixes in DDS.cc
#
# Revision 1.6  2000/06/16 18:15:01  jimg
# Merged with 3.1.7
#
# Revision 1.5.2.1  2000/06/15 02:24:58  jimg
# Fixed the tests: problems with PATH, etc. broke the tests on my new machine
#
# Revision 1.5  1999/07/22 17:08:17  jimg
# *** empty log message ***
#
# Revision 1.4  1996/05/14 15:41:50  jimg
# These changes have already been checked in once before. However, I
# corrupted the source repository and restored it from a 5/9/96 backup
# tape. The previous version's log entry should cover the changes.
#
# Revision 1.3  1995/12/06  21:58:55  jimg
# Removed `List List' variables.
#
# Revision 1.2  1995/01/19  22:05:25  jimg
# Fixed for new class hierarchy.
#
# Revision 1.1  1994/12/21  17:01:41  jimg
# Added these to the testsuite.
#

global comp_output		# contains output from dds-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_name' is the name of the das input file for this test.

set test_name test.9

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "DDS past semantic check
DDS past full semantic check
Dataset {
    List Int32 i\[10\]\[20\];
    Sequence {
        String name;
        Int32 age;
    } person;
    Structure {
        Int32 j;
        Int32 i;
        Structure {
            Int32 i;
            Float64 f\[10\];
        } data;
        List String folks;
    } exp;
    Grid {
     ARRAY:
        Float64 g\[10\]\[10\]\[10\];
     MAPS:
        Float64 lat\[10\];
        Float64 lon\[10\];
        Float64 weirdness\[10\];
    } strange;
} data6;"

dds-test_start p $srcdir/$test_name

if ![string compare $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}


