:source-highlighter: coderay
[[threddsDocs]]

= THREDDS Group - Planning

'''''

== Version 4.1 (Sept 15)

<<../../../../archive/src/docs/web/thredds/tech/devel/threddsGroup/threddsCatalog2/backlogs#,thredds.catalog2>>
Cleanup THREDDS Catalog API for access, creation, improved XML parsing,
and smaller memory footprint.

(PointObsCollectionServer) Support spatial and temporal queries over
collections of point data.

GEMPAK Point Data

FileSystem Efficient tracking of files on disk with caching etc.

(FileSystem Aggregation) Use FileSystem for tracking collections of
datasets used in aggregations.

(FileSystem PointCollection) Use FileSystem for tracking collections of
datasets for PointObsCollectionServer.

(GRIB PDS/GDS Index) New GRIB index scheme that includes PDS and GDS.

(GRIB Ensemble Data) Improve GRIB library handling of ensemble data
(SREF, …)

(Some Bugs)

* Ability to output dataSize element with units=``bytes''

== Version 4.2 (Dec 15)

catalog2 on server

consider non-catalog config mechanism

* catalog2
* follow Spring bean wiring paradigm
* GUI interface hides XML

caching, aggregation, changing datasets +

generic config mechanism for point datasets

(FileSystem DatasetScan) Use FileSystem for tracking collections of
datasets for DatasetScan/CatalogGen.

(DatasetSource) Extract and use new interface for locating datasets
given an ID.

* GOAL: separate data location from HTTP request processing; allow TDS,
ncWMS, RAMADDA to use same interface.
("`TDS Services ->|<- DatasetSource interface ->|<- TDS State`")
* Register IDs or ID groups that are handled (state impl side of things)
* Handle restricted data? Metadata?

(AutoMetadataExtraction) Add automated metadata harvesting (extract from
dataset and insert into catalog).

* (AutoMetadataExtraction Manual) Manual insertion of templates in
catalogs (XPath into NcML, e.g., ``@title'')
* (AutoMetadataExtraction Extractor) MetadataExtractor interface as
plug-in for catalog builder/source (DatasetCollection?)
* (AutoMetadataExtraction FeatureType) Use FeatureType API to get
certain metadata (BBox, etc)
* Persistence mechanism for extracted metadata

(GEMPAK Sounding Data) CDM local and remote access (w/ collection
queries) to GEMPAK Soundings.

(RadarServer TdsContext) Update RadarServer to use TdsContext and
FileSource for locating config directories and files (Spring Bean?
Spring MVC?).

== Version 4.3 ()

* (Unidata Real-time Regional WRF model) Improve the
``idd/rtmodels.xml'' catalog to separate out model runs, extract lat/lon
bounding box for each run, and aggregate over the forecast hours for
each run. ((??Use pluggable DatasetCollection to organize data. Use
(AutoMetadataExtraction) for lat/lon bounding box. ??))
* (TDS Config State)
* (FMRC Refactor) ???

== Product Backlog

(FileSystem Updater) Extend FileSystem to support pluggable update
algorithm (on a per collection/directory basis) for handling different
creation/arrival and scour/remove patterns.

(Dataset) Efficient tracking of datasets and metadata (file, remote,
aggregation).

(CDM Decoder/Indexer) LDM feeding data to CDM decoders which build
(Dataset)s and (DatasetInventory)s

* (CDM Decoder For Inventory) Decode multiple records into one (Dataset)
(e.g., GRIB, BUFR, …)
* (CDM Decoder For Collection) Decode into one (DatasetCollection)
(e.g., Profiler, … ?)
* (CDM Decoder Both) Decode into many (Dataset)s that make up one
(DatasetCollection) (e.g., all)

(DatasetInventory) Efficient tracking of dataset components (e.g., the
GRIB records that make up a GRIB file).

(DatasetCollection) Efficient tracking of dataset collections and
services for those collections (including lists/catalogs, subsetting on
BBox, aggregation support).

(WCS Spring-ify) Use Spring binding and validation framework for WCS
requests.

(DatasetSource) Extract interface for accessing datasets given an ID for
use by TDS, ncWMS, and RAMADDA.

(WCS RAMADDA) Pull WCS Servlet code apart for use by RAMADDA

(TDS Config WebUI)

(PointObs CF)

(Ensemble GRIB)

(Ensemble CF)

TeamCityPlus

unidataCommon.jar

(DatasetSession) TDS sessions on data requests coordinated with LDM
scour (data marked for deletion but held till all sessions are closed
(and data released)).

=== Even More

* (TDS metadata auto-extraction) Use (Dataset)/(DatasetCollection) for
auto-extraction of metadata.
* (Station (part of PointObs?))
* (Profile)
* (Trajectory)
* (Image)
* (Swath)
* (TDS monitoring GUI)
* (EventDriven FileSystem) Keep FileSystem current with event
notification (LDM, OS file system notification, …).
* (Asynchronous OPeNDAP)
* (Asynchronous CDMRemote)
* (Streaming OPeNDAP)
* (Streaming CDMRemote)

=== And More Data

* WRF staggered grids
* EUMETSAT GRIB2
* EUMETSAT BUFR
* EPA NMAQ
* GEON text
* CREX ?
* Lightning data on motherlode ?
