:source-highlighter: coderay
[[threddsDocs]]

= thredds.catalog2: Catalog redesign

_6/12/2015_

== ESGF Mode

. DataRoots are in top catalog.
. Global services in top catalog
. Top catalog always read in and cached
. DatasetTracker persists _restrict, ncml_
. Use CatalogScan with watches
. Updating
.. If no cache, read in all catalogs into cache, record lastRead
(global i think)
.. If cache, read catalog lastModified, test against lastRead, reread
if needed
.. Manual reinit (just remove cache ??)
.. CatalogScan has watch, if changed, then reread that catalog.
.. This doesnt solve the problem of deletions.
... (drag and drop into delete folder ?)
... keep copy of old catalog
... keep track of what datasets belong to what catalog

More General

. DataRootPathMatcher could persist all data roots (dir, datasetScan,
FC)
. DatasetTracker could persist found metadata after cracking the file
(space/time extents, global attributes)

== State redesign

_3/30/2015_

. Ids vs paths
. dont requires default service, can be added globally
. should we also cache dynamic catalogs (catref, fc) ?

4/1/2015

Config version 2

. Put dataset roots, services seperate, maybe a catalog ?
. Put catalogs that might change in a seperate directory tree.

== TdsContext

Implements ServletContextAware so it gets a ServletContext and performs
most initial THREDDS set up.

Not sure if it needs to have a ``reinit'' ? Perhaps this should be the
object that does not reinit.

. checks version
. check for latest stable and development release versions
. sets the content directory
. reads persistent user defined params and runs ThreddsConfig.init
. creates, if don’t exist, log and public dirs in content directory
. Sets InvDatasetScan and InvDatasetFeatureCollection properties
. Get default and jsp dispatchers from servletContext
. Creates and initializes the TdsConfigMapper (how is this used? is not a instance field)
. CdmInit is then called (by Spring)

* lots of state in TdsContext
* not immutable
* effectively a singleton

== ConfigCatalogCache

. all acesses must come through here
. reloads when not in cache, using *ConfigCatalogBuilder*
. set maximum number of cache entries (currently 1000)
. expires ??
. should we also cache dynamic catalogs (catref, fc) ?

[source,java]
----
com.google.common.cache.LoadingCache<String, ConfigCatalog> cache
----

== ConfigCatalogInitialization

. reads configuration catalogs
.. finds DatasetRoots, DatasetScan, FeatureCollection
.. finds restrictAccess, NcML
.. look for duplicate ids (paths?)
. constructs the PathMatcher
. configures the datasetManager
. adds a watch on all configCatalogs, or on directories (ESG mode)
. Keep track of all root catalogs (all other catalogs can be found
from these)

[source,java]
----
@Autowired private DataRootPathMatcher<DataRoot> dataRootPathMatcher;
@Autowired private DatasetTracker datasetTracker;
List<String> rootCatalogKeys;
----

== DataRoot

A DataRoot associates a urlPath to a directoy, **DatasetScan**, or
**FeatureCollectionRef**. This is where the references to those objects
are held, preventing GC.

[source,java]
----
private final String path;          // match this path
private final String dirLocation;   // to this directory
private final DatasetScan scan;     // the DatasetScan that created this (may be null)
private final FeatureCollectionRef featCollection; // the FeatureCollection that created this (may be null)
----

== DataRootPathMatcher

Holds the DataRoots, preventing GC.

. An in-memory TreeSet of DataRoot paths, allowing ``longest match''
of request -> DataRoot path
. A map DataRoot path -> DataRoot. Could be stored in external cache
if needed.

[source,java]
----
private final TreeSet<String> treeSet;    // this should be in-memory for speed
private final Map<String, T> map;         // this could be turned into an off-heap cache if needed
----

== DataRootManager

. *getLocationFromRequestPath()*
. *findDataRootMatch()*
. *getCatalog();* this is here because of need for dataRoots to find

atasetScan, featureCollection (dynamic catalogs)

[source,java]
----
@Autowired private DataRootPathMatcher<DataRoot> dataRootPathMatcher;
----

== CatalogManager

. **getCatalog()**, called by CatalogServiceController

[source,java]
----
@Autowired private DataRootManager dataRootManager;
@Autowired private ConfigCatalogCache ccc;
@Autowired private FeatureCollectionCache featureCollectionCache;
----

== DatasetTracker

Maybe eventually track all metadata

* String findResourceControl(String path);
* String findNcml(String path);

== DatasetManager

Turns request into CDM Dataset objects. Fronted by
**TdsRequestedDataset**.

. getLocationFromRequestPath(String reqPath)
. findResourceControl()
. openNetcdfFile()
. openGridDataset()
. openGridCoverage()
. openPointDataset()

[source,java]
----
@Autowired private DataRootManager dataRootManager;
@Autowired private FeatureCollectionCache featureCollectionCache;
@Autowired private Authorizer restrictedDatasetAuthorizer;
@Autowired private DatasetTracker datasetTracker;

private ArrayList<DatasetSource> datasetSources = new ArrayList<>();
----

Currently we don't have access to the catalog Dataset object. Could we?

. DataRootPathMatcher gives you the dataRoot; if DatasetScan or
FeatureCollection then done.
. Otherwise, can we have a (possibly external) map of urlPath ->
Dataset ??
. Can we get dataset to be independent so can be serialized and cached?
. Open the file, extract metadata into the Dataset element. What about
for datasetScan ??
. Let the Catalog use the new Dataset, maybe write the catalog back
out with it ??

If you pay the price of fetching Dataset for every request, can do away
with special purpose maps to NcML and restrict.

Could keep a memory cache of reqPath -> Object to handle the common
case. expire after a some minutes of inactivity.

Tracks NcML as a map *requestPath -> Dataset*

* Dataset.getNcmlElement()

[source,java]
----
// InvDataset (not DatasetScan, DatasetFmrc) that have an NcML element in it. key is the request Path
private Map<String, Dataset> ncmlDatasetHash = new HashMap<>();
----

* could have Set<reqPath> hasNcml, and Map<reqPath,Dataset> all ??

Track restricted access datasets

* map of *requestPath -> restrictAccess*
* PathMatcher of *requestPath -> restrictAccess*

[source,java]
----
// resource control
private HashMap<String, String> resourceControlHash = new HashMap<>(); // path, restrictAccess string for datasets
private volatile PathMatcher<String> resourceControlMatcher = new PathMatcher<>(); // path, restrictAccess string for datasetScan
----

Track DatasetSource (only used by LAS)

[source,java]
----
// list of dataset sources. note we have to search this each call to getNetcdfFile - most requests (!)
// possible change to one global hash table request
private ArrayList<DatasetSource> sourceList = new ArrayList<>();
----

== URL redesign

https://localhost:8443/thredds/admin/spring/map

[source,bash]
----
    [/admin/showFmrc, /admin/showFmrc/*]: thredds.server.admin.CollectionController.showFmrcCache()
    [/admin/collection/showStatus]: thredds.server.admin.CollectionController.handleCollectionStatus()
    [/admin/collection/showStatus.csv]: thredds.server.admin.CollectionController.handleCollectionStatusCsv()
    [/admin/collection, /admin/collection/trigger]: thredds.server.admin.CollectionController.handleCollectionTriggers()
    [/admin/debug, /admin/debug/*]: thredds.server.admin.DebugController.showDebugPage()
    [/admin/**]: thredds.server.admin.DirDisplayController.handleRequestInternal()
    [/admin/log/**, /admin/roots]: thredds.server.admin.LogController.handleRequestInternal()
    [/admin/spring/map]: thredds.server.admin.SpringInfoController.show()
    [/catalog/**/*.xml, /catalog/*.xml]: thredds.server.catalogservice.LocalCatalogServiceController.handleXmlRequest()
    [/catalog/**/*.html, /catalog/*.html]: thredds.server.catalogservice.LocalCatalogServiceController.handleHtmlRequest()
    [/cdmremote/**]: thredds.server.cdmremote.CdmRemoteController.handleRequest()
    [/cdmrfeature/**]: thredds.server.cdmremote.CdmrfController.metadataRequestHandler()
    [/cdmrfeature/**]: thredds.server.cdmremote.CdmrfController.headerRequestHandler()
    [/cdmrfeature/**]: thredds.server.cdmremote.CdmrfController.dataRequestHandler()
    [/fileServer/**]: thredds.server.fileserver.FileServerController.doGet()
    [/metadata/**]: thredds.server.metadata.MetadataController.getMetadata()
    [/ncss/**]: thredds.server.ncss.controller.NcssController.handleRequest()
    [/ncss/**/datasetBoundaries.xml]: thredds.server.ncss.controller.NcssDatasetBoundariesController.getDatasetBoundaries()
    [/ncss/**/station.xml]: thredds.server.ncss.controller.NcssDatasetInfoController.getStations()
    [/ncss/**/dataset.html, /ncss/**/dataset.xml, /ncss/**/pointDataset.html, /ncss/**/pointDataset.xml]: thredds.server.ncss.controller.NcssDatasetInfoController.getDatasetDescription()
    [/radarServer2/{dataset}/dataset.xml]: thredds.server.radarServer2.RadarServerController.datasetCatalog()
    [/radarServer2/{dataset}]: thredds.server.radarServer2.RadarServerController.stations()
    [/radarServer2/{dataset}/stations.xml]: thredds.server.radarServer2.RadarServerController.stationsFile()
    [/radarServer2/catalog.xml]: thredds.server.radarServer2.RadarServerController.topLevelCatalog()
    [/radarServer2/{dataset}]: thredds.server.radarServer2.RadarServerController.handleQuery()
    [/catalog.xml]: thredds.server.root.RootController.getRootCatalogXml()
    [/*.css, /*.gif, /*.jpg]: thredds.server.root.RootController.checkPublicDirectory()
    [/, /catalog.html]: thredds.server.root.RootController.getRootCatalog()
    [/info/serverVersion.txt]: thredds.server.serverinfo.ServerInfoController.getServerVersion()
    [/info/serverInfo.html]: thredds.server.serverinfo.ServerInfoController.getServerInfoHtml()
    [/info/serverInfo.xml]: thredds.server.serverinfo.ServerInfoController.getServerInfoXML()
    [/view/{viewer}.jnlp]: thredds.server.viewer.ViewerController.launchViewer()
    [/wcs/**]: thredds.server.wcs.WCSController.doGet()
----

Notes:

* opendap not in here
* cdmrfeature is wrong
* ncss needs to be disambiguated, prob back to ncss/grid and ncss/point
