:source-highlighter: coderay
[[threddsDocs]]

= Grib Collection Implementation Notes

3/14/2015

Heap Dump of tds-dev

Ran out of memory because restarting TDS doesnt clear memory - must
restart Tomcat.

InvDatasetFcGGrib holding 8.8M - ~500K bytes. Look at largest:

---------------------------------------------------------------------------------------------------------------------------------
InvDatasetFcGGrib   8844K
 InvDatsetImpl      6500
   datasets: ArrayList of 2873 catalogRefs RTMA consuming 2700 bytes each. likely a file partition should be time or directory ??
             put indirection - catalogRef for "Partitions" so dont keep in topCatalog
 Grib2Partion           2016
---------------------------------------------------------------------------------------------------------------------------------

-
 
-

6/15/2012

== Index

Example 1. GFS global half degree - 45 day archive

--------------------------------------------------------------------------------------------
 Rectilyser: nvars=117 records unique=132684 total=3637805 dups=3505121 (0.963526)
 createIndex for /data/ldm/pub/native/grid/NCEP/GFS/Global_0p5deg/NCEP-GFS-Global_0p5deg.ncx
 write RecordMaps: bytes = 1265209 record = 132684 bytesPerRecord=9
 write GribCollectionIndex= 35929 bytes
--------------------------------------------------------------------------------------------

There are a total of 3.6M grib records, but only 132K are unique and
used in the collection dataset. This is typical when making a collection
of forecast model runs, where the forecast times heavily overlap.

When opening the collection dataset, only 36K has to be read in. The
remaining bytes of the 1.26M collection index are the record lookup
section, and are read in only when a variable’s data is requested.

In this example, computing the collection index takes around 60 sec,
with 4Gb heap space, but 30 minutes with 2Gb heap. That probaby means
that the index took just under 2Gb heap and was doing excessive GC. So
one needs large heap sizes to compute these large collections.

== Assumptions on the GRIB encoding

The collection of GRIB records is not arbitrary, but must be coherent
(eg come all from the same model) such that the following assumptions
are valid:

1.  All Grib records are assumed to have the same center, subcenter, and
master and local table versions. This is used for determiing which GRIB
code and template tables to use.
2.  Grib records can be distributed arbitrarily among the collection of
files.
3.  Unique variables are created by hashing the __GDS, PDS template,
discipline, category, parameter, __ __level type__, and __level layer
flag__. Also, if they apply, the__ statistical process type__ (code
table 4.10), and the __ensemble derived type__  (table 4.7).
4.  The collection of GRIB records for each unique variable is turned
into a multidimensional grid, by taking the cartesion product of *_time
X ens X vert_* coordinates. Where there are missing records, the library
will return missing data. Where there are duplicate records, later
records replace earlier records, where later means later in one file, or
in a later file where the file collection is sorted lexigraphically.
5.  If there are multiple GDS (Grid Definition Section) in the
collection, each unique GDS and the variables that use it becomes a
seperate __Group__. GDS uniqueness is based on a hashcode.
Unfortunately, there may be roundoff errors and/or minor variations in
GDS encodings. The CDM tries to allow for this in
__Grib2Gds.hashcode()__. If you see variables unexpectedly split into
different groups with apparently the same projection, likely the
hashcode for that projection type needs to be modified.
6.  All of the time, ensemble, and vertical coordinates for each
variable in one group are compared, and where they are identical, are
shared between variables.

== RAF Caching

------------------------------------------------------------------------------------------------
    // GribCollection : default is allow 100 - 200 open files, cleanup every 15 minutes
    min = ThreddsConfig.getInt("GribCollection.minFiles", 100);
    max = ThreddsConfig.getInt("GribCollection.maxFiles", 200);
    secs = ThreddsConfig.getSeconds("GribCollection.scour", 15 * 60);
    if (max > 0) {
      GribCollection.initFileCache(min, max, secs);
      startupLog.info("CdmInit: GribCollection.initFileCache= ["+min+","+max+"] scour = "+secs);
    }
------------------------------------------------------------------------------------------------

== Time Partitions

------------------------------------------------------------------------------------------------------------------------------------------------
// date matcher part of spec - #date# - can only be in name
// time partition by directory

<collection spec="G:/nomads/cfsr/timeseries/**/.*grb2$" dateFormatMark="#timeseries/#yyyyMM" name="CFSR-timeseries" timePartition="directory" />


// dateFormatMark in seperate attribute - #match literal# - works on the path
// time partition by day
        <collection
            spec="/data/ldm/pub/native/grid/NCEP/SREF/CONUS_40km/ensprod_biasc/.*grib2$"
            name="SREF_CONUS_40km_ensprod_biasc"
            dateFormatMark="#SREF_CONUS_40km_ensprod_biasc_#yyyyMMdd_HHmm"
            timePartition="day"
            olderThan="5 min"/>






// date matcher part of spec - #date# - can only be in name

  <collection
            spec="/data/ldm/pub/native/grid/NCEP/SREF/CONUS_40km/pgrb_biasc/SREF_CONUS_40km_pgrb_biasc_[a-z]*_#yyyyMMdd_HHmm#.grib2$"
            name="SREF_CONUS_40km_ensprod_biasc"
            timePartition="day"
            olderThan="5 min"/>

        <collection
            spec="/data/ldm/pub/native/grid/NCEP/SREF/CONUS_40km/pgrb_biasc/.*grib2$"
            name="SREF_CONUS_40km_ensprod_biasc"
            dateFormatMark="yyyyMMdd_HHmm#.grib2#"
            timePartition="day"
            olderThan="5 min"/>


------------------------------------------------------------------------------------------------------------------------------------------------

 

cannot mix ensembles and vertical levels across the partition.

for each variable, create union of times: for each time track (value,
partition, localIndex). merge time coords with same \{value}. store
\{partition, localIndex} cmmon case is that variables will share
\{partition, localIndex}, but is it worth merging?

dont need proto change; it’s reselected when index is rebuilt

== check for changes

handled by DCM, looking only at underlying collection.

== GribCollection

1.  look for new or deleted files
2.  look if newFile.lastModified() > oldFile.lastModified()
3.  look if index (gbx9) file doesnt exist, or has lastModified date <
oldFile.lastModified()

 

can’t examine all files to see whats changed - too many files. only
examine each partition. maybe examine the latest?? maybe not - use
manual rescan ??

'''''

== Grib Collection Index File

A Grib Collection index file (ncx) stores the CDM header information,
plus stores which GRIB records the data is in.

The index file layout:

* *header* = ``Grib1CollectionIndex'' | ``Grib2CollectionIndex'' |
``Grib1Partition0Index'' | ``Grib2Partition0Index''
* *version* = 4 byte integer (big endian)
* *length* of VariableRecords section = 8 byte integer (big endian)
* **VariableRecords**[] = protobuf serialized objects
* *length* of GribCollectionIndex section = variable length integer
(vint)
* *GribCollectionIndex* = protobuf serialized object

Each variable has a *VariableRecords* object that keeps track of the
GRIB record used for that variable:

----------------------------------------------------------------------------------------------------------
message VariableRecords {
 required fixed32 cdmHash = 1; // which variable
 repeated Record records = 2;  // Record[ntimes*nvert*nens]
}

message Record {
 required uint32 fileno = 1;  // index into GribCollectionIndex.files
 required uint64 pos = 2;     // offset in Grib file of the start of drs (grib2) or entire message (grib1)
 optional bool missing = 3 [default = false]; // record is missing
}
----------------------------------------------------------------------------------------------------------

The *GribCollectionIndex* object has all the rest of the info. The
*GribCollection* is a collection of **Groups**:

---------------------------------------------------------------------------------
message GribCollectionIndex {
  required string name = 1;       // must be unique - index filename is name.ncx
  repeated string files = 2;      // list of grib files
  repeated Group groups = 3;      // separate groups for each GDS
  repeated Parameter params = 4;  // global attributes
  required int32 center = 5;      // these 4 fields are to get a GribTable object
  required int32 subcenter = 6;
  required int32 master = 7;
  required int32 local = 8;       // grib1 table Version
  optional int32 genProcessType = 10;
  optional int32 genProcessId = 11;
  optional int32 backProcessId = 12;


  repeated Partition partitions = 13;  // for time partitions only
}
---------------------------------------------------------------------------------

A *Group* is a collection of variables and coordinates. All the
variables use the same GDS:

-------------------------------------------------------------------------------------------------------------
message Group {
  optional int32 predefinedGds = 1;   // predefined GDS code, defined by center
  optional bytes gds = 2;             // all variables in the group use the same GDS
  repeated Variable variables = 3;    // list of variables
  repeated Coord timeCoords = 4;    // list of time coordinates
  repeated Coord vertCoords = 5;    // list of vert coordinates
  repeated Coord ensCoords = 6;     // list of ens coordinates
  repeated Parameter params = 7;    // group attributes
  repeated int32 fileno = 8;        // this is so we can show just the component files that are in this group


  repeated TimeCoordUnion timeCoordUnions = 9; // for time partitions only
  optional string name = 10;       // only when user overrides default name
  optional sint32 gdsHash = 11 [default = 0];
}
-------------------------------------------------------------------------------------------------------------

*Variable* object:

------------------------------------------------------------------------------------------------------------
message Variable {
 required int32 discipline = 1;
 required int32 category = 2;
 required int32 parameter = 3;
 required int32 levelType = 4;                     // table 4.5 (grib2); table 3 (grib1)
 optional int32 intervalType = 5 [default = -1];   // table 4.10 (grib2); table 5 (grib1)
 required fixed32 cdmHash = 6;


 required uint64 recordsPos = 7;  // offset of VariableRecords message for this Variable
 required uint32 recordsLen = 8;  // size of VariableRecords message for this Variable


 required uint32 timeIdx = 9;     // index into GribCollectionIndex.timeCoords
 optional int32 vertIdx = 10 [default = -1];   // index into GribCollectionIndex.vertCoords
 optional int32 ensIdx = 11 [default = -1];    // index into GribCollectionIndex.ensCoords


 // only one of 12, or 13 (and 11?)
 optional int32 ensDerivedType = 12 [default = -1];             // table 4.7
 optional string probabilityName = 13;
 optional int32 probabilityType = 14  [default = -1];           // table 4.9
 optional bool isLayer = 15 [default = false];

 repeated uint32 groupno = 16;  // only for partitions
 repeated uint32 varno = 17;
 repeated int32 flag = 21;

 // in case different from the GribCollectionIndex
 optional uint32 tableVersion = 18;      // grib1 table Version, grib2 local
 optional string intvName = 19;
 optional int32 genProcessType = 20  [default = -1];    // if set, then the generating process type was used
}
------------------------------------------------------------------------------------------------------------

The *VariableRecords* object for this variable is at *recordsPos* in the
ncx file, with *recordsLen* number of bytes.

The coordinates for the variable is represented by the *Coord* object in
the **Group**, and are shared whenever possible. Each variable has an
index in the array of time, vert, and ensemble coordinate. Each
coordinate is an array of values, and optionally bounds. The size of the
variable is found by looking at its coordinates.

----------------------------------------------------------------------------------------------
message Coord {
  required int32 code = 1;
  required string unit = 2;
  repeated float values = 3;
  repeated float bound = 4;                    // only used if interval, then = (value, bound)
  optional int32 index = 5  [default = -1];  // safety check
}
----------------------------------------------------------------------------------------------

'''''

== Time Partition Index File

A Time Partition divides the dataset into disjoint partitions of time.
Each Time Partition is just a Grib Collection. The overall time
partition index file has the following special features:

1.  The *VariableRecords* section is missing, delegated to the
individual grib collections.
2.  Each Variable tracks, for each partition, which group/variable it’s
using, i.e: groupno[partition], varno[partition] indexes.
3.  It uses extended time coordinates, which have [start, end) for each
partition:
+
-------------------------------------------------------------
message TimeCoordUnion extends Coord {
   repeated int32 partition = 5; // starting index, inclusive
   repeated int32 index = 6; // ending index, exclusive
 }
-------------------------------------------------------------
4.  It keeps track of the partition names:
+
-------------------------------------------------------------------------------------------------------------------------
message Partition {
  required string name = 1;       // name is used in TDS - eg the subdirectory when generated by TimePartitionCollections
  required string filename = 2;   // the gribCollection.ncx file
}
-------------------------------------------------------------------------------------------------------------------------

Currently we assume that, for each variable, its vertical coordinates
and ensemble coordinates are identical across partitions. These are
taken from the prototype dataset.

1.  If we passed in the vert, ens coord value, we could match for each
partition, returning missing values when needed.
2.  We could precompute the mapping when the overall index is
constructed.
3.  We could always use the vert, ens coordinates from prototype when
constructing each GribCollection partition. But we’d have to recompute
when proto changed.
4.  We could throw out that variable, or split in pieces.

Thi isnt a problem for GribCOllection, since all the records from all
the files a re thrown into the bag and rectilyser turns them into a
rectangular array with missing values if needed. It occurs because we
want to compute each Time Partition independent of the others, for
scalability.

'''''

== Notes (10/31/2012)

== simple

[cols=",,,",options="header",]
|=======================================================================
|dataset |catalogRef |name |path
|collection |  |name |path/__collection__

|individual files |path/__files/catalog.xml__ |filename
|path/__files__/filename
|=======================================================================

path = grib/NCEP/GFS/CONUS_191km

dataset catalog =
http://motherlode.ucar.edu:9080/thredds/catalog/grib/NCEP/GFS/CONUS_191km/catalog.html

server://thredds/catalog/path/catalog.xml

collection dataset
http://motherlode.ucar.edu:9080/thredds/catalog/grib/NCEP/GFS/CONUS_191km/catalog.html?dataset=grib/NCEP/GFS/CONUS_191km

best dataset
http://motherlode.ucar.edu:9080/thredds/catalog/grib/NCEP/GFS/CONUS_191km/catalog.html?dataset=grib/NCEP/GFS/CONUS_191km/collection

files catalog
http://motherlode.ucar.edu:9080/thredds/catalog/grib/NCEP/GFS/CONUS_191km/files/catalog.html

latest
http://motherlode.ucar.edu:8080/thredds/catalog/fmrc/NCEP/GFS/Alaska_191km/files/latest.html

== time partition

[cols=",,,",options="header",]
|=======================================================================
|dataset |catalogRef |name |path
|collection |path/__collection/catalog.xml__ |name
|path/name__/collection__

|partitions |path/partitionName__/catalog.xml__ |partitionName
|path/partitionName/__collection__

|individual files |path/partitionName/__files/catalog.xml__ |filename
|path/__files__/filename
|=======================================================================

path = grib/NCEP/GFS/Global_0p5deg

dataset catalog =
http://motherlode.ucar.edu:9080/thredds/catalog/grib/NCEP/GFS/Global_0p5deg/catalog.html

collection dataset =
http://motherlode.ucar.edu:9080/thredds/catalog/grib/NCEP/GFS/Global_0p5deg/catalog.html?dataset=grib/NCEP/GFS/Global_0p5deg

best dataset catalog =
http://motherlode.ucar.edu:9080/thredds/catalog/grib/NCEP/GFS/Global_0p5deg/collection/catalog.html

best dataset =
http://motherlode.ucar.edu:9080/thredds/catalog/grib/NCEP/GFS/Global_0p5deg/collection/catalog.html?dataset=grib/NCEP/GFS/Global_0p5deg/GFS-Global_0p5deg/collection

partition catalog =
http://motherlode.ucar.edu:9080/thredds/catalog/grib/NCEP/GFS/Global_0p5deg/GFS-Global_0p5deg_20121010/catalog.html

partition dataset =
http://motherlode.ucar.edu:9080/thredds/catalog/grib/NCEP/GFS/Global_0p5deg/GFS-Global_0p5deg_20121010/catalog.html?dataset=grib/NCEP/GFS/Global_0p5deg/GFS-Global_0p5deg_20121010/collection

partittion files catalog =
http://motherlode.ucar.edu:9080/thredds/catalog/grib/NCEP/GFS/Global_0p5deg/GFS-Global_0p5deg_20121010/files/catalog.html

partittion files =
http://motherlode.ucar.edu:9080/thredds/catalog/grib/NCEP/GFS/Global_0p5deg/GFS-Global_0p5deg_20121010/files/catalog.html?dataset=grib/NCEP/GFS/Global_0p5deg/files/GFS_Global_0p5deg_20121010_0000.grib2

 

== multiple groups

[cols=",,,",options="header",]
|=======================================================================
|dataset |catalogRef |name |path
|group collection |  |groupName____ |path/groupName/__collection__

|individual files |path/groupName/__files/catalog.xml__ |filename
|path/__files__/filename
|=======================================================================

== time partition and groups

[cols=",,,",options="header",]
|=======================================================================
|dataset |catalogRef |name |path
|overall collection for group |path/groupName/__collection/catalog.xml__
|groupName |path/name/groupName

|collection for partition and group |path/partitionName__/catalog.xml__
|groupName |path/partitionName/groupName

|individual files |path/partitionName/groupName/__files/catalog.xml__
|partitionName/filename |path/__files__/filename
|=======================================================================

 

'''''

== 11/7/2012

== simple

-----------------------------------------------------------------------------------------------------------------------------
<featureCollection name="GFS-CONUS_191km" featureType="GRIB" harvest="true" path="grib/NCEP/GFS/CONUS_191km">
  <metadata inherited="true">
   <dataFormat>GRIB-1</dataFormat>
  </metadata>
  <collection spec="/data/ldm/pub/native/grid/NCEP/GFS/CONUS_191km/GFS_CONUS_191km_#yyyyMMdd_HHmm#.grib1" olderThan="5 min"/>
  <tdm startup="true" rescan="0 0/15 * * * ? *" trigger="allow"/>
</featureCollection>
-----------------------------------------------------------------------------------------------------------------------------

[width="100%",cols="20%,20%,20%,20%,20%",options="header",]
|=======================================================================
|dataset |url |type |example |NetCDF Object
|overall |server__://thredds/catalog__/path__/catalog.xml__ |catalog
|http://localhost:8080/thredds/catalog/grib/NCEP/GFS/Puerto_Rico_0p5deg/catalog.html
| 

|collection |cat?__dataset__=path/__collection (no access)__ |dataset
|cat?dataset=grib/NCEP/GFS/Puerto_Rico_0p5deg/collection |none

|best |cat?__dataset__=path/__best__ |dataset
|cat?dataset=grib/NCEP/GFS/Puerto_Rico_0p5deg/best |collection.ncx

|files catalog |path__/files/catalog.xml__ |catalog
|http://localhost:8080/thredds/catalog/grib/NCEP/GFS/Puerto_Rico_0p5deg/files/catalog.html
| 

|individual files |fcat?__dataset__=path/__files__/filepath |dataset
|fcat?dataset=grib/NCEP/GFS/Puerto_Rico_0p5deg/files/GFS_Puerto_Rico_0p5deg_20111116_0000.grib2
|file.ncx

|latest file catalog |path__/files/latest.xml__ |catalog
|http://localhost:8080/thredds/catalog/grib/NCEP/GFS/Puerto_Rico_0p5deg/files/latest.html
| 
|=======================================================================

== groups

[width="100%",cols="20%,20%,20%,20%,20%",options="header",]
|=======================================================================
|dataset |url |type |example |NetCDF Object
|overall |server__://thredds/catalog__/path__/catalog.xml__ |catalog
|http://localhost:8080/thredds/catalog/grib/carlosMoraga/catalog.html | 

|collection |cat?__dataset__=path/__collection (no access)__ |dataset
|cat?dataset=grib/carlosMoraga/collection |none

|group best |cat?__dataset__=path/group/__best__ |dataset
|cat?dataset=grib/carlosMoraga/domain1/best |collection(group).ncx

|group files catalog |path__/group/files/catalog.xml__ |catalog
|http://localhost:8080/thredds/catalog/grib/carlosMoraga/domain1/files/catalog.html
| 

|individual files |fcat?__dataset__=path/group/__files__/filepath
|dataset
|fcat?dataset=grib/carlosMoraga/files/ECMWF_GNERA_d0001.20121001
|file.ncx

|latest file catalog |path__/__group__/files/__latest.xml____ |catalog
|http://localhost:8080/thredds/catalog/grib/carlosMoraga/domain1/files/latest.html
| 
|=======================================================================

== time partition

path -> path/partitionName

[cols=",,,,",options="header",]
|=======================================================================
|dataset |url |type |example |NetCDF Object
|overall |server__://thredds/catalog__/path__/catalog.xml__ |catalog
|http://localhost:8080/thredds/catalog/grib/NCEP/GFS/Global_0p5deg/catalog.html
| 

|collection |cat?__dataset__=path/__collection (no access)__ |dataset
|cat?dataset=grib/NCEP/GFS/Global_0p5deg/collection |none

|best overall |cat?__dataset__=path/__best__ |dataset
|cat?dataset=grib/NCEP/GFS/Global_0p5deg/best |collectionName.ncx

|latest overall file |path__/files/__latest.xml____ |catalog
|http://localhost:8080/thredds/catalog/grib/NCEP/GFS/Global_0p5deg/files/latest.html
| 

|partition catalog
|server__://thredds/catalog__/path__/__partitionName__/catalog.xml__
|catalog
|http://localhost:8080/thredds/catalog/grib/NCEP/GFS/Global_0p5deg/20120518/catalog.html
| 

|best in partition |pcat?__dataset__=path/partitionName/__best__
|dataset |pcat?dataset=grib/NCEP/GFS/Global_0p5deg/20120518/best
|partitionName.ncx

|partition files catalog |path/partitionName__/files/catalog.xml__
|catalog
|http://localhost:8080/thredds/catalog/grib/NCEP/GFS/Global_0p5deg/20120518/files/catalog.html
| 

|individual files |pfcat?__dataset__=path/__files__/filepath |dataset
|pfcat?dataset=grib/NCEP/GFS/Global_0p5deg/files/GFS_Global_0p5deg_20120518_0000.grib2
|file.ncx
|=======================================================================

== time partition with groups

path -> path/partition/group ??

[cols=",,,,",options="header",]
|=======================================================================
|dataset |url |type |example |NetCDF Object
|overall |server__://thredds/catalog__/path__/catalog.xml__ |catalog
|http://localhost:8080/thredds/catalog/grib/NCDC/CFSR/catalog.html | 

|collection |cat?__dataset__=path/__collection (no access)__ |dataset
|cat?dataset=grib/NCDC/CFSR/collection |none

|best catalog |path/__best/catalog.xml__ |catalog
|http://localhost:8080/thredds/catalog/grib/NCDC/CFSR/grib/NCDC/CFSR/best/catalog.html
| 

|group best |bcat?__dataset__=path/group/__best__ |dataset
|bcat?dataset=grib/NCDC/CFSR/FLX-GaussianT382/best
|collectionName(group).ncx

|latest file in group |path__/files/__latest.xml____ |catalog |NOT DONE
| 

|partition catalog
|server__://thredds/catalog__/path__/__partitionName__/catalog.xml__
|catalog
|http://localhost:8080/thredds/catalog/grib/NCDC/CFSR/200808/catalog.html
| 

|best in partition, group
|pcat?__dataset__=path/partitionName/group/__best__ |dataset
|pcat?dataset=grib/NCDC/CFSR/200808/FLX-GaussianT382/best
|partitionName(group).ncx

|partition, group files catalog
|path/partitionName/group__/files/catalog.xml__ |catalog
|http://localhost:8080/thredds/catalog/grib/NCDC/CFSR/200808/FLX-GaussianT382/files/catalog.html
| 

|individual files |pgfcat?__dataset__=path/__files__/filepath |dataset
|pgfcat?dataset=grib/NCDC/CFSR/files/200808/dlwsfc.l.gdas.200808.grb2
|file.ncx
|=======================================================================

 

'''''

== VariableMap

* uses MetadataController
* DatasetHandler.openGridDataset(req, res, path)
* MetadataExtractor.extractVariables()
* collection could use best

== TimeRange / Spatial Extant

* need to keep persistant Object cache.

'''''

== 01/04/2014

== GribCollections, version 2

-----------------------------------------------------------------------------------------------------------------------------
<featureCollection name="GFS-CONUS_191km" featureType="GRIB2" harvest="true" path="grib/NCEP/GFS/CONUS_191km">
  <metadata inherited="true">
   <dataFormat>GRIB-1</dataFormat>
  </metadata>
  <collection spec="/data/ldm/pub/native/grid/NCEP/GFS/CONUS_191km/GFS_CONUS_191km_#yyyyMMdd_HHmm#.grib1" olderThan="5 min"/>
  <tdm startup="test" rescan="0 0/15 * * * ? *" trigger="allow"/>
</featureCollection>
-----------------------------------------------------------------------------------------------------------------------------

== File Partition, no groups

[cols=",,,,",options="header",]
|=======================================================================
|dataset |url |type |example |NetCDF Object
|overall |server__://thredds/catalog__/path__/catalog.xml__ |catalog
|http://localhost:8080/thredds/catalog/grib/NCEP/GFS/Puerto_Rico_0p5deg/catalog.html
| 

|TwoD |cat?__dataset__=path/__TwoD__ |dataset
|cat?dataset=grib/NCEP/DGEX/CONUS_12km/TwoD |collection.ncx2

|Best |cat?__dataset__=path/__Best__ |dataset
|cat?dataset=grib/NCEP/DGEX/CONUS_12km/Best |collection.ncx2

|latest |path__/files/__latest.xml____ |catalog
|http://localhost:8080/thredds/catalog/grib/NCEP/DGEX/CONUS_12km/files/latest.html
| 

|files catalog |path__/files/catalog.xml__ |catalog
|http://localhost:8080/thredds/catalog/grib/NCEP/GFS/Puerto_Rico_0p5deg/files/catalog.html
| 

|individual files |fcat?__dataset__=path/__files__/filepath |dataset
|http://localhost:8080/thredds/catalog/grib/NCEP/DGEX/CONUS_12km/DGEX_CONUS_12km_20131204_1800.grib2/catalog.html
|file.ncx
|=======================================================================

== Grib Collection, with groups

[width="100%",cols="20%,20%,20%,20%,20%",options="header",]
|=======================================================================
|dataset |url |type |example |NetCDF Object
|overall |server__://thredds/catalog__/path__/catalog.xml__ |catalog
|http://localhost:8080/thredds/catalog/grib/carlosMoraga/catalog.html | 

|collection |cat?__dataset__=path/__collection (no access)__ |dataset
|cat?dataset=grib/carlosMoraga/collection |none

|group best |cat?__dataset__=path/group/__best__ |dataset
|cat?dataset=grib/carlosMoraga/domain1/best |collection(group).ncx

|group files catalog |path__/group/files/catalog.xml__ |catalog
|http://localhost:8080/thredds/catalog/grib/carlosMoraga/domain1/files/catalog.html
| 

|individual files |fcat?__dataset__=path/group/__files__/filepath
|dataset
|fcat?dataset=grib/carlosMoraga/files/ECMWF_GNERA_d0001.20121001
|file.ncx

|latest file catalog |path__/__group__/files/__latest.xml____ |catalog
|http://localhost:8080/thredds/catalog/grib/carlosMoraga/domain1/files/latest.html
| 
|=======================================================================

== partition collection

path -> path/partitionName

[cols=",,,,",options="header",]
|=======================================================================
|dataset |url |type |example |NetCDF Object
|overall |server__://thredds/catalog__/path__/catalog.xml__ |catalog
|http://localhost:8080/thredds/catalog/grib/NCEP/GFS/Global_0p5deg/catalog.html
| 

|collection |cat?__dataset__=path/__collection (no access)__ |dataset
|cat?dataset=grib/NCEP/GFS/Global_0p5deg/collection |none

|best overall |cat?__dataset__=path/__best__ |dataset
|cat?dataset=grib/NCEP/GFS/Global_0p5deg/best |collectionName.ncx

|latest overall file |path__/files/__latest.xml____ |catalog
|http://localhost:8080/thredds/catalog/grib/NCEP/GFS/Global_0p5deg/files/latest.html
| 

|partition catalog
|server__://thredds/catalog__/path__/__partitionName__/catalog.xml__
|catalog
|http://localhost:8080/thredds/catalog/grib/NCEP/GFS/Global_0p5deg/20120518/catalog.html
| 

|best in partition |pcat?__dataset__=path/partitionName/__best__
|dataset |pcat?dataset=grib/NCEP/GFS/Global_0p5deg/20120518/best
|partitionName.ncx

|partition files catalog |path/partitionName__/files/catalog.xml__
|catalog
|http://localhost:8080/thredds/catalog/grib/NCEP/GFS/Global_0p5deg/20120518/files/catalog.html
| 

|individual files |pfcat?__dataset__=path/__files__/filepath |dataset
|pfcat?dataset=grib/NCEP/GFS/Global_0p5deg/files/GFS_Global_0p5deg_20120518_0000.grib2
|file.ncx
|=======================================================================

== time partition with groups

path -> path/partition/group ??

[cols=",,,,",options="header",]
|=======================================================================
|dataset |url |type |example |NetCDF Object
|overall |server__://thredds/catalog__/path__/catalog.xml__ |catalog
|http://localhost:8080/thredds/catalog/grib/NCDC/CFSR/catalog.html | 

|collection |cat?__dataset__=path/__collection (no access)__ |dataset
|cat?dataset=grib/NCDC/CFSR/collection |none

|best catalog |path/__best/catalog.xml__ |catalog
|http://localhost:8080/thredds/catalog/grib/NCDC/CFSR/grib/NCDC/CFSR/best/catalog.html
| 

|group best |bcat?__dataset__=path/group/__best__ |dataset
|bcat?dataset=grib/NCDC/CFSR/FLX-GaussianT382/best
|collectionName(group).ncx

|latest file in group |path__/files/__latest.xml____ |catalog |NOT DONE
| 

|partition catalog
|server__://thredds/catalog__/path__/__partitionName__/catalog.xml__
|catalog
|http://localhost:8080/thredds/catalog/grib/NCDC/CFSR/200808/catalog.html
| 

|best in partition, group
|pcat?__dataset__=path/partitionName/group/__best__ |dataset
|pcat?dataset=grib/NCDC/CFSR/200808/FLX-GaussianT382/best
|partitionName(group).ncx

|partition, group files catalog
|path/partitionName/group__/files/catalog.xml__ |catalog
|http://localhost:8080/thredds/catalog/grib/NCDC/CFSR/200808/FLX-GaussianT382/files/catalog.html
| 

|individual files |pgfcat?__dataset__=path/__files__/filepath |dataset
|pgfcat?dataset=grib/NCDC/CFSR/files/200808/dlwsfc.l.gdas.200808.grb2
|file.ncx
|=======================================================================

01/10/2014

FileCollection is always a PC, with individual files being GC; all the
files is a directory. could genralize to span directories.
spec=path/[filter], partition=file

DirectoryCollection is a GC; all the files in a single directory.
spec=directory:path[/filter]

DirectoryPartition is a PC, with DirectoryCollections at its leaves. may
be nested (i hope). but when do we know if we are at the leaves?
partition=directory

01/14/14

partition=file, directory

otherwise, use

 

While we think that generally the 4.3 GRIB reading is correct, we have
been unsatisfied with the way that reference time was handled there;
this affects files (or collections of files) that have more than one
reference time, with the same valid time. A coming version of the
netcdf-java library (4.5) has another refactor in which these datasets
expose both reference time and valid time. This allows users to see all
of the data in the file. This version will be out as alpha in the next
few weeks.

 

<update startup=``true'' rewrite=``never'' trigger="allow />

<tdm startup=``test'' rewrite=``nocheck'' scan=``'' trigger="allow />

if tdm is defined, default is:

<update startup=``true'' rewrite=``never'' trigger="allow />

 

so, tds no longer supports scan, or recheckAfter.

force a rewite on startup with

<tdm startup=``always'' rewrite=``nocheck'' scan=``'' trigger="allow />

 

02/10/2014

index = gcname + ``.ncx''

*partition = none*

* make a CollectionManager for the collectionSpec set of files.
* if multiple runtimes, make seperate GC for each one, make a PC that
puts them together. GC name= collectionName + runtime, PC =
collectionName.
* if single runtime, GC = collectionName

A partition divides the files into a tree of collections

*partition = directory*

* use the directory tree as the partition
* gcname = collectionName + directory

*partition = file*

* use the directory tree and the individual files as the partition
* gcname = collectionName = filename

3/6/2014

* catalogs +
 * path/catalog.xml // top catalog +
 * path/partitionName/catalog.xml +
 * path/partitionName/../partitionName/catalog.xml +
 * path/latest.xml // latest (resolver) +
 * +
 * datasets +
 * path/dataset (BEST, TWOD, GC) // top collection, single group +
 * path/dataset/groupName // top collection, multiple group +
 * path/partitionName/dataset // partition, single group +
 * path/partitionName/../partitionName/dataset +
 * path/partitionName/dataset/groupName // partition, multiple group +
 * path/partitionName/../partitionName/dataset/groupName

[cols=",,,,",options="header",]
|=======================================================================
|dataset |url |type |example |NetCDF Object
|overall |server__://thredds/catalog__/path__/catalog.xml__ |catalog
|http://localhost:8080/thredds/catalog/cfsr-hpr-ts45/catalog.html | 

|top collection, single group |cat?__dataset__=path/dataset (BEST, TWOD,
GC) |dataset |cat?dataset=grib/NCEP/DGEX/CONUS_12km/TwoD |none

|top collection, multiple group |cat?__dataset__=path/dataset/groupName
|dataset |cat?dataset=cfsr-hpr-ts45/TwoD/LatLon_360X720-p25S-179p7W | 

|group best |bcat?__dataset__=path/group/__best__ |dataset
|bcat?dataset=grib/NCDC/CFSR/FLX-GaussianT382/best
|collectionName(group).ncx

|latest collection |path__/__latest.xml____ |catalog
|http://localhost:8080/thredds/catalog/cfsr-hpr-ts45/latest.html | 

|partition catalog |path/partitionName/../partitionName/catalog.xml
|catalog
|http://localhost:8080/thredds/catalog/cfsr-hpr-ts45/cfsr-hpr-ts45-1999/catalog.html
| 

|best in partition, group
|pcat?__dataset__=path/partitionName/group/__best__ |dataset
|pcat?dataset=grib/NCDC/CFSR/200808/FLX-GaussianT382/best
|partitionName(group).ncx

|partition, group files catalog
|path/partitionName/group__/files/catalog.xml__ |catalog
|http://localhost:8080/thredds/catalog/grib/NCDC/CFSR/200808/FLX-GaussianT382/files/catalog.html
| 

|individual files |pgfcat?__dataset__=path/__files__/filepath |dataset
|pgfcat?dataset=grib/NCDC/CFSR/files/200808/dlwsfc.l.gdas.200808.grb2
|file.ncx
|=======================================================================
