:source-highlighter: coderay
[[threddsDocs]]

= Implementation of latest dataset

1)

Original design of latest was a ``Resolver''service type, in which for
some URL, say

*<service name=``latest'' type=``Resolver'' base=``'' />* +
 *<dataset name=``latestComplete.xml'' serviceName=``latest''
urlPath=``latestComplete.xml'' />*

this URL resolves simply to <base>/**latestComplete.xml**

which is a catalog with a single dataset in it, namely the latest one,
for example :

----------------------------------------------------------------------------------------------------------------
<catalog ...>
  <service ...>
  <dataset name="Latest File_Access" ID="fmrc/NCEP/GFS/Alaska_191km/files/GFS_Alaska_191km_20121105_1800.grib1" 
         urlPath="fmrc/NCEP/GFS/Alaska_191km/files/GFS_Alaska_191km_20121105_1800.grib1">
   ...
</catalog>

----------------------------------------------------------------------------------------------------------------

2)

Feature Collection knows what datasets are in it, so we could skip the
resolver type and just use a logical URL like

*<dataset name=``latest file'' serviceName=``usual''
urlPath=``path/latest'' />*

-------------------------
fcat?dataset=path/latest
-------------------------

however you would have to propagate latest processing to all services.

\3) or you could generate latest at the time of the catalog:

<dataset name=``Latest
File_Access'' ID=``fmrc/NCEP/GFS/Alaska_191km/files/GFS_Alaska_191km_20121105_1800.grib1'' 
urlPath=``fmrc/NCEP/GFS/Alaska_191km/files/GFS_Alaska_191km_20121105_1800.grib1''>

but then you dont have a logical URL that you can embed in an (ahem) IDV
bundle.

 

fcat__?dataset__=path/__latest__

4)

currently, latest.xml URL is grabbed at

---------------------------------
DataRootHandler.getMatchingScan()

---------------------------------

by having a

--------------------------------------------------------------------
reqDataRoot.featCollection.getRawFileScan()
and returning a ProxyDatasetHandler
InvCatalogImpl cat = scan.makeProxyDsResolverCatalog(path, baseURI);
--------------------------------------------------------------------

problem is we dont really want to leave it up to a datasetScan object to
implement latest. It should be handled directly by the FC.
