:source-highlighter: coderay
[[threddsDocs]]


Untitled Document
=================

== NCSS REST Design

_note: needs updating as of 3/2015_

=== 1. What are the resources/URIs?

The resources are THREDDS datasets. The resource URIs can be discovered
in a
<<../../../../archive/src/docs/web/thredds/tech/TDS#Catalogs,THREDDS
catalog>>, by looking for datasets that use the *NetcdfSubset* Service
type. Generally these resource URLs look like:

__________________________________________________________
*http://servername:8080/thredds/ncss/\{path/dataset}*

*http://servername:8080/thredds/ncss/grid/\{path/dataset}*
__________________________________________________________

Typically the user wants a link:#subset[subset] of the dataset.This is
considered a _view_ of a resource, rather than a separate resource:

_______________________________________________________________
*http://servername:8080/thredds/ncss/\{path/dataset}?\{subset}*
_______________________________________________________________

A desired _link:#representation[representation]_ of the resource is
specified using the *accept* parameter. Again, different representations
are not considered separate resources. Following the *Accept* HTTP
header, accept takes a comma delimited list of mime-types (or aliases),
but does not allow wild cards (*) or q parameters.

___________________________________________________________________________________
*http://servername:8080/thredds/ncss/\{path/dataset}?\{subset}&accept=\{mime-type}*
___________________________________________________________________________________

=== *2. What’s the format/representation?*

The dataset itself has two representations:

an XML file describing the dataset, called the
link:#DatasetDescription[Dataset Description]

* *http://servername:8080/thredds/ncss/\{path/dataset}/dataset.xml*

An HTML form to allow interactive user input:

* *http://servername:8080/thredds/ncss/\{path/dataset}/dataset.html*

Results of a subset request can be:

* *a netCDF binary file*
** http://servername:8080/thredds/ncss/\{path/dataset}?\{subset}&**accept=application/x-netcdf**
* *an XML document*
** http://servername:8080/thredds/ncss/\{path/dataset}?\{subset}&**accept=application/xml**
* *ASCII text*
** http://servername:8080/thredds/ncss/\{path/dataset}?\{subset}&**accept=text/plain**
* *Excel CSV (comma separated values)*
** http://servername:8080/thredds/ncss/\{path/dataset}?\{subset}&**accept=text/csv**

1.  The netCDF binary file will be encoded using
http://www.cgd.ucar.edu/cms/eaton/cf-metadata/[CF conventions] when
possible, and when not possible, the encoding will be submitted to CF
for approval.
2.  The XML, ASCII, and CSV files are intended for use only for small
extractions of data, and are generally missing some or all of the
metadata of the dataset.
3.  Multiple accept values can be specified, eg *accept=xml,csv* (comma
delimited, no spaces). The server will select from that list.

*Representation types*

[cols=",",options="header",]
|============================
|Mime Type |Synonyms
|text/plain |raw, ascii
|application/xml |xml
|text/csv |csv
|text/html |html
|application/x-netcdf |netcdf
|============================

 

=== 3. What are the Methods?

_______________________________
Only the GET method is allowed.
_______________________________

=== 4. What Status codes can be returned?

* 200 : success
* 307 : redirect to an authorization challenge
* 400 : malformed request
* 401 : authorization challenge
* 404 : unknown resource
* 501 : request requires too much server resources / data result would
be too large

=== REST Resources:

* http://www.xml.com/pub/a/2004/08/11/rest.html[Implementing REST Web
Services: Best Practices and Guidelines]
