:source-highlighter: coderay
[[threddsDocs]]

= THREDDS Catalogs

THREDDS Catalogs are logical directories of on-line data resources,
encoded as http://www.w3.org/TR/REC-xml/[XML documents], which provide a
place for annotations and other metadata about the data resources to
reside. This is how THREDDS-enabled data consumers find out what data is
available from data providers.

THREDDS Catalogs were originally designed for _clients_ to use to
access remote data. They have been extended to allow the TDS to use them
for its own configuration. In this mode they are called *_TDS
Configuration Catalogs_*, or *_server-side Catalogs_*. They
contain information needed only on the server, which is removed when the
TDS sends the catalog to the client, called the *_client-side catalog_*.

For client-side catalogs, see:

* <<InvCatalogSpec#,Catalog specification>> is an annotated XML Schema that explains the details of THREDDS Catalogs.
* The XML Schema document: http://www.unidata.ucar.edu/schemas/thredds/InvCatalog.1.0.7.xsd[Online catalog schema].
* <<../tutorial/CatalogPrimer#,Catalog Primer>>
* The <<../../netcdf-java/documentation#,Java NetCDF library>> has a complete package (thredds.client.catalog) to parse client-side catalogs.
* [Syphon] is a python library that includes catalog parsing.

The TDS dynamically generates THREDDS catalogs based on the TDS
configuration catalogs. For server-side catalogs, see:

* <<InvCatalogServerSpec#,Server-side Catalog Specification>>
* <<../tutorial/index#,THREDDS Data Server Administration Tutorial>>
