:source-highlighter: coderay
[[threddsDocs]]

= TDS Installation Checklist for Production (Reference)

== Initial Installation

=== Install Java

1.  Download and install the http://www.oracle.com/technetwork/java/javase/downloads/index.html[latest version of Java 8+]

=== Tomcat Install

Create a dedicated user and group for running Tomcat who does not have root privileges.

As this user, download and install the http://tomcat.apache.org/[latest version of Tomcat 8+].

In *$\{tomcat_home}/bin* create a *setenv.sh* shell script, and set
the values of *JAVA_HOME* and *CATALINA_BASE* and *CATALINA_OPTS*. These
each have to be customized to your installation. For example:

-------------------------------------------------------------
#!/bin/sh

JAVA_HOME="/usr/local/jdk1.8.0_66"
export JAVA_HOME

CATALINA_BASE="/usr/local/tomcat"
export CATALINA_BASE

CONTENT_DIR= "/opt/local/tds/content"
NORMAL="-Xmx4g -Xms512m -server"
HEADLESS="-Djava.awt.headless=true"
JAVA_PREFS="-Djava.util.prefs.systemRoot=$CONTENT_DIR/thredds/javaUtilPrefs -Djava.util.prefs.userRoot=$CONTENT_DIR/thredds/javaUtilPrefs"

# other Java options you might need
JAVA_OPTS="-Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true"

CATALINA_OPTS="$NORMAL -Dtds.content.root.path=$CONTENT_DIR/ $HEADLESS $JAVA_PREFS $JAVA_OPTS"
export CATALINA_OPTS
-------------------------------------------------------------

(You can use JAVA_OPTS instead of CATALINA_OPTS, but JAVA_OPTS is used for any Java program, and CATALINA_OPTS is only used by Tomcat.)

Create the directory
*$CONTENT_DIR/thredds/javaUtilPrefs/.systemPrefs* and make sure it is writeable by the user running Tomcat
(<<../faq#javaUtilPrefs,details>>). +

Purchase a real certificate from a http://en.wikipedia.org/wiki/Certificate_authority[certificate
authority], so users are not confused and question the legitimacy of your web site.

1. *Make the following modifications to $\{tomcat_home}/conf/server.xml*:

. <<../tutorial/Security#digested,Enable digest passwords>> by
commenting out the *UserDatabaseRealm* and enabling the **MemoryRealm**.
. <<../tutorial/Security#ssl,Enable SSL>> by uncommenting the SSL
Connector listening on port 8443, and add the required *keystoreFile*
and *keystorePass* attributes.
. <<../reference/Performance#enableCompression,Enable compression>>
by adding *compression* and *compressableMimeType*
attributes to 8080 Connector.
. <<../tutorial/TDSMonitoringAndDebugging#access,Enable access logging>>
by uncommenting the *AccessLogValve* and change the *prefix*
and *suffix* and *pattern* attributes.

2. For each user, create a SHA1 password digest using the
*$\{tomcat_home}/bin/digest.sh* script or an online service such as
http://www.freeformatter.com/message-digest.html

3. *Make the following modifications to $\{tomcat_home}/conf/tomcat-users.xml*:

. Define the roles
<<../tutorial/GettingStarted#grantingAccess,manager-gui>>,
<<../tutorial/examples/accessingTDSMonitoringAndDebuggingTools#,tdsConfig>> and (optionally)
<<../tutorial/examples/accessingTDSMonitoringAndDebuggingTools#,tdsMonitor>>.
. <<../tutorial/GettingStarted#grantingAccess,Add yourself as a user>>
with the roles manager-gui and tdsConfig using your digest
password your created in step #6 above.

4. *Make the following modifications to $\{tomcat_home}/webapps/manager/WEB-INF/web.xml*:

.  Make sure the manager is only <<../tutorial/examples/tomcatManagerSSL#,available via SSL>> by
adding a user-data-constraint with a transport-guarantee of CONFIDENTIAL
inside the security-constraint element.
.  DO NOT ENABLE THE MANAGER WITHOUT RESTRICTING TO SSL ACCESS ONLY. (!)

5. <<../tutorial/Security#unused,Remove any unused applications>>
from $\{tomcat_home}/webapps.

6. (optional) <<../../netcdf-java/reference/netcdf4Clibrary#,Build
netCDF-C library>> on your server. Standard install directory is
*/opt/netcdf.*

=== TDS Install

<<../tutorial/GettingStarted#deploying,Download>> the latest
thredds.war file, and put it into **$\{tomcat_home}/webapps**.

Start/restart Tomcat so that it has a chance to create initial files in
*$\{tomcat_home}/content/thredds* (optional).

Modify *$\{tomcat_home}/content/thredds/catalog.xml* for your site, as
in this
<<../tutorial/BasicConfigCatalogs#exampleCatalog,example>>.

Modify  **$\{tomcat_home}/content/thredds/threddsConfig.xml** for your
site in the following manner:

* Add the needed information to the <<../tutorial/BasicThreddsConfig_xml#serverInfo,serverInformation element>>
* <<../tutorial/AddingServices#,Enable any other optional services>> like WMS or WCS.

If needed, <<../tutorial/Security#access,limit access to the
TDS>> and create a robots.txt file in *$\{tomcat_home}/webapps/ROOT/* to
restrict crawler activity.

 
== Maintenance and Upgrades

=== Maintenance

*Be sure to periodically check to make sure you are running the
<<../tutorial/Security#versions,latest versions>> of Java, Tomcat
and the TDS.*

* If you have enabled
<<../tutorial/TomcatAndTDSLogs#access,access logging>> (and you
should), zip up the unused access logs in *$\{tomcat_home}/logs/* and
archive them off to another directory.
* Likewise, zip up the unused
<<../tutorial/TomcatAndTDSLogs#tds,TDS servlet logs>> in
*$\{tomcat_home}/content/thredds/logs* and archive them as well.

=== Upgrading the TDS

When installing a new thredds.war, everything in
*$\{tomcat_home}/webapps/* is overwritten. However, nothing in
*$\{tomcat_home}/content/* is overwritten.

Use one of the following methods to deploying a new version of the TDS

* <<../tutorial/GettingStarted#manager,Tomcat manager application>>
* <<../tutorial/GettingStarted#deploying,manual installation>>
