:source-highlighter: coderay
[[threddsDocs]]

= Recommended Process for Upgrading a TDS

When upgrading a THREDDS Data Server (TDS), it is important to fully
undeploy the running TDS before deploying the new TDS. Not doing so can
cause conflicts between old and new Java classes and/or JSP pages (among
other things). The reason for this is that Tomcat and other webapp
containers have working directories [link:#noteWorkDir[1]] of some kind
in which to keep files they need (like compiled JSP pages).

So, here is the process we follow when we upgrade the TDS on our systems
(we use Tomcat, but the process should be similar for other webapp
containers):

1.  Use the Tomcat manager app [link:#noteManagerUrl[2]] to undeploy the TDS
2.  Shutdown Tomcat [link:#noteStopStart[3]]
3.  Clean up any log files [link:#noteLogCleanup[4]]
4.  Startup Tomcat
5.  Use the Tomcat manager to deploy the new TDS

== Notes

1.  work/Catalina/localhost/thredds
2.  https://server:port/manager/html/
3.  One reason to stop-and-restart Tomcat, besides cleaning up log files
(some of which Tomcat keeps open), is to avoid the PermGen memory error
mentioned <<../tutorial/BasicTomcatAndTDSSecurity#,here>>
4.  The Tomcat and TDS log files we clean up when upgrading:
* In $\{TOMCAT_HOME}/logs/*
* In $\{TOMCAT_HOME}/content/thredds/logs/*
+
where $\{TOMCAT_HOME} is the directory in which Tomcat is installed.

