:source-highlighter: coderay
[[threddsDocs]]

= Running TDS Behind a Proxy Server

== About Reverse Proxies

View the http://en.wikipedia.org/wiki/Reverse_proxy[Wikipedia entry on
Reverse Proxies] for more information on reverse proxies uses and types
of proxies servers.

=== Uses of reverse proxies

* A reverse proxy is a proxy server that appears to clients to be an
ordinary server. Requests are forwarded to one or more origin servers
which handle the request. The response is returned as if it came
directly from the proxy server.
* Reverse proxies can be used to hide the existence and characteristics
of the origin server(s) and can be an additional layer of defense and
can protect against some OS and WebServer specific attacks. However, it
does not provide any protection to attacks against vulernabilities in
the web application or proxy service itself (e.g., Apache, Tomcat).
* A reverse proxy can also be used for load balancing, caching content,
content compression, and SSL acceleration.

== Setting Up A Reverse Proxy For The TDS

=== Using Tomcat and Apache HTTP Server

Using Apache as a front-end proxy server for the TDS running on Tomcat
is perhaps the easiest method for setting up a reverse proxy for the
TDS. There are two methods to accomplish this:

* Apache's *_mod_proxy_* in combination with Tomcat’s HTTP connector; or
* the *_mod_jk_* Apache module with the Tomcat AJP connector.

*Warning!* It is important to carefully configure your proxy so that the
existence of the proxy is transparent to the end-user/client. For
instance, when a web application (e.g., the TDS) on the backend server
includes a link:#chgContextPath[self-referential URL] in some response
content, it should use the proxy server’s name and port rather than
those of the backend server.

=== Tomcat-Apache Proxy Documentation

http://tomcat.apache.org/tomcat-8.0-doc/connectors.html[Tomcat
Connectors] +
 Documentation describing the difference between the Tomcat HTTP and AJP
connectors.

`mod_proxy`

* http://tomcat.apache.org/tomcat-8.0-doc/config/http.html[Tomcat HTTP
Connector] +
 Configuration for the Tomcat HTTP connector (for use with Apache’s
`mod_proxy`).
* http://tomcat.apache.org/tomcat-8.0-doc/proxy-howto.html[Tomcat Proxy
Support - How To] +
 Tomcat documentation showing how to use the build-in Apache module
`mod_proxy` for Apache versions 1.3X and 2.X.

`mod_jk`

* http://tomcat.apache.org/tomcat-8.0-doc/config/ajp.html[Tomcat AJP
Connector] +
 Configuration for the Tomcat AJP connector (for use with Apache’s
`mod_jk`).
* http://tomcat.apache.org/connectors-doc/generic_howto/proxy.html[Tomcat
Reverse Proxy - How To] +
 Configurations and fine tuning of a reverse proxy set up using the
`mod_jk` Apache module.

=== Changing the TDS Context Path ( `/thredds` )

*We do not recommend* changing the TDS context path (the
`       /thredds     ` part of the URL path). However, if your network
configuration requires that you use a different context path (e.g.,
`       /my/thredds     `) or you are proxying two TDS installations and
need to differentiate them with different context paths (e.g.,
`       /thredds1     ` and `       /thredds2     `), you will need to
make the following changes:

1.  Rename the `thredds.war` file to match the desired context path
before you deploy it to Tomcat.
2.  Edit the TDS `web.xml` file and change the value of the
``ContextPath'' parameter to match the desired context path.
3.  Edit your TDS configuration catalogs and change the service base
URLs to start with the desired context path

==== Troubleshooting tips

Check that the catalog URL in the title of the HTML view of catalogs
matches the requested URL.

Check that the Data Access URL in the OPeNDAP Data Access Form matches
the requested URL (minus the ``.html'' suffix).

If you have <<RemoteManagement#,TDS Remote Management>>
configured, go to the TDS debug page (e.g.,
`http://localhost:8080/thredds/admin/debug`) and follow the ``Show HTTP
Request info'' link. Once there, check that the values listed for server
name and port and the context path all match the appropriate values from
the request URL. E.g., for the URL
`             http://localhost:8080/thredds/admin/debug?General/showRequest           `,
the values should be

* `             req.getServerName(): localhost           `
* `             req.getServerPort(): 8080           `
* `             req.getContextPath(): /thredds           `

'''''

This document is maintained by Unidata. Send comments to
mailto:support-thredds@unidata.ucar.edu[THREDDS support].
