:source-highlighter: coderay
[[threddsDocs]]

= CDM GRIB-1 Notes

== ECMWF extended complex packing

ECMWF uses an undocumented format for *_GRIB-1 extended complex packing_*.
As a service to the community, we document here that format as well as we understand it.

When should this format be used? There is a standard WMO complex_packing (though I havent seen it used), so probably
best to restrict to center = ECMWF. The flag at octet 4 is tested for _isGridPointData_ (bit 1 = 0) and _isComplexPacking_ (bit 2 = 1).

Sources:

* *_GRIB-API_* source code _data.grid_second_order.def_

[title="Section-4 (BDS)",width="100%",cols="10%,90%",options="header",]
|===
|Octet|Content
|1-3 |*_dataMessageLength_*: Length in octets of binary data section
|4 | *_flag_*: Bits 1 through 4: See Table 11, and note 5 below +
*_unusedBits_*: Bits 5 through 8: Number of unused bits at end of Section 4.
|5-6 | *_binaryScaleFactor_*: The binary scale factor.
|7-10 | *_referenceValue_*: Reference value.
|11 |*_widthOfFirstOrderValues_*, number of bits of first order packed values.
|12-13 |*_N1_* - Octet number relative to the start of the BDS, at which the first order packed numbers begin.
|14 | *_extendedFlags_*: See Code Table 11-2, below.
|15-16 |*_N2_* - Octet number relative to the start of the BDS, at which the second order packed numbers begin.
|17-18 |*_codedNumberOfGroups_* : see Note 1
|19-20 |*_numberOfSecondOrderPackedValues_* - The number of second order packed values : see Notes 2, 3
|21 | *_extraValues_* : see Note 1
|22 | *_widthOfWidths_* : width in bits of groupWidths
|23 | *_widthOfLengths_* : width in bits of groupLengths
|24-25 | *_NL_* : Octet number relative to the start of the BDS, at which the group lengths begin
|26 | *_widthOfSPD _* ??
|27-? | *_SPD_* ?? see Note 4, 5
|?-(NL-1)| packed *_groupWidths_*: _widthOfWidths*numberOfGroups_ bits, 0 padded to end of byte
|NL-(N1-1)| packed *_groupLengths_*: _widthOfLengths*numberOfGroups_ bits, 0 padded to end of byte
|N1-(N2-1)| packed *_firstOrderValues_*: _widthOfFirstOrderValues*numberOfGroups_ bits, 0 padded to end of byte
|N2-... | packed *_secondOrderValues_*: _sum(groupLength[group] * groupWidth[group])_ bits
|===

Notes:

. *_numberOfGroups_* = _codedNumberOfGroups + 65536 * extraValues_
. with only two bytes, _numberOfSecondOrderPackedValues_ has maximum of 65536; so 65536 indicates overflow
.  *_numberOfSecondOrderPackedValues_* can be calculated as _sum(groupLengths)_. This should match npts from GDS.
. variable number of bytes read here apparently.
. calculate backwards from NL - (widthOfWidths*numberOfGroups +7) / 8
. if groupWidth == 0, secondOrderValue = 0 for all values in that group

*_Table 11-2_*: From http://cost733.geo.uni-augsburg.de/cost733class-1.2/browser/grib_api-1.9.18/definitions/grib1/11-2.table?rev=4:
----
# CODE TABLE 11-2, Flag
#  Undocumented use of octet 14 extendedFlags
#  Taken from d2ordr.F
#         R------- only bit 1 is reserved.
#         -0------ single datum at each grid point.
#         -1------ matrix of values at each grid point.
#         --0----- no secondary bit map.
#         --1----- secondary bit map present.
#         ---0---- second order values have constant width.
#         ---1---- second order values have different widths.
#         ----0--- no general extended second order packing.
#         ----1--- general extended second order packing used.
#         -----0-- standard field ordering in section 4.
#         -----1-- boustrophedonic ordering in section 4.
1 0 Reserved
1 1 Reserved
2 0 Single datum at each grid point
2 1 Matrix of values at each grid point
3 0 No secondary bitmap Present
3 1 Secondary bitmap Present
4 0 Second-order values constant width
4 1 Second-order values different widths
5 0 no general extended second order packing
5 1 general extended second order packing used
6 0 standard field ordering in section 4
6 1 boustrophedonic ordering in section 4
#         ------00 no spatial differencing used.
#         ------01 1st-order spatial differencing used.
#         ------10 2nd-order    "         "         " .
#         ------11 3rd-order    "         "         " .
----

The floating point calculation of a value is:

[source,java]
----
double pow10 =  Math.pow(10.0, -pds.decimalScale); // from PDS section
float ref = (float) (pow10 * referenceValue);
float scale = (float) (pow10 * Math.pow(2.0, binaryScaleFactor));
int val = 0;
for (int group = 0; group < numberOfGroups; group++) {
  for (int i = 0; i < groupLength[group]; i++) {
    values[val] = ref + scale * (firstOrderValues[group] + secondOrderValues[val]);
    val++;
  }
}
----

== Problems

This algorithm is not yet correct, at least on the sample message.

. widthSPD, SPD undefined, apparently variable length number of bytes
. The calculation of total number of points _sum(groupLength[group])_ = 88836, but npts from GDS (this is a gaussian grid) = 88838.

== Output from grib_dump -D

----
  ======> section section_4 (81433,81433,0)
      658-658 position offsetSection4 = 658
      658-661 g1_section4_length section4Length = 81433
      661-661 section_pointer section4Pointer = 658_81433
      661-661 g1_half_byte_codeflag halfByte = 4
      661-662 codeflag dataFlag = 68 [01000100:(1=0)  Grid-point data;(2=1)  Complex or second-order packing;(3=0)  Floating point values are represented;(4=0)  No additional flags at octet 14:grib1/11.table]
      662-664 signed binaryScaleFactor = -5
      664-668 ibmfloat referenceValue = 229.323
      668-668 reference_value_error referenceValueError = 1.52588e-05
      668-668 bit sphericalHarmonics = 0
      668-668 bit complexPacking = 1
      668-668 bit integerPointValues = 0
      668-668 bit additionalFlagPresent = 0
      668-669 unsigned widthOfFirstOrderValues = 11
      669-671 unsigned N1 = 5117
      671-672 codeflag extendedFlag = 26 [00011010:(1=0)  Reserved;(2=0)  Single datum at each grid point;(3=0)  No secondary bitmap Present;(4=1)  Second-order values different widths;(5=1)  general extended second order packing used;(6=0)  standard field ordering in section 4:grib1/11-2.table]
      672-672 bit matrixOfValues = 0
      672-672 bit secondaryBitmapPresent = 0 [secondaryBitmap]
      672-672 bit secondOrderOfDifferentWidth = 1
      672-672 bit generalExtended2ordr = 1
      672-672 bit boustrophedonicOrdering = 0 [boustrophedonic]
      672-672 bit twoOrdersOfSPD = 1
      672-672 bit plusOneinOrdersOfSPD = 0
      672-672 evaluate orderOfSPD = 2
      672-672 transient hideThis = 0
      672-672 concept packingType = grid_second_order [typeOfPacking]
      ======> section dataValues (81419,81419,0)
         672-674 unsigned N2 = 10710
         674-676 unsigned codedNumberOfGroups = 4067
         676-678 unsigned numberOfSecondOrderPackedValues = 65535
         678-679 unsigned extraValues = 0
         679-679 evaluate numberOfGroups = 4067
         679-680 unsigned widthOfWidths = 4
         680-681 unsigned widthOfLengths = 6
         681-683 unsigned NL = 2066
         683-684 unsigned widthOfSPD = 12
         684-689 spd SPD = 12 *** ERR=-6 (Passed array is too small)
         689-2723 unsigned_bits groupWidths = 6 *** ERR=-6 (Passed array is too small)
         2723-5774 unsigned_bits groupLengths = 6 *** ERR=-6 (Passed array is too small)
         5774-11367 unsigned_bits firstOrderValues = 6 *** ERR=-6 (Passed array is too small)
         11367-11367 sum countOfGroupLengths = (4067,0) {
                 88836,          0,          0,          0,          0,          0,          0,          0,
                     0,          0,          0,          0,          0, 1.61985e-316, 2.122e-314,       67.5,
               67.5556, 2.47515e-316,       -nan,         68, 2.47515e-316,          0,    68.2031,      68.25,
               68.3334,       68.4,    68.4375, 1.31213e-312,          0,          0,          0,          0,
                     0,          0,          0,          0,          0,          0,          0,          0,
                     0,    69.6296,      69.75,      69.84,         70,      70.08,       70.2,    70.2222,
               70.3125,    70.3704,       70.4,       70.5,      70.56,    70.6667,       70.8,    70.8333,
                70.875,         71,    71.0156,      71.04,       71.1,    71.1111,       71.2,      71.25,
                 71.28,    71.6667,    71.7188,    71.8519,         72,    72.1875, 1.31213e-312, 1.46932e-317,
                  72.5,    72.5926,      72.72,      72.75,       72.8,    72.8889,       72.9,      72.96,
                    73,     73.125,       73.2,    73.3333,      73.44,       73.5,       73.6,      73.75,
               73.7778,       73.8,    73.8281,      73.92,         74,    74.0625,    74.0741,      74.16,
               74.1667,      74.25,       74.4,    74.4444
            ... 3967 more values
         } # sum countOfGroupLengths
         11367-11367 transient numberOfCodedValues = 88838 [numberOfEffectiveValues]
         11367-11367 second_order_bits_per_value bitsPerValue = 12
         11367-11367 position offsetBeforeData = 11367
         11367-82091 data_g1second_order_general_extended_packing values = (88838,70724) [codedValues, data.packedValues] {
               246.886,    245.823,    244.979,    244.604,    244.511,    244.573,    244.573,    244.542,
               244.542,    244.636,    244.761,    245.167,    245.979,    247.073,    247.979,    248.261,
               248.073,    247.636,    249.167,    247.729,    246.011,    244.792,    244.136,    243.729,
               243.636,    243.573,    243.542,    243.573,    243.604,    243.729,    243.948,    244.261,
               244.573,    244.886,    245.792,    247.479,    249.042,    250.136,    250.823,    251.042,
               250.792,    250.386,    249.948,    250.698,    249.917,    248.542,    246.792,    245.261,
               244.354,    243.886,    243.729,    243.792,    243.854,    243.823,    243.698,    243.667,
               243.761,    243.729,    243.729,    243.823,    243.886,    243.948,    244.261,    244.636,
               244.823,    245.198,    246.292,    248.136,    250.011,    251.323,    252.229,    252.636,
               252.854,    252.979,    252.823,    252.573,    252.386,    251.979,    251.323,    252.011,
               251.042,    249.823,    248.167,    246.198,    244.792,    244.323,    244.198,    244.167,
               244.073,    243.979,    244.167,    244.167,    243.886,    243.886,    243.854,    243.761,
               243.761,    243.792,    243.886,    244.042
            ... 88738 more values
         } # data_g1second_order_general_extended_packing values
         82091-82091 simple_packing_error packingError = 0.0156326
         ======> section statistics (0,0,0)
            82091-82091 dirty dirty_statistics = 1
            82091-82091 statistics computeStatistics = (8,0) {
                  309.854,    229.323,    284.609,          0,    15.6525, 3.68346e+08, 1.85978e+10,          0
            } # statistics computeStatistics
            82091-82091 vector maximum = 309.854 [statistics.max]
            82091-82091 vector minimum = 229.323 [statistics.min]
            82091-82091 vector average = 284.609 [statistics.avg]
            82091-82091 count_missing numberOfMissing = 0 [numberOfMissingValues]
            82091-82091 vector standardDeviation = 15.6525 [statistics.sd]
            82091-82091 vector skewness = 3.68346e+08 [statistics.skew]
            82091-82091 vector kurtosis = 1.85978e+10 [statistics.kurt]
            82091-82091 vector isConstant = 0 [statistics.const]
         <===== section statistics
      <===== section dataValues
      82091-82091 position offsetAfterData = 82091
      82091-82091 transient dataLength = 8840
      82091-82091 decimal_precision changeDecimalPrecision = 0 [setDecimalPrecision]
      82091-82091 decimal_precision decimalPrecision = 0
      82091-82091 bits_per_value bitsPerValueAndRepack = 12 [setBitsPerValue]
      82091-82091 scale_values scaleValuesBy = 1
      82091-82091 offset_values offsetValuesBy = 0
      82091-82091 concept gridType = reduced_gg [geography.gridType, typeOfGrid]
      82091-82091 size getNumberOfValues = 88838
      82091-82091 md5 md5Section4 = 736be5a9ae83d8499f93110239794754
   <===== section section_4
----
