
/*
 * parameter table for the Air Force Weather Agency
 * center = 57
 */

struct ParmTable parm_table_afwa[256] = {
   /* 0 */ {"var0", "undefined"},
   /* 1 */ {"PRES", "Pressure [Pa]"},
   /* 2 */ {"PRMSL", "Pressure reduced to MSL [Pa]"},
   /* 3 */ {"PTEND", "Pressure tendency [Pa/s]"},
   /* 4 */ {"PVORT", "Potential Vorticity [K m^2/kg s]"},
   /* 5 */ {"ICAHT", "ICAO Standard Atmosphere Reference Height [m]"},
   /* 6 */ {"GP", "Geopotential [m^2/s^2]"},
   /* 7 */ {"HGT", "Geopotential height [gpm]"},
   /* 8 */ {"DIST", "Geometric height [m]"},
   /* 9 */ {"HSTDV", "Std dev of height [m]"},
   /* 10 */ {"TOZNE", "Total ozone [Dobson]"},
   /* 11 */ {"TMP", "Temp. [K]"},
   /* 12 */ {"VTMP", "Virtual temp. [K]"},
   /* 13 */ {"POT", "Potential temp. [K]"},
   /* 14 */ {"EPOT", "Pseudo-adiabatic pot. temp. [K]"},
   /* 15 */ {"TMAX", "Max. temp. [K]"},
   /* 16 */ {"TMIN", "Min. temp. [K]"},
   /* 17 */ {"DPT", "Dew point temp. [K]"},
   /* 18 */ {"DEPR", "Dew point depression [K]"},
   /* 19 */ {"LAPR", "Lapse rate [K/m]"},
   /* 20 */ {"VISIB", "Visibility [m]"},
   /* 21 */ {"RDSP1", "Radar spectra (1) [non-dim]"},
   /* 22 */ {"RDSP2", "Radar spectra (2) [non-dim]"},
   /* 23 */ {"RDSP3", "Radar spectra (3) [non-dim]"},
   /* 24 */ {"PLI", "Parcel lifted index (to 500 hPa [K]"},
   /* 25 */ {"TMPA", "Temp. anomaly [K]"},
   /* 26 */ {"PRESA", "Pressure anomaly [Pa]"},
   /* 27 */ {"GPA", "Geopotential height anomaly [gpm]"},
   /* 28 */ {"WVSP1", "Wave spectra (1) [non-dim]"},
   /* 29 */ {"WVSP2", "Wave spectra (2) [non-dim]"},
   /* 30 */ {"WVSP3", "Wave spectra (3) [non-dim]"},
   /* 31 */ {"WDIR", "Wind direction [deg]"},
   /* 32 */ {"WIND", "Wind speed [m/s]"},
   /* 33 */ {"UGRD", "u wind [m/s]"},
   /* 34 */ {"VGRD", "v wind [m/s]"},
   /* 35 */ {"STRM", "Stream function [m^2/s]"},
   /* 36 */ {"VPOT", "Velocity potential [m^2/s]"},
   /* 37 */ {"MNTSF", "Montgomery stream function [m^2/s^2]"},
   /* 38 */ {"SGCVV", "Sigma coord. vertical velocity [/s]"},
   /* 39 */ {"VVEL", "Pressure vertical velocity [Pa/s]"},
   /* 40 */ {"DZDT", "Geometric vertical velocity [m/s]"},
   /* 41 */ {"ABSV", "Absolute vorticity [/s]"},
   /* 42 */ {"ABSD", "Absolute divergence [/s]"},
   /* 43 */ {"RELV", "Relative vorticity [/s]"},
   /* 44 */ {"RELD", "Relative divergence [/s]"},
   /* 45 */ {"VUCSH", "Vertical u shear [/s]"},
   /* 46 */ {"VVCSH", "Vertical v shear [/s]"},
   /* 47 */ {"DIRC", "Direction of current [deg]"},
   /* 48 */ {"SPC", "Speed of current [m/s]"},
   /* 49 */ {"UOGRD", "u of current [m/s]"},
   /* 50 */ {"VOGRD", "v of current [m/s]"},
   /* 51 */ {"SPFH", "Specific humidity [kg/kg]"},
   /* 52 */ {"RH", "Relative humidity [%]"},
   /* 53 */ {"MIXR", "Humidity mixing ratio [kg/kg]"},
   /* 54 */ {"PWAT", "Precipitable water [kg/m^2]"},
   /* 55 */ {"VAPP", "Vapor pressure [Pa]"},
   /* 56 */ {"SATD", "Saturation deficit [Pa]"},
   /* 57 */ {"EVP", "Evaporation [kg/m^2]"},
   /* 58 */ {"CICE", "Cloud Ice [kg/m^2]"},
   /* 59 */ {"PRATE", "Precipitation rate [kg/m^2/s]"},
   /* 60 */ {"TSTM", "Thunderstorm probability [%]"},
   /* 61 */ {"APCP", "Total precipitation [kg/m^2]"},
   /* 62 */ {"NCPCP", "Large scale precipitation [kg/m^2]"},
   /* 63 */ {"ACPCP", "Convective precipitation [kg/m^2]"},
   /* 64 */ {"SRWEQ", "Snowfall rate water equiv. [kg/m^2/s]"},
   /* 65 */ {"WEASD", "Accum. snow [kg/m^2]"},
   /* 66 */ {"SNOD", "Snow depth [m]"},
   /* 67 */ {"MIXHT", "Mixed layer depth [m]"},
   /* 68 */ {"TTHDP", "Transient thermocline depth [m]"},
   /* 69 */ {"MTHD", "Main thermocline depth [m]"},
   /* 70 */ {"MTHA", "Main thermocline anomaly [m]"},
   /* 71 */ {"TCDC", "Total cloud cover [%]"},
   /* 72 */ {"CDCON", "Convective cloud cover [%]"},
   /* 73 */ {"LCDC", "Low level cloud cover [%]"},
   /* 74 */ {"MCDC", "Mid level cloud cover [%]"},
   /* 75 */ {"HCDC", "High level cloud cover [%]"},
   /* 76 */ {"CWAT", "Cloud water [kg/m^2]"},
   /* 77 */ {"BLI", "Best lifted index to 500 hPa [K]"},
   /* 78 */ {"SNOC", "Convective snow [kg/m^2]"},
   /* 79 */ {"SNOL", "Large scale snow [kg/m^2]"},
   /* 80 */ {"WTMP", "Water temp. [K]"},
   /* 81 */ {"LAND", "Land-sea mask [1=land; 0=sea]"},
   /* 82 */ {"DSLM", "Deviation of sea level from mean [m]"},
   /* 83 */ {"SFCR", "Surface roughness [m]"},
   /* 84 */ {"ALBDO", "Albedo [%]"},
   /* 85 */ {"TSOIL", "Soil temp. [K]"},
   /* 86 */ {"SOILM", "Soil moisture content [kg/m^2]"},
   /* 87 */ {"VEG", "Vegetation [%]"},
   /* 88 */ {"SALTY", "Salinity [kg/kg]"},
   /* 89 */ {"DEN", "Density [kg/m^3]"},
   /* 90 */ {"RUNOF", "Runoff [kg/m^2]"},
   /* 91 */ {"ICEC", "Ice concentration [ice=1;no ice=0]"},
   /* 92 */ {"ICETK", "Ice thickness [m]"},
   /* 93 */ {"DICED", "Direction of ice drift [deg]"},
   /* 94 */ {"SICED", "Speed of ice drift [m/s]"},
   /* 95 */ {"UICE", "u of ice drift [m/s]"},
   /* 96 */ {"VICE", "v of ice drift [m/s]"},
   /* 97 */ {"ICEG", "Ice growth rate [m/s]"},
   /* 98 */ {"ICED", "Ice divergence [/s]"},
   /* 99 */ {"SNOM", "Snow melt [kg/m^2]"},
   /* 100 */ {"HTSGW", "Sig height of wind waves and swell [m]"},
   /* 101 */ {"WVDIR", "Direction of wind waves [deg]"},
   /* 102 */ {"WVHGT", "Sig height of wind waves [m]"},
   /* 103 */ {"WVPER", "Mean period of wind waves [s]"},
   /* 104 */ {"SWDIR", "Direction of swell waves [deg]"},
   /* 105 */ {"SWELL", "Sig height of swell waves [m]"},
   /* 106 */ {"SWPER", "Mean period of swell waves [s]"},
   /* 107 */ {"DIRPW", "Primary wave direction [deg]"},
   /* 108 */ {"PERPW", "Primary wave mean period [s]"},
   /* 109 */ {"DIRSW", "Secondary wave direction [deg]"},
   /* 110 */ {"PERSW", "Secondary wave mean period [s]"},
   /* 111 */ {"NSWRS", "Net short wave (surface) [W/m^2]"},
   /* 112 */ {"NLWRS", "Net long wave (surface) [W/m^2]"},
   /* 113 */ {"NSWRT", "Net short wave (top) [W/m^2]"},
   /* 114 */ {"NLWRT", "Net long wave (top) [W/m^2]"},
   /* 115 */ {"LWAVR", "Long wave [W/m^2]"},
   /* 116 */ {"SWAVR", "Short wave [W/m^2]"},
   /* 117 */ {"GRAD", "Global radiation [W/m^2]"},
   /* 118 */ {"BRTMP", "Brightness temperature [K]"},
   /* 119 */ {"LWRAD", "Radiance (with respect to wave number) [W/m sr]"},
   /* 120 */ {"SWRAD", "Radiance (with respect to wave length) [W/m^3 sr]"},
   /* 121 */ {"LHTFL", "Latent heat flux [W/m^2]"},
   /* 122 */ {"SHTFL", "Sensible heat flux [W/m^2]"},
   /* 123 */ {"BLYDP", "Boundary layer dissipation [W/m^2]"},
   /* 124 */ {"UFLX", "Zonal momentum flux [N/m^2]"},
   /* 125 */ {"VFLX", "Meridional momentum flux [N/m^2]"},
   /* 126 */ {"WMIXE", "Wind mixing energy [J]"},
   /* 127 */ {"IMGD", "Image data [integer]"},
   /* 128 */ {"M3HPCP", "Average 3hr Precipitation [mm/hr]"},
   /* 129 */ {"ARSLTP", "Aerosol Type [code]"},
   /* 130 */ {"HLAND", "Hours since land [hours]"},
   /* 131 */ {"PRESMB", "Pressure [hPa]"},
   /* 132 */ {"MSLPMB", "Pressure Reduced to MSL [hPa]"},
   /* 133 */ {"VVELMB", "Pressure Vertical Velocity [hPa/s]"},
   /* 134 */ {"ALTDENSE", "Altitude Density [m]"},
   /* 135 */ {"WBZ", "Wet Bulb Zero [m]"},
   /* 136 */ {"ASIZE", "Potential Hail Size [cm]"},
   /* 137 */ {"PBLHGT", "Planetary Boundary Layer Height [m]"},
   /* 138 */ {"TSMAXT", "Thunderstorm Max Tops [m]"},
   /* 139 */ {"TSCOV", "Thunderstorm Coverage [code]"},
   /* 140 */ {"CIG", "Ceiling [m]"},
   /* 141 */ {"WNDGST", "Wind Gust [m/s]"},
   /* 142 */ {"UGST", "U component Wind Gust [m/s]"},
   /* 143 */ {"VGST", "V component Wind Gust [m/s]"},
   /* 144 */ {"PCPCAT", "Precip Category [code]"},
   /* 145 */ {"CONT1T", "Contrail Engine Type 1 Top [m]"},
   /* 146 */ {"CONT1B", "Contrail Engine Type 1 Base [m]"},
   /* 147 */ {"CONT1I", "Contrail Engine Type 1 Intensity [code]"},
   /* 148 */ {"CONT2T", "Contrail Engine Type 2 Top [m]"},
   /* 149 */ {"CONT2B", "Contrail Engine Type 2 Base [m]"},
   /* 150 */ {"CONT2I", "Contrail Engine Type 2 Intensity [code]"},
   /* 151 */ {"CONT3T", "Contrail Engine Type 3 Top [m]"},
   /* 152 */ {"CONT3B", "Contrail Engine Type 3 Base [m]"},
   /* 153 */ {"CONT3I", "Contrail Engine Type 3 Intensity [code]"},
   /* 154 */ {"IRTRAN", "IR Transmissivity (IWA vs TDA's) [%]"},
   /* 155 */ {"ABSHUM", "Absolute Humidity [g/m^3]"},
   /* 156 */ {"IRVIS", "IR Visibility [m]"},
   /* 157 */ {"CATSNOW", "Categorical Snow [code]"},
   /* 158 */ {"var158", "undefined"},
   /* 159 */ {"var159", "undefined"},
   /* 160 */ {"var160", "undefined"},
   /* 161 */ {"POTV", "Potential Vorticity [/s]"},
   /* 162 */ {"SST", "Sea Surface Temp [.1Deg C]"},
   /* 163 */ {"var163", "undefined"},
   /* 164 */ {"var164", "undefined"},
   /* 165 */ {"TPI", "Thunderstorm Potential Indicator [non-dim]"},
   /* 166 */ {"SVTFG", "Severe Turbulence Flag [0/1]"},
   /* 167 */ {"RAINF", "Rain Flag [0/1]"},
   /* 168 */ {"TSTMF", "Thunderstorm Flag [0/1]"},
   /* 169 */ {"SVTSFG", "Precipitation Severe TS Flag [0/1]"},
   /* 170 */ {"SNOWF", "Snow Flag [0/1]"},
   /* 171 */ {"ICEF", "Ice/Mixed Flag [0/1]"},
   /* 172 */ {"IPFG", "Precipitation Ice Pellets Flag [0/1]"},
   /* 173 */ {"ZRF", "Freezing Rain Flag [0/1]"},
   /* 174 */ {"SNODIN", "Snow Depth [inches]"},
   /* 175 */ {"SNOAGE", "Snow age [days]"},
   /* 176 */ {"SNOCLI", "Snow Depth Climo [inches]"},
   /* 177 */ {"VISCOD", "Visibility [code]"},
   /* 178 */ {"P_WX", "Weather [code]"},
   /* 179 */ {"CLDLYA", "Layer Cloud Amount [%]"},
   /* 180 */ {"CLDLYB", "Layer Cloud Base [code]"},
   /* 181 */ {"CLDLYT", "Layer Cloud Top [code]"},
   /* 182 */ {"CLDTYP", "Layer Cloud Type [code]"},
   /* 183 */ {"UPDTIM", "Time of last update from base time [code]"},
   /* 184 */ {"SOURCE", "Source data"},
   /* 185 */ {"ICETOP", "Icing Top [ft]"},
   /* 186 */ {"ICEBAS", "Icing Base [ft]"},
   /* 187 */ {"ICING", "Icing (1-yes, 0-no) [code]"},
   /* 188 */ {"TRBTOP", "Turbulence Top [ft]"},
   /* 189 */ {"TRBBAS", "Turbulence Base [ft]"},
   /* 190 */ {"TURB", "Turbulence [code]"},
   /* 191 */ {"PSTAR", "P* [cb]"},
   /* 192 */ {"PPERT", "Pressure Perturbation [Pa]"},
   /* 193 */ {"PBLR", "PBL Regime [category]"},
   /* 194 */ {"FVEL", "Friction Velocity [m/s]"},
   /* 195 */ {"GRAUPEL", "Grauple Mixing Ratio [kg/kg]"},
   /* 196 */ {"ICEPART", "Number_concentration_of_ice [#/m^3]"},
   /* 197 */ {"RADTEND", "Radiative Tendency [K/day]"},
   /* 198 */ {"TKE", "Turbulent Kinetic Energy [J/kg]"},
   /* 199 */ {"MAPSCALE", "Mapscale Factors [ratio]"},
   /* 200 */ {"TSOILU", "Upper Layer Soil Temp [K]"},
   /* 201 */ {"SOILMU", "Upper Layer Soil Moisture [g/m³]"},
   /* 202 */ {"SOILML", "Lower Layer Soil Moisture [g/m³]"},
   /* 203 */ {"MRGPCP", "Merged Precipitation [mm/24hrs]"},
   /* 204 */ {"EVAP", "Evapotransporation [mm/24hrs]"},
   /* 205 */ {"SOILTP", "Soil Type [code]"},
   /* 206 */ {"VOLASH", "Volcanic Ash [1=present 0=not present]"},
   /* 207 */ {"KETI", "Knapp-Ellrod Turbulence Index [category]"},
   /* 208 */ {"PANIND", "Panofsky Low Level Turbulence Index [non-dim]"},
   /* 209 */ {"ALTSET", "Altimeter setting [in Hg]"},
   /* 210 */ {"K X", "K index [K]"},
   /* 211 */ {"KO X", "KO index [K]"},
   /* 212 */ {"TT X", "Total totals index [K]"},
   /* 213 */ {"S X", "Sweat index [non-dim]"},
   /* 214 */ {"CAPE", "Convective available potential eng [J/kg]"},
   /* 215 */ {"CIN", "Convective inhibition [J/kg]"},
   /* 216 */ {"SRHEL", "Storm relative helicity [J/kg]"},
   /* 217 */ {"EHI", "Energy helicity index [non-dim]"},
   /* 218 */ {"ILW", "Integrated liquid water [g/m^2]"},
   /* 219 */ {"COND", "Condensate [kg/kg]"},
   /* 220 */ {"CW MR", "Cloud water mixing ratio [kg/kg]"},
   /* 221 */ {"IW MR", "Ice water mixing ratio [kg/kg]"},
   /* 222 */ {"RW MR", "Rain water mixing ratio [kg/kg]"},
   /* 223 */ {"SW MR", "Snow water mixing ratio [kg/kg]"},
   /* 224 */ {"HEATX", "Heat index [K]"},
   /* 225 */ {"MCONV", "Horizontal moisture convergence [kg/kg/s]"},
   /* 226 */ {"TCAT", "Turbulence (Intensity) [0-none, 1-lgt, 2-mod, 3-svr]"},
   /* 227 */ {"CLD B", "Cloud base [m]"},
   /* 228 */ {"CLD T", "Cloud top [m]"},
   /* 229 */ {"T CLDCOV", "Total cloud cover [%]"},
   /* 230 */ {"LAT", "Latitude [deg]"},
   /* 231 */ {"LON", "Longitude [deg]"},
   /* 232 */ {"THKNS", "Thickness [m]"},
   /* 233 */ {"TER HT", "Model terrain height [m]"},
   /* 234 */ {"W CHILL", "Wind Chill [F]"},
   /* 235 */ {"D VAL", "D-values of height [feet]"},
   /* 236 */ {"MX RH", "Maximum relative humidity [%]"},
   /* 237 */ {"MX ABSH", "Maximum absolute humidity [g/m^3]"},
   /* 238 */ {"MX WIND", "Maximum wind speed [m/s]"},
   /* 239 */ {"MN DEPR", "Minimum dewpoint depression [K]"},
   /* 240 */ {"TOTAPCP", "Total accumulated precipitation [kg/m^2]"},
   /* 241 */ {"LANDUSE", "Land-use [category]"},
   /* 242 */ {"INCSNOWF", "Incremental accumulated snowfall [in]"},
   /* 243 */ {"TOTSNOWF", "Total accumulated snowfall [in]"},
   /* 244 */ {"PCPTYPE", "Precipitation type [1-rain 2-trw, 3-zr 4-mixed/ice 5-snow]"},
   /* 245 */ {"ICECOD", "Icing [0-none, 1-light, 2-mod, 3-severe]"},
   /* 246 */ {"REFRACT", "Radio refractivity [dimensionless]"},
   /* 247 */ {"VTHETA", "Virtual Potential Temperature [K]"},
   /* 248 */ {"LSI", "Lid Strength Index [K]"},
   /* 249 */ {"REFLECT", "Reflectivity [None]"},
   /* 250 */ {"LGIFG", "Light Icing Flag [0/1]"},
   /* 251 */ {"MDIFG", "Moderate Icing Flag [0/1]"},
   /* 252 */ {"SVIFG", "Severe Icing Flag [0/1]"},
   /* 253 */ {"LGTFG", "Light Turbulence Flag [0/1]"},
   /* 254 */ {"MDTFG", "Moderate Turbulence Flag [0/1]"},
   /* 255 */ {"var255", "undefined"},
};


