
/*
 * parameter table for the Air Force Weather Agency
 * center = 57 subcenter = 10
 */

struct ParmTable parm_table_afwa_climo[256] = {
   /* 0 */ {"var0", "undefined"},
   /* 1 */ {"PRES", "Pressure [Pa]"},
   /* 2 */ {"PRMSL", "Pressure reduced to MSL [Pa]"},
   /* 3 */ {"PTEND", "Pressure tendency [Pa/s]"},
   /* 4 */ {"PVORT", "Potential Vorticity [K m^2/kg s]"},
   /* 5 */ {"ICAHT", "ICAO Standard Atmosphere Reference Height [m]"},
   /* 6 */ {"GP", "Geopotential [m^2/s^2]"},
   /* 7 */ {"HGT", "Geopotential height [gpm]"},
   /* 8 */ {"DIST", "Geometric height [m]"},
   /* 9 */ {"HSTDV", "Std dev of height [m]"},
   /* 10 */ {"TOZNE", "Total ozone [Dobson]"},
   /* 11 */ {"TMP", "Temp. [K]"},
   /* 12 */ {"VTMP", "Virtual temp. [K]"},
   /* 13 */ {"POT", "Potential temp. [K]"},
   /* 14 */ {"EPOT", "Pseudo-adiabatic pot. temp. [K]"},
   /* 15 */ {"TMAX", "Max. temp. [K]"},
   /* 16 */ {"TMIN", "Min. temp. [K]"},
   /* 17 */ {"DPT", "Dew point temp. [K]"},
   /* 18 */ {"DEPR", "Dew point depression [K]"},
   /* 19 */ {"LAPR", "Lapse rate [K/m]"},
   /* 20 */ {"VISIB", "Visibility [m]"},
   /* 21 */ {"RDSP1", "Radar spectra (1) [non-dim]"},
   /* 22 */ {"RDSP2", "Radar spectra (2) [non-dim]"},
   /* 23 */ {"RDSP3", "Radar spectra (3) [non-dim]"},
   /* 24 */ {"PLI", "Parcel lifted index (to 500 hPa [K]"},
   /* 25 */ {"TMPA", "Temp. anomaly [K]"},
   /* 26 */ {"PRESA", "Pressure anomaly [Pa]"},
   /* 27 */ {"GPA", "Geopotential height anomaly [gpm]"},
   /* 28 */ {"WVSP1", "Wave spectra (1) [non-dim]"},
   /* 29 */ {"WVSP2", "Wave spectra (2) [non-dim]"},
   /* 30 */ {"WVSP3", "Wave spectra (3) [non-dim]"},
   /* 31 */ {"WDIR", "Wind direction [deg]"},
   /* 32 */ {"WIND", "Wind speed [m/s]"},
   /* 33 */ {"UGRD", "u wind [m/s]"},
   /* 34 */ {"VGRD", "v wind [m/s]"},
   /* 35 */ {"STRM", "Stream function [m^2/s]"},
   /* 36 */ {"VPOT", "Velocity potential [m^2/s]"},
   /* 37 */ {"MNTSF", "Montgomery stream function [m^2/s^2]"},
   /* 38 */ {"SGCVV", "Sigma coord. vertical velocity [/s]"},
   /* 39 */ {"VVEL", "Pressure vertical velocity [Pa/s]"},
   /* 40 */ {"DZDT", "Geometric vertical velocity [m/s]"},
   /* 41 */ {"ABSV", "Absolute vorticity [/s]"},
   /* 42 */ {"ABSD", "Absolute divergence [/s]"},
   /* 43 */ {"RELV", "Relative vorticity [/s]"},
   /* 44 */ {"RELD", "Relative divergence [/s]"},
   /* 45 */ {"VUCSH", "Vertical u shear [/s]"},
   /* 46 */ {"VVCSH", "Vertical v shear [/s]"},
   /* 47 */ {"DIRC", "Direction of current [deg]"},
   /* 48 */ {"SPC", "Speed of current [m/s]"},
   /* 49 */ {"UOGRD", "u of current [m/s]"},
   /* 50 */ {"VOGRD", "v of current [m/s]"},
   /* 51 */ {"SPFH", "Specific humidity [kg/kg]"},
   /* 52 */ {"RH", "Relative humidity [%]"},
   /* 53 */ {"MIXR", "Humidity mixing ratio [kg/kg]"},
   /* 54 */ {"PWAT", "Precipitable water [kg/m^2]"},
   /* 55 */ {"VAPP", "Vapor pressure [Pa]"},
   /* 56 */ {"SATD", "Saturation deficit [Pa]"},
   /* 57 */ {"EVP", "Evaporation [kg/m^2]"},
   /* 58 */ {"CICE", "Cloud Ice [kg/m^2]"},
   /* 59 */ {"PRATE", "Precipitation rate [kg/m^2/s]"},
   /* 60 */ {"TSTM", "Thunderstorm probability [%]"},
   /* 61 */ {"APCP", "Total precipitation [kg/m^2]"},
   /* 62 */ {"NCPCP", "Large scale precipitation [kg/m^2]"},
   /* 63 */ {"ACPCP", "Convective precipitation [kg/m^2]"},
   /* 64 */ {"SRWEQ", "Snowfall rate water equiv. [kg/m^2/s]"},
   /* 65 */ {"WEASD", "Accum. snow [kg/m^2]"},
   /* 66 */ {"SNOD", "Snow depth [m]"},
   /* 67 */ {"MIXHT", "Mixed layer depth [m]"},
   /* 68 */ {"TTHDP", "Transient thermocline depth [m]"},
   /* 69 */ {"MTHD", "Main thermocline depth [m]"},
   /* 70 */ {"MTHA", "Main thermocline anomaly [m]"},
   /* 71 */ {"TCDC", "Total cloud cover [%]"},
   /* 72 */ {"CDCON", "Convective cloud cover [%]"},
   /* 73 */ {"LCDC", "Low level cloud cover [%]"},
   /* 74 */ {"MCDC", "Mid level cloud cover [%]"},
   /* 75 */ {"HCDC", "High level cloud cover [%]"},
   /* 76 */ {"CWAT", "Cloud water [kg/m^2]"},
   /* 77 */ {"BLI", "Best lifted index to 500 hPa [K]"},
   /* 78 */ {"SNOC", "Convective snow [kg/m^2]"},
   /* 79 */ {"SNOL", "Large scale snow [kg/m^2]"},
   /* 80 */ {"WTMP", "Water temp. [K]"},
   /* 81 */ {"LAND", "Land-sea mask [1=land; 0=sea]"},
   /* 82 */ {"DSLM", "Deviation of sea level from mean [m]"},
   /* 83 */ {"SFCR", "Surface roughness [m]"},
   /* 84 */ {"ALBDO", "Albedo [%]"},
   /* 85 */ {"TSOIL", "Soil temp. [K]"},
   /* 86 */ {"SOILM", "Soil moisture content [kg/m^2]"},
   /* 87 */ {"VEG", "Vegetation [%]"},
   /* 88 */ {"SALTY", "Salinity [kg/kg]"},
   /* 89 */ {"DEN", "Density [kg/m^3]"},
   /* 90 */ {"RUNOF", "Runoff [kg/m^2]"},
   /* 91 */ {"ICEC", "Ice concentration [ice=1;no ice=0]"},
   /* 92 */ {"ICETK", "Ice thickness [m]"},
   /* 93 */ {"DICED", "Direction of ice drift [deg]"},
   /* 94 */ {"SICED", "Speed of ice drift [m/s]"},
   /* 95 */ {"UICE", "u of ice drift [m/s]"},
   /* 96 */ {"VICE", "v of ice drift [m/s]"},
   /* 97 */ {"ICEG", "Ice growth rate [m/s]"},
   /* 98 */ {"ICED", "Ice divergence [/s]"},
   /* 99 */ {"SNOM", "Snow melt [kg/m^2]"},
   /* 100 */ {"HTSGW", "Sig height of wind waves and swell [m]"},
   /* 101 */ {"WVDIR", "Direction of wind waves [deg]"},
   /* 102 */ {"WVHGT", "Sig height of wind waves [m]"},
   /* 103 */ {"WVPER", "Mean period of wind waves [s]"},
   /* 104 */ {"SWDIR", "Direction of swell waves [deg]"},
   /* 105 */ {"SWELL", "Sig height of swell waves [m]"},
   /* 106 */ {"SWPER", "Mean period of swell waves [s]"},
   /* 107 */ {"DIRPW", "Primary wave direction [deg]"},
   /* 108 */ {"PERPW", "Primary wave mean period [s]"},
   /* 109 */ {"DIRSW", "Secondary wave direction [deg]"},
   /* 110 */ {"PERSW", "Secondary wave mean period [s]"},
   /* 111 */ {"NSWRS", "Net short wave (surface) [W/m^2]"},
   /* 112 */ {"NLWRS", "Net long wave (surface) [W/m^2]"},
   /* 113 */ {"NSWRT", "Net short wave (top) [W/m^2]"},
   /* 114 */ {"NLWRT", "Net long wave (top) [W/m^2]"},
   /* 115 */ {"LWAVR", "Long wave [W/m^2]"},
   /* 116 */ {"SWAVR", "Short wave [W/m^2]"},
   /* 117 */ {"GRAD", "Global radiation [W/m^2]"},
   /* 118 */ {"BRTMP", "Brightness temperature [K]"},
   /* 119 */ {"LWRAD", "Radiance (with respect to wave number) [W/m sr]"},
   /* 120 */ {"SWRAD", "Radiance (with respect to wave length) [W/m^3 sr]"},
   /* 121 */ {"LHTFL", "Latent heat flux [W/m^2]"},
   /* 122 */ {"SHTFL", "Sensible heat flux [W/m^2]"},
   /* 123 */ {"BLYDP", "Boundary layer dissipation [W/m^2]"},
   /* 124 */ {"UFLX", "Zonal momentum flux [N/m^2]"},
   /* 125 */ {"VFLX", "Meridional momentum flux [N/m^2]"},
   /* 126 */ {"WMIXE", "Wind mixing energy [J]"},
   /* 127 */ {"IMGD", "Image data [integer]"},
   /* 128 */ {" DTEMP", " Standard Deviation of Temperature [K] "},
   /* 129 */ {" DDEW", " Standard Deviation of Dew Point  [K] "},
   /* 130 */ {" DPREC", " Standard Deviation of Precipitation [mm] "},
   /* 131 */ {" DMXTP", " Standard Deviation of Max Temperature [K] "},
   /* 132 */ {" DMNTP", " Standard Deviation of Min Temperature [K] "},
   /* 133 */ {" DSNFL", " Standard Deviation of Snowfall [m] "},
   /* 134 */ {" DPALT", " Standard Deviation of Pressure Altitude [m] "},
   /* 135 */ {" DDALT", " Standard Deviation of Density Altitude [m] "},
   /* 136 */ {" MXDEW", " Max Dew Point [K] "},
   /* 137 */ {" MNDEW", " Min Dew Point [K] "},
   /* 138 */ {" ALSTG", " Altimeter Setting [hPa] "},
   /* 139 */ {" MXALST", " Max Altimeter Setting [hPa] "},
   /* 140 */ {" MNALST", " Min Altimeter Setting [hPa] 1"},
   /* 141 */ {" PFREQ", " Precipitation Frequency [%] "},
   /* 142 */ {" MXPREC", " Max Precipitation [mm] "},
   /* 143 */ {" SFREQ", " Snowfall Frequency [%] "},
   /* 144 */ {" MXSNO", " Max Snowfall [m] "},
   /* 145 */ {" MXWSP", " Max Wind Speed  [m/s] "},
   /* 146 */ {" MNWSP", " Min Wind Speed  [m/s] "},
   /* 147 */ {" MXABH", " Max Absolute Humidity [g m3] "},
   /* 148 */ {" MNABH", " Min Absolute Humidity [g m3] "},
   /* 149 */ {" MNPREC", " Min Precipitation [mm] "},
   /* 150 */ {" NEWND", " NE Wind Direction Occurrence [%] "},
   /* 151 */ {" EWND", " E Wind Direction Occurrence [%] "},
   /* 152 */ {" SEWND", " SE Wind Direction Occurrence [%] "},
   /* 153 */ {" SWND", " S Wind Direction Occurrence [%] "},
   /* 154 */ {" SWWND", " SW Wind Direction Occurrence [%] "},
   /* 155 */ {" WWND", " W Wind Direction Occurrence [%] "},
   /* 156 */ {" NWWND", " NW Wind Direction Occurrence [%] "},
   /* 157 */ {" NWND", " N Wind Direction Occurrence [%] "},
   /* 158 */ {" NEWSP", " NE Wind Speed [m/s] "},
   /* 159 */ {" EWSP", " E Wind Speed [m/s] "},
   /* 160 */ {" SEWSP", " SE Wind Speed [m/s] "},
   /* 161 */ {" SWSP", " S Wind Speed [m/s] "},
   /* 162 */ {" SWWSP", " SW Wind Speed [m/s] "},
   /* 163 */ {" WWSP", " W Wind Speed [m/s] "},
   /* 164 */ {" NWWSP", " NW Wind Speed [m/s] "},
   /* 165 */ {" NWSP", " N Wind Speed [m/s] "},
   /* 166 */ {" P01OC", " Precipitation Greater than .01 inch [n/a] "},
   /* 167 */ {" P4OC", " Precipitation Greater than .4 inch [n/a] "},
   /* 168 */ {" MNSNO", " Min Snowfall [m] "},
   /* 169 */ {" PALT", " Pressure Altitude [m] "},
   /* 170 */ {" DALT", " Density Altitude [m] "},
   /* 171 */ {" V7FREQ", " Frequency Visibility Less than 9999 meters [%] "},
   /* 172 */ {" V6FREQ", " Frequency Visibility Less than 9000 meters [%] "},
   /* 173 */ {" V5FREQ", " Frequency Visibility Less than 8000 meters [%] "},
   /* 174 */ {" V4FREQ", " Frequency Visibility Less than 6000 meters [%] "},
   /* 175 */ {" V3FREQ", " Frequency Visibility Less than 4800 meters [%] "},
   /* 176 */ {" V2FREQ", " Frequency Visibility Less than 3200 meters [%] "},
   /* 177 */ {" V1FREQ", " Frequency Visibility Less than 1600 meters [%] "},
   /* 178 */ {" V0FREQ", " Frequency Visibility Less than 800 meters [%] "},
   /* 179 */ {" OBFREQ", " Frequency Obstruction to Vision [%] "},
   /* 180 */ {" MXGST", " Max Wind Gust   [m/s] "},
   /* 181 */ {" G25FRE", " Frequency Max Wind Gust Greater than 25kt  [%] "},
   /* 182 */ {" G35FRE", " Frequency Max Wind Gust Greater than 35kt  [%] "},
   /* 183 */ {" G50FRE", " Frequency Max Wind Gust Greater than 50kt  [%] "},
   /* 184 */ {" TRANS", " Transmissivity (8-12um) [frac] "},
   /* 185 */ {" TFREQ", " Frequency Thunderstorms  [%] "},
   /* 186 */ {" TBFREQ", " Frequency Turbulence  [%] "},
   /* 187 */ {" ICFREQ", " Frequency Icing  [%] "},
   /* 188 */ {" IPFREQ", " Frequency Ice Pellets Precipitation [%] "},
   /* 189 */ {" ZRFREQ", " Frequency Freezing Rain Precipitation [%] "},
   /* 190 */ {" HZFREQ", " Frequency Haze [%] "},
   /* 191 */ {" FGFREQ", " Frequency Fog [%] "},
   /* 192 */ {" BDFREQ", " Frequency Blowing Dust [%] "},
   /* 193 */ {" BSFREQ", " Frequency Blowing Snow [%] "},
   /* 194 */ {" T90FRQ", " Frequency Temperature Above 90 F [%] "},
   /* 195 */ {" T32FRQ", " Frequency Temperature Above 32 F [%] "},
   /* 196 */ {" T0FRQ", " Frequency Temperature Above 0 F [%] "},
   /* 197 */ {" CLDBAS", " Cloud Base [m] "},
   /* 198 */ {" CLDCIG", " Cloud Ceiling  [m] "},
   /* 199 */ {" CLDTOP", " Cloud Top [m] "},
   /* 200 */ {" CIGFRQ", " Frequency Ceiling   [%] "},
   /* 201 */ {" CTPFRQ", " Frequency Cloud Tops  [%] "},
   /* 202 */ {" CV107F", " Frequency Ceiling/Visibility Less than 10kft/7mi  [%] "},
   /* 203 */ {" CV33F", " Frequency Ceiling/Visibility Less than 3kft/3mi  [%] "},
   /* 204 */ {" CV153F", " Frequency Ceiling/Visibility Less than 1.5kft/3mi  [%] "},
   /* 205 */ {" CV12F", " Frequency Ceiling/Visibility Less than 1kft/2mi  [%] "},
   /* 206 */ {" CV55F", " Frequency Ceiling/Visibility Less than .5kft/.5mi  [%] "},
   /* 207 */ {" CV1510F", " Frequency Ceiling/Visibility Less than 15kft/10mi  [%] "},
   /* 208 */ {" CV105F", " Frequency Ceiling/Visibility Less than 10kft/5mi  [%] "},
   /* 209 */ {" CV52F", " Frequency Ceiling/Visibility Less than .5kft/2mi  [%] "},
   /* 210 */ {" CV15F", " Frequency Ceiling/Visibility Less than 1kft/.5mi  [%] "},
   /* 211 */ {" CV2015F", " Frequency Ceiling/Visibility Less than 20kft/15mi  [%] "},
   /* 212 */ {" ICCAT", " Icing Category   [cat] "},
   /* 213 */ {" TBCAT", " Turbulence Category   [cat] "},
   /* 214 */ {" SOLSAT", " Soil Moisture Saturation [%]"},
   /* 215 */ {" MAXRH", " Max Relative Humidity [%]"},
   /* 216 */ {" MINRH", " Min Relative Humidity [%]"},
   /* 217 */ {" MXSND", " Max Snow Depth [m] "},
   /* 218 */ {" MNSND", " Min Snow Depth [m] "},
   /* 219 */ {" MXSSAT", " Max Soil Moisture Saturation [%]"},
   /* 220 */ {" MNSSAT", " Min Soil Moisture Saturation [%]"},
   /* 221 */ {" ALCIG", " Frequency All Ceilings [%]"},
   /* 222 */ {" FQFZG", " Frequency Frozen Ground [%]"},
   /* 223 */ {" ABSHUM", " Absolute Humidity [g m3] "},
   /* 224 */ {" PRECIP", " Precipitation [mm]"},
   /* 225 */ {" var225", " blank [n/a]"},
   /* 226 */ {" var226", " blank [n/a]"},
   /* 227 */ {" var227", " blank [n/a]"},
   /* 228 */ {" var228", " blank [n/a]"},
   /* 229 */ {" var229", " blank [n/a]"},
   /* 230 */ {" var230", " blank [n/a]"},
   /* 231 */ {" var231", " blank [n/a]"},
   /* 232 */ {" var232", " blank [n/a]"},
   /* 233 */ {" var233", " blank [n/a]"},
   /* 234 */ {" var234", " blank   [n/a] "},
   /* 235 */ {" var235", " blank   [n/a] "},
   /* 236 */ {" var236", " blank [n/a]"},
   /* 237 */ {" var237", " blank [n/a]"},
   /* 238 */ {" var238", " blank [n/a]"},
   /* 239 */ {" var239", " blank [n/a]"},
   /* 240 */ {" var240", " blank [n/a]"},
   /* 241 */ {" var241", " blank [n/a]"},
   /* 242 */ {" var242", " blank [n/a]"},
   /* 243 */ {" var243", " blank [n/a]"},
   /* 244 */ {" var244", " blank [n/a]"},
   /* 245 */ {" var245", " blank [n/a]"},
   /* 246 */ {" var246", " blank [n/a]"},
   /* 247 */ {" var247", " blank [n/a]"},
   /* 248 */ {" var248", " blank [n/a]"},
   /* 249 */ {" var249", " blank [n/a]"},
   /* 250 */ {" var250", " blank [n/a]"},
   /* 251 */ {" var251", " blank [n/a]"},
   /* 252 */ {" var252", " blank [n/a]"},
   /* 253 */ {" var253", " blank [n/a]"},
   /* 254 */ {" var254", " blank [n/a]"},
   /* 255 */ {"var255", "blank"},

};


