/*
 * parameter table for the Air Force Weather Agency
 * center = 57 subcenter = 1
 */

struct ParmTable parm_table_afwa_chem[256] = {
   /* 0 */ {"var0", "undefined"},
   /* 1 */ {"PRES", "Pressure [Pa]"},
   /* 2 */ {"PRMSL", "Pressure reduced to MSL [Pa]"},
   /* 3 */ {"PTEND", "Pressure tendency [Pa/s]"},
   /* 4 */ {"PVORT", "Potential Vorticity [K m^2/kg s]"},
   /* 5 */ {"ICAHT", "ICAO Standard Atmosphere Reference Height [m]"},
   /* 6 */ {"GP", "Geopotential [m^2/s^2]"},
   /* 7 */ {"HGT", "Geopotential height [gpm]"},
   /* 8 */ {"DIST", "Geometric height [m]"},
   /* 9 */ {"HSTDV", "Std dev of height [m]"},
   /* 10 */ {"TOZNE", "Total ozone [Dobson]"},
   /* 11 */ {"TMP", "Temp. [K]"},
   /* 12 */ {"VTMP", "Virtual temp. [K]"},
   /* 13 */ {"POT", "Potential temp. [K]"},
   /* 14 */ {"EPOT", "Pseudo-adiabatic pot. temp. [K]"},
   /* 15 */ {"TMAX", "Max. temp. [K]"},
   /* 16 */ {"TMIN", "Min. temp. [K]"},
   /* 17 */ {"DPT", "Dew point temp. [K]"},
   /* 18 */ {"DEPR", "Dew point depression [K]"},
   /* 19 */ {"LAPR", "Lapse rate [K/m]"},
   /* 20 */ {"VISIB", "Visibility [m]"},
   /* 21 */ {"RDSP1", "Radar spectra (1) [non-dim]"},
   /* 22 */ {"RDSP2", "Radar spectra (2) [non-dim]"},
   /* 23 */ {"RDSP3", "Radar spectra (3) [non-dim]"},
   /* 24 */ {"PLI", "Parcel lifted index (to 500 hPa [K]"},
   /* 25 */ {"TMPA", "Temp. anomaly [K]"},
   /* 26 */ {"PRESA", "Pressure anomaly [Pa]"},
   /* 27 */ {"GPA", "Geopotential height anomaly [gpm]"},
   /* 28 */ {"WVSP1", "Wave spectra (1) [non-dim]"},
   /* 29 */ {"WVSP2", "Wave spectra (2) [non-dim]"},
   /* 30 */ {"WVSP3", "Wave spectra (3) [non-dim]"},
   /* 31 */ {"WDIR", "Wind direction [deg]"},
   /* 32 */ {"WIND", "Wind speed [m/s]"},
   /* 33 */ {"UGRD", "u wind [m/s]"},
   /* 34 */ {"VGRD", "v wind [m/s]"},
   /* 35 */ {"STRM", "Stream function [m^2/s]"},
   /* 36 */ {"VPOT", "Velocity potential [m^2/s]"},
   /* 37 */ {"MNTSF", "Montgomery stream function [m^2/s^2]"},
   /* 38 */ {"SGCVV", "Sigma coord. vertical velocity [/s]"},
   /* 39 */ {"VVEL", "Pressure vertical velocity [Pa/s]"},
   /* 40 */ {"DZDT", "Geometric vertical velocity [m/s]"},
   /* 41 */ {"ABSV", "Absolute vorticity [/s]"},
   /* 42 */ {"ABSD", "Absolute divergence [/s]"},
   /* 43 */ {"RELV", "Relative vorticity [/s]"},
   /* 44 */ {"RELD", "Relative divergence [/s]"},
   /* 45 */ {"VUCSH", "Vertical u shear [/s]"},
   /* 46 */ {"VVCSH", "Vertical v shear [/s]"},
   /* 47 */ {"DIRC", "Direction of current [deg]"},
   /* 48 */ {"SPC", "Speed of current [m/s]"},
   /* 49 */ {"UOGRD", "u of current [m/s]"},
   /* 50 */ {"VOGRD", "v of current [m/s]"},
   /* 51 */ {"SPFH", "Specific humidity [kg/kg]"},
   /* 52 */ {"RH", "Relative humidity [%]"},
   /* 53 */ {"MIXR", "Humidity mixing ratio [kg/kg]"},
   /* 54 */ {"PWAT", "Precipitable water [kg/m^2]"},
   /* 55 */ {"VAPP", "Vapor pressure [Pa]"},
   /* 56 */ {"SATD", "Saturation deficit [Pa]"},
   /* 57 */ {"EVP", "Evaporation [kg/m^2]"},
   /* 58 */ {"CICE", "Cloud Ice [kg/m^2]"},
   /* 59 */ {"PRATE", "Precipitation rate [kg/m^2/s]"},
   /* 60 */ {"TSTM", "Thunderstorm probability [%]"},
   /* 61 */ {"APCP", "Total precipitation [kg/m^2]"},
   /* 62 */ {"NCPCP", "Large scale precipitation [kg/m^2]"},
   /* 63 */ {"ACPCP", "Convective precipitation [kg/m^2]"},
   /* 64 */ {"SRWEQ", "Snowfall rate water equiv. [kg/m^2/s]"},
   /* 65 */ {"WEASD", "Accum. snow [kg/m^2]"},
   /* 66 */ {"SNOD", "Snow depth [m]"},
   /* 67 */ {"MIXHT", "Mixed layer depth [m]"},
   /* 68 */ {"TTHDP", "Transient thermocline depth [m]"},
   /* 69 */ {"MTHD", "Main thermocline depth [m]"},
   /* 70 */ {"MTHA", "Main thermocline anomaly [m]"},
   /* 71 */ {"TCDC", "Total cloud cover [%]"},
   /* 72 */ {"CDCON", "Convective cloud cover [%]"},
   /* 73 */ {"LCDC", "Low level cloud cover [%]"},
   /* 74 */ {"MCDC", "Mid level cloud cover [%]"},
   /* 75 */ {"HCDC", "High level cloud cover [%]"},
   /* 76 */ {"CWAT", "Cloud water [kg/m^2]"},
   /* 77 */ {"BLI", "Best lifted index to 500 hPa [K]"},
   /* 78 */ {"SNOC", "Convective snow [kg/m^2]"},
   /* 79 */ {"SNOL", "Large scale snow [kg/m^2]"},
   /* 80 */ {"WTMP", "Water temp. [K]"},
   /* 81 */ {"LAND", "Land-sea mask [1=land; 0=sea]"},
   /* 82 */ {"DSLM", "Deviation of sea level from mean [m]"},
   /* 83 */ {"SFCR", "Surface roughness [m]"},
   /* 84 */ {"ALBDO", "Albedo [%]"},
   /* 85 */ {"TSOIL", "Soil temp. [K]"},
   /* 86 */ {"SOILM", "Soil moisture content [kg/m^2]"},
   /* 87 */ {"VEG", "Vegetation [%]"},
   /* 88 */ {"SALTY", "Salinity [kg/kg]"},
   /* 89 */ {"DEN", "Density [kg/m^3]"},
   /* 90 */ {"RUNOF", "Runoff [kg/m^2]"},
   /* 91 */ {"ICEC", "Ice concentration [ice=1;no ice=0]"},
   /* 92 */ {"ICETK", "Ice thickness [m]"},
   /* 93 */ {"DICED", "Direction of ice drift [deg]"},
   /* 94 */ {"SICED", "Speed of ice drift [m/s]"},
   /* 95 */ {"UICE", "u of ice drift [m/s]"},
   /* 96 */ {"VICE", "v of ice drift [m/s]"},
   /* 97 */ {"ICEG", "Ice growth rate [m/s]"},
   /* 98 */ {"ICED", "Ice divergence [/s]"},
   /* 99 */ {"SNOM", "Snow melt [kg/m^2]"},
   /* 100 */ {"HTSGW", "Sig height of wind waves and swell [m]"},
   /* 101 */ {"WVDIR", "Direction of wind waves [deg]"},
   /* 102 */ {"WVHGT", "Sig height of wind waves [m]"},
   /* 103 */ {"WVPER", "Mean period of wind waves [s]"},
   /* 104 */ {"SWDIR", "Direction of swell waves [deg]"},
   /* 105 */ {"SWELL", "Sig height of swell waves [m]"},
   /* 106 */ {"SWPER", "Mean period of swell waves [s]"},
   /* 107 */ {"DIRPW", "Primary wave direction [deg]"},
   /* 108 */ {"PERPW", "Primary wave mean period [s]"},
   /* 109 */ {"DIRSW", "Secondary wave direction [deg]"},
   /* 110 */ {"PERSW", "Secondary wave mean period [s]"},
   /* 111 */ {"NSWRS", "Net short wave (surface) [W/m^2]"},
   /* 112 */ {"NLWRS", "Net long wave (surface) [W/m^2]"},
   /* 113 */ {"NSWRT", "Net short wave (top) [W/m^2]"},
   /* 114 */ {"NLWRT", "Net long wave (top) [W/m^2]"},
   /* 115 */ {"LWAVR", "Long wave [W/m^2]"},
   /* 116 */ {"SWAVR", "Short wave [W/m^2]"},
   /* 117 */ {"GRAD", "Global radiation [W/m^2]"},
   /* 118 */ {"BRTMP", "Brightness temperature [K]"},
   /* 119 */ {"LWRAD", "Radiance (with respect to wave number) [W/m sr]"},
   /* 120 */ {"SWRAD", "Radiance (with respect to wave length) [W/m^3 sr]"},
   /* 121 */ {"LHTFL", "Latent heat flux [W/m^2]"},
   /* 122 */ {"SHTFL", "Sensible heat flux [W/m^2]"},
   /* 123 */ {"BLYDP", "Boundary layer dissipation [W/m^2]"},
   /* 124 */ {"UFLX", "Zonal momentum flux [N/m^2]"},
   /* 125 */ {"VFLX", "Meridional momentum flux [N/m^2]"},
   /* 126 */ {"WMIXE", "Wind mixing energy [J]"},
   /* 127 */ {"IMGD", "Image data [integer]"},
   /* 128 */ {"M3HPCP", "Average 3hr precip [mm/hr]"},
   /* 129 */ {"var129", "blank [numeric]"},
   /* 130 */ {"GBASE", "Geopotential Base State [m/s2]"},
   /* 131 */ {"var131", "blank [numeric]"},
   /* 132 */ {"var132", "blank [numeric]"},
   /* 133 */ {"var133", "blank [numeric]"},
   /* 134 */ {"var134", "blank [numeric]"},
   /* 135 */ {"DUSVIS", "Dust Visibility [m]"},
   /* 136 */ {"DUSCON", "Dust Concentration [ug m-3]"},
   /* 137 */ {"DUSFLX", "Dust Flux [ug m-2 s-1]"},
   /* 138 */ {"EXTUV", "Aerosol extinction ultraviolet (0.3 um) [km^-1]"},
   /* 139 */ {"EXTVIS", "Aerosol extinction visible (0.55 um) [km^-1]"},
   /* 140 */ {"EXTNIR", "Aerosol extinction near infrared (1.06 um) [km^-1]"},
   /* 141 */ {"EXTMIR", "Aerosol extinction mid infrared (3-5 um) [km^-1]"},
   /* 142 */ {"EXTLIR", "Aerosol extinction long infrared (8-12 um) [km^-1]"},
   /* 143 */ {"ASYMUV", "Aerosol asymmetry ultraviolet (0.3 um) [numeric]"},
   /* 144 */ {"ASYMVIS", "Aerosol asymmetry visible (0.55 um) [numeric]"},
   /* 145 */ {"ASYMNIR", "Aerosol asymmetry near infrared (1.06 um) [numeric]"},
   /* 146 */ {"AODUV", "Aerosol optical depth (0.3 um) [numeric]"},
   /* 147 */ {"AODVIS", "Aerosol optical depth (0.55 um) [numeric]"},
   /* 148 */ {"AODNIR", "Aerosol Optical depth (1.06 um) [numeric]"},
   /* 149 */ {"SCTUV", "Aerosol scattering ultraviolet [km^-1]"},
   /* 150 */ {"SCTVIS", "Aerosol scattering visible (0.55um) [km^-1]"},
   /* 151 */ {"SCTNIR", "Aerosol scattering near infrared (1.06um) [km^-1]"},
   /* 152 */ {"var152", "blank [numeric]"},
   /* 153 */ {"var153", "blank [numeric]"},
   /* 154 */ {"var154", "blank [numeric]"},
   /* 155 */ {"var155", "blank [numeric]"},
   /* 156 */ {"var156", "blank [numeric]"},
   /* 157 */ {"var157", "blank [numeric]"},
   /* 158 */ {"var158", "blank [numeric]"},
   /* 159 */ {"var159", "blank [numeric]"},
   /* 160 */ {"var160", "blank [numeric]"},
   /* 161 */ {"var161", "blank [numeric]"},
   /* 162 */ {"var162", "blank [numeric]"},
   /* 163 */ {"var163", "blank [numeric]"},
   /* 164 */ {"var164", "blank [numeric]"},
   /* 165 */ {"var165", "blank [numeric]"},
   /* 166 */ {"var166", "blank [numeric]"},
   /* 167 */ {"var167", "blank [numeric]"},
   /* 168 */ {"var168", "blank [numeric]"},
   /* 169 */ {"var169", "blank [numeric]"},
   /* 170 */ {"var170", "blank [numeric]"},
   /* 171 */ {"var171", "blank [numeric]"},
   /* 172 */ {"var172", "blank [numeric]"},
   /* 173 */ {"var173", "blank [numeric]"},
   /* 174 */ {"var174", "blank [numeric]"},
   /* 175 */ {"var175", "blank [numeric]"},
   /* 176 */ {"var176", "blank [numeric]"},
   /* 177 */ {"var177", "blank [numeric]"},
   /* 178 */ {"var178", "blank [numeric]"},
   /* 179 */ {"var179", "blank [numeric]"},
   /* 180 */ {"var180", "blank [numeric]"},
   /* 181 */ {"var181", "blank [numeric]"},
   /* 182 */ {"var182", "blank [numeric]"},
   /* 183 */ {"var183", "blank [numeric]"},
   /* 184 */ {"var184", "blank [numeric]"},
   /* 185 */ {"var185", "blank [numeric]"},
   /* 186 */ {"var186", "blank [numeric]"},
   /* 187 */ {"var187", "blank [numeric]"},
   /* 188 */ {"DISTBIN1", "Particle Distribution Size Bin 1 [numeric]"},
   /* 189 */ {"DISTBIN2", "Particle Distribution Size Bin 2 [numeric]"},
   /* 190 */ {"DISTBIN3", "Particle Distribution Size Bin 3 [numeric]"},
   /* 191 */ {"DISTBIN4", "Particle Distribution Size Bin 4 [numeric]"},
   /* 192 */ {"DISTBIN5", "Particle Distribution Size Bin 5 [numeric]"},
   /* 193 */ {"DISTBIN6", "Particle Distribution Size Bin 6 [numeric]"},
   /* 194 */ {"DISTBIN7", "Particle Distribution Size Bin 7 [numeric]"},
   /* 195 */ {"DISTBIN8", "Particle Distribution Size Bin 8 [numeric]"},
   /* 196 */ {"DISTBIN9", "Particle Distribution Size Bin 9 [numeric]"},
   /* 197 */ {"DISTBIN10", "Particle Distribution Size Bin 10 [numeric]"},
   /* 198 */ {"var198", "blank [numeric]"},
   /* 199 */ {"var199", "blank [numeric]"},
   /* 200 */ {"var200", "blank [numeric]"},
   /* 201 */ {"var201", "blank [numeric]"},
   /* 202 */ {"var202", "blank [numeric]"},
   /* 203 */ {"var203", "blank [numeric]"},
   /* 204 */ {"var204", "blank [numeric]"},
   /* 205 */ {"var205", "blank [numeric]"},
   /* 206 */ {"var206", "blank [numeric]"},
   /* 207 */ {"var207", "blank [numeric]"},
   /* 208 */ {"var208", "blank [numeric]"},
   /* 209 */ {"var209", "blank [numeric]"},
   /* 210 */ {"var210", "blank [numeric]"},
   /* 211 */ {"var211", "blank [numeric]"},
   /* 212 */ {"var212", "blank [numeric]"},
   /* 213 */ {"var213", "blank [numeric]"},
   /* 214 */ {"var214", "blank [numeric]"},
   /* 215 */ {"var215", "blank [numeric]"},
   /* 216 */ {"var216", "blank [numeric]"},
   /* 217 */ {"var217", "blank [numeric]"},
   /* 218 */ {"var218", "blank [numeric]"},
   /* 219 */ {"var219", "blank [numeric]"},
   /* 220 */ {"var220", "blank [numeric]"},
   /* 221 */ {"var221", "blank [numeric]"},
   /* 222 */ {"var222", "blank [numeric]"},
   /* 223 */ {"var223", "blank [numeric]"},
   /* 224 */ {"var224", "blank [numeric]"},
   /* 225 */ {"var225", "blank [numeric]"},
   /* 226 */ {"var226", "blank [numeric]"},
   /* 227 */ {"var227", "blank [numeric]"},
   /* 228 */ {"var228", "blank [numeric]"},
   /* 229 */ {"var229", "blank [numeric]"},
   /* 230 */ {"var230", "blank [numeric]"},
   /* 231 */ {"var231", "blank [numeric]"},
   /* 232 */ {"var232", "blank [numeric]"},
   /* 233 */ {"var233", "blank [numeric]"},
   /* 234 */ {"var234", "blank [numeric]"},
   /* 235 */ {"var235", "blank [numeric]"},
   /* 236 */ {"var236", "blank [numeric]"},
   /* 237 */ {"var237", "blank [numeric]"},
   /* 238 */ {"var238", "blank [numeric]"},
   /* 239 */ {"var239", "blank [numeric]"},
   /* 240 */ {"var240", "blank [numeric]"},
   /* 241 */ {"var241", "blank [numeric]"},
   /* 242 */ {"var242", "blank [numeric]"},
   /* 243 */ {"var243", "blank [numeric]"},
   /* 244 */ {"var244", "blank [numeric]"},
   /* 245 */ {"var245", "blank [numeric]"},
   /* 246 */ {"var246", "blank [numeric]"},
   /* 247 */ {"var247", "blank [numeric]"},
   /* 248 */ {"var248", "blank [numeric]"},
   /* 249 */ {"var249", "blank [numeric]"},
   /* 250 */ {"var250", "blank [numeric]"},
   /* 251 */ {"var251", "blank [numeric]"},
   /* 252 */ {"var252", "blank [numeric]"},
   /* 253 */ {"LAT", "Latitude [deg]"},
   /* 254 */ {"LON", "Longitude [deg]"},
   /* 255 */ {"var255", "Missing [numeric]"},

};


