on: [pull_request, workflow_dispatch]

jobs:
  check-dependency-availability:
    name: Check fresh compile and assemble of the project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Build with Gradle (refresh dependencies)
        run: ./gradlew clean classes testClasses assemble --refresh-dependencies

