on: [pull_request]

jobs:
  tests-zulu:
    name: netCDF-Java Tests (Zulu)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest 8
        java: [ 8 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
      - name: Install netCDF-C
        run: sudo apt update && sudo apt-get install libnetcdf-dev
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build and test with Gradle
        run: ./gradlew --info --stacktrace testAll
        env:
          TRAVIS: 'true'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: netCDF-Java-TDS_JUnit_Results_${{ github.sha }}_Zulu-${{ matrix.java }}
          path: build/reports/allTests

  tests-adpotopen-hs:
    name: netCDF-Java Tests (Adoptium-HS)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest Adoptium 8 LTS release
        java: [ 8 ]
    steps:
      - uses: actions/checkout@v2
      - name: Fetch latest Adoptium ${{ matrix.java }} (hotspot) built for linux
        run: curl -L "https://api.adoptopenjdk.net/v3/binary/latest/${{ matrix.java }}/ga/linux/x64/jdk/hotspot/normal/adoptopenjdk" -o aojdk${{ matrix.java }}-hs.tar.gz
      - name: Setup Latest Adoptium 8 (hotspot) ${{ matrix.java }}
        uses: actions/setup-java@master
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
          jdkFile: ./aojdk${{ matrix.java }}-hs.tar.gz
      - name: Print java version
        run: java -version
      - name: Install netCDF-C
        run: sudo apt update && sudo apt-get install libnetcdf-dev
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ matrix.java }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-${{ matrix.java }}-gradle
      - name: Build and test with Gradle
        run: ./gradlew --info --stacktrace testAll
        env:
          TRAVIS: 'true'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: netCDF-Java-TDS_JUnit_Results_${{ github.sha }}Adoptium-HS-${{ matrix.java }}
          path: build/reports/allTests

  check-assemble-adpotopen-hs:
    name: Check fresh assemble of netCDF-Java project (Adoptium-HS)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch latest Adoptium 8 (hotspot) built for linux
        run: curl -L "https://api.adoptopenjdk.net/v3/binary/latest/8/ga/linux/x64/jdk/hotspot/normal/adoptopenjdk" -o aojdk8-hs.tar.gz
      - name: Setup Latest Adoptium 8 (hotspot)
        uses: actions/setup-java@master
        with:
          java-version: 8
          architecture: x64
          jdkFile: ./aojdk8-hs.tar.gz
      - name: Print java version
        run: java -version
      - name: Build with Gradle
        run: ./gradlew assemble --refresh-dependencies
